### ISSUE TITLE
Реализация поиска на странице "Игроки"

### ISSUE THREAD

**Issue by KonstantinRaikhert** [Studio-Yandex-Practicum/adaptive_hockey_federation#122]
# Зачем?

Необходимо реализивать поиск для странице игроки. Для этого нужно сделать отдельные ендпоинт(ы), views и фильтры

![2024-01-22_13-16](https://github.com/Studio-Yandex-Practicum/adaptive_hockey_federation/assets/69113745/c8cf35b4-b666-41cf-81ca-a52c2d5fa9cf)
![2024-01-22_13-16_1](https://github.com/Studio-Yandex-Practicum/adaptive_hockey_federation/assets/69113745/e2cca420-f0ed-404c-b544-c97fa92e0e0e)

Важна реализация по выбору фильра (Имя, диагноз и тд)

# Как нужно делать?

- изучить лучшие практики в применении поиска у джанго проектов
- уделить внимание к Q и возможно F объектам формирования queryset
- завести необходимые ендпоинты и вьюхи

# Где?

adaptive_hockey_federation/main

**Comment by mysm** [comment]
Ветку от adaptive_hockey_federation/main клонировать?

**Comment by KonstantinRaikhert** [comment]
Нет, так же от dev. Это относительный путь папки, где сейчас работаем

**Comment by mysm** [comment]
Прошу уточнить, как должен работать интерфейс поиска?
1. Из выпадающего списка выбирает поле поиска. 
2. Поле поиска должно появляться в окошке поиска.
3. В поле поиска вводится искомое вхождение и нажимается кнопка с лупой.
4. В списке появляются только строки с подходящими значениями.

Все правильно? Или как-то иначе?

**Comment by KonstantinRaikhert** [comment]
> Прошу уточнить, как должен работать интерфейс поиска?
> 
> 1. Из выпадающего списка выбирает поле поиска.
> 2. Поле поиска должно появляться в окошке поиска.
> 3. В поле поиска вводится искомое вхождение и нажимается кнопка с лупой.
> 4. В списке появляются только строки с подходящими значениями.
> 
> Все правильно? Или как-то иначе?

Из выпадающего списка выбирается тип данных и этот тип работает как фильтр (в кверисете добавляем фильтр по этому типу и ищем). Если не выбрано ничего из выпадающего списка -> поиск по всем полям

**Comment by mysm** [comment]
> > Прошу уточнить, как должен работать интерфейс поиска?
> > 
> > 1. Из выпадающего списка выбирает поле поиска.
> > 2. Поле поиска должно появляться в окошке поиска.
> > 3. В поле поиска вводится искомое вхождение и нажимается кнопка с лупой.
> > 4. В списке появляются только строки с подходящими значениями.
> > 
> > Все правильно? Или как-то иначе?
> 
> Из выпадающего списка выбирается тип данных и этот тип работает как фильтр (в кверисете добавляем фильтр по этому типу и ищем). Если не выбрано ничего из выпадающего списка -> поиск по всем полям

Там странно html страница отрабатывает. Когда выбираешь поле для поиска идет get запрос с параметром 'search_column'. Затем когда набираешь строку поиска, то идет запрос только со строкой поиска. Поля поиска там нет. Получается, при выборе поля поиска, его где-то запоминать надо? А можно переделать фронт, чтобы как-то фиксировалось поле поиска и передавалось вместе со строкой поиска? 
Я сейчас сделал что тупо ищется сразу по всем полям. Но, как я понимаю, это не совсем то. Чтобы искать по одному полю, хотелось бы чтобы оно в GET параметре шло вместе со строкой запроса.

**Comment by KonstantinRaikhert** [comment]
> > > Прошу уточнить, как должен работать интерфейс поиска?
> > > 
> > > 1. Из выпадающего списка выбирает поле поиска.
> > > 2. Поле поиска должно появляться в окошке поиска.
> > > 3. В поле поиска вводится искомое вхождение и нажимается кнопка с лупой.
> > > 4. В списке появляются только строки с подходящими значениями.
> > > 
> > > Все правильно? Или как-то иначе?
> > 
> > 
> > Из выпадающего списка выбирается тип данных и этот тип работает как фильтр (в кверисете добавляем фильтр по этому типу и ищем). Если не выбрано ничего из выпадающего списка -> поиск по всем полям
> 
> Там странно html страница отрабатывает. Когда выбираешь поле для поиска идет get запрос с параметром 'search_column'. Затем когда набираешь строку поиска, то идет запрос только со строкой поиска. Поля поиска там нет. Получается, при выборе поля поиска, его где-то запоминать надо? А можно переделать фронт, чтобы как-то фиксировалось поле поиска и передавалось вместе со строкой поиска? Я сейчас сделал что тупо ищется сразу по всем полям. Но, как я понимаю, это не совсем то. Чтобы искать по одному полю, хотелось бы чтобы оно в GET параметре шло вместе со строкой запроса. У нас, я видел, как раз фронт-эндер добавился.

Тут лучше поискать, как это реализуется с шаблонизатором джанги. Каким образом нам надо передать параметр. Может здесь необходимо будет писать ajax запрос и делать отдельный ендпоинт (ajax написать должна помочь Алина).
Посмотри пожалуйста, готовые решения явно должны присутствовать. Пул реквест с существующими наработками тоже можно сделать)

**Comment by mysm** [comment]
> > > > Прошу уточнить, как должен работать интерфейс поиска?
> > > > 
> > > > 1. Из выпадающего списка выбирает поле поиска.
> > > > 2. Поле поиска должно появляться в окошке поиска.
> > > > 3. В поле поиска вводится искомое вхождение и нажимается кнопка с лупой.
> > > > 4. В списке появляются только строки с подходящими значениями.
> > > > 
> > > > Все правильно? Или как-то иначе?
> > > 
> > > 
> > > Из выпадающего списка выбирается тип данных и этот тип работает как фильтр (в кверисете добавляем фильтр по этому типу и ищем). Если не выбрано ничего из выпадающего списка -> поиск по всем полям
> > 
> > 
> > Там странно html страница отрабатывает. Когда выбираешь поле для поиска идет get запрос с параметром 'search_column'. Затем когда набираешь строку поиска, то идет запрос только со строкой поиска. Поля поиска там нет. Получается, при выборе поля поиска, его где-то запоминать надо? А можно переделать фронт, чтобы как-то фиксировалось поле поиска и передавалось вместе со строкой поиска? Я сейчас сделал что тупо ищется сразу по всем полям. Но, как я понимаю, это не совсем то. Чтобы искать по одному полю, хотелось бы чтобы оно в GET параметре шло вместе со строкой запроса. У нас, я видел, как раз фронт-эндер добавился.
> 
> Тут лучше поискать, как это реализуется с шаблонизатором джанги. Каким образом нам надо передать параметр. Может здесь необходимо будет писать ajax запрос и делать отдельный ендпоинт (ajax написать должна помочь Алина). Посмотри пожалуйста, готовые решения явно должны присутствовать. Пул реквест с существующими наработками тоже можно сделать)

Джанга гибкая. Можно реализовать через отдельный url можно в рамках параметров к существующим. Тут скорее вопрос, как это должно выглядеть для пользователя.  Мне не совсем понятна изначальная задумка, когда и поле поиска и строка поиска задаются в одном поле. Я бы делал в разных полях.


![Image](https://github.com/Studio-Yandex-Practicum/adaptive_hockey_federation/assets/2930783/aad5ff7d-3c5a-449e-8cc0-461dc50d812f)

Сделал коммит с поиском по все полям, чтобы было ясно в каком направлении двигаюсь. В данном случае, мне кажется, надо доделать фронт. Если бы делал я, то сделал бы два поля - одно с выбором где ищем, второе - что ищем. Если идея вместить все именно в одно поле, то тут моей фронтовой квалификации не хватает.

**Comment by mysm** [comment]
Сделал полноценный поиск по полям players и заодно поправил отображение списка игроков.



![Image](https://github.com/Studio-Yandex-Practicum/adaptive_hockey_federation/assets/2930783/2e2610fd-ca93-4a55-8f0b-003be40c2982)




![Image](https://github.com/Studio-Yandex-Practicum/adaptive_hockey_federation/assets/2930783/0aac2dbe-a678-4d22-8a46-308e516cbcbb)




![Image](https://github.com/Studio-Yandex-Practicum/adaptive_hockey_federation/assets/2930783/1b4264dc-a49f-4a52-9894-23d9289a1a91)
