### ISSUE TITLE
Реализовать редактирование и удаление комманд

### ISSUE THREAD

**Issue by KonstantinRaikhert** [Studio-Yandex-Practicum/adaptive_hockey_federation#123]
# Зачем?

Сейчас эти кнопки не работают
![2024-01-22_13-38](https://github.com/Studio-Yandex-Practicum/adaptive_hockey_federation/assets/69113745/d21eee8d-817a-46d8-92c3-820c7d44b7ce)

# Как нужно делать?

- необходимо написать необходимые views и endpoints
- привязать к шаблону

# Где?

adaptive_hockey_federation/main

**Comment by alexesma** [comment]
Добрый день Константин, я отправил код на pull request, просьба проверить, спасибо.
