### ISSUE TITLE
Создать CI для сборки докер образов на github packages

### ISSUE THREAD

**Issue by KonstantinRaikhert** [Studio-Yandex-Practicum/adaptive_hockey_federation#128]
# Зачем?

Это нам будет необходимо для дальнейшего разворачивания нашего приложения на сервере.

# Как нужно делать?

- разобраться как это работает.
- реализовать с присвоением тегов - в зависимости от ветки

Пример можно посмотреть тут - https://github.com/Studio-Yandex-Practicum/RandomCoffeeBotTelegram/blob/develop/.github/workflows/build-and-push-github-packages.yml

# Где?

.github/workflows

**Comment by KonstantinRaikhert** [comment]
@mysm Привет! Появились сложности?

**Comment by mysm** [comment]
> [@mysm](https://github.com/mysm) Привет! Появились сложности?

Привет! Какие действия должны совершаться? Для каждой ветки.

**Comment by KonstantinRaikhert** [comment]
> > [@mysm](https://github.com/mysm) Привет! Появились сложности?
> 
> Привет! Какие действия должны совершаться? Для каждой ветки.

Для каждой ветки должен собираться образ с соответствующим тегом

**Comment by mysm** [comment]
> > > [@mysm](https://github.com/mysm) Привет! Появились сложности?
> > 
> > 
> > Привет! Какие действия должны совершаться? Для каждой ветки.
> 
> Для каждой ветки должен собираться образ с соответствующим тегом

Т.е. все аналогично примеру?
