### ISSUE TITLE
Рефакторинг шаблонов в папке templates

### ISSUE THREAD

**Issue by KonstantinRaikhert** [Studio-Yandex-Practicum/adaptive_hockey_federation#129]
# Зачем?

Необходимо все шаблоны и includes разложить по папкам сущностей и приложений. Сейчас проявляется проблема в том, что многие шаблоны путаются между собой. 
![2024-01-30_16-13](https://github.com/Studio-Yandex-Practicum/adaptive_hockey_federation/assets/69113745/c5b10e65-1e2a-444c-8e37-7e0e085deefc)

# Как нужно делать?

- думаю, что стоит для каждой страницы разложить шаблоны по папкам
- завести на каждую страницу свой шаблон (таблица и тд)

Вообще мне не очень нравится такая идея, но универсализация шаблонов мне кажется может привести нас в большие дебри и еще сильнее отстанем

# Где?

adaptive_hockey_federation/templates

**Comment by Pogorelii1993** [comment]
"завести на каждую страницу свой шаблон (таблица и тд)"

Я правильно понимаю, что внутри папок будут повторяться некоторые html шаблоны кнопок, таблиц, форм и т.п., так как, некоторые из них одинаковые для всех страниц?

**Comment by KonstantinRaikhert** [comment]
> "завести на каждую страницу свой шаблон (таблица и тд)"
> 
> Я правильно понимаю, что внутри папок будут повторяться некоторые html шаблоны кнопок, таблиц, форм и т.п., так как, некоторые из них одинаковые для всех страниц?

Да, мне это конечно самому не нравится. Но видимо придётся))
