### ISSUE TITLE
Реализация моделей и фабрик на блок Соревнования

### ISSUE THREAD

**Issue by KonstantinRaikhert** [Studio-Yandex-Practicum/adaptive_hockey_federation#137]
# Зачем?

Приступаем к следующему блоку и здесь нам необходимо проработать модели и сделать фабрики для их заполнения

# Как нужно делать?

- я считаю что нужно сделать отдельное приложение "соревнования"
- в этом приложении оформить модели по макету
- написать фабрики наполнения (соревнований 30)
- добавить правки в ER-диаграмму

# Где?

**Comment by KonstantinRaikhert** [comment]
@Aleksey-Krd Возьмешь)

**Comment by Aleksey-Krd** [comment]
@KonstantinRaikhert  Попробую), почему бы и нет
