### ISSUE TITLE
Реализовать деплой (CD) на сервер

### ISSUE THREAD

**Issue by KonstantinRaikhert** [Studio-Yandex-Practicum/adaptive_hockey_federation#144]
# Зачем?

Будем реализовывать стейдж для проверки нашего сервиса на виртуальной машине

# Как нужно делать?

- прислать мне свой ssh, чтобы я дал доступ к VPS
- на машине создать нового пользователя и дать ему все необходимые права (docker и что будет необходимо)
- реализовать workflow для деплоя приложения ([пример](https://github.com/Studio-Yandex-Practicum/RandomCoffeeBotTelegram/blob/develop/.github/workflows/stage_deploy.yml))

# Где?

84.201.161.166

**Comment by KonstantinRaikhert** [comment]
@xxfeel Интересно?)

**Comment by xxfeel** [comment]
Да, возьмусь=) Но могу провалить по сроку исполнения...
