### ISSUE TITLE
Отрефакторить views в main (создать отдельную папку)

### ISSUE THREAD

**Issue by KonstantinRaikhert** [Studio-Yandex-Practicum/adaptive_hockey_federation#145]
# Зачем?

Сейчас в приложении main наш views.py слишком стал большим. Необходимо декомпозировать

# Как нужно делать?

Создать папку views и отдельно в каждом файле разместить наши вьюхи (player_views.py например)

# Где?

adaptive_hockey_federation/main/views.py

**Comment by mysm** [comment]
Разделение на 
- Players
- Teams

или более подробно разделить?
