### ISSUE TITLE
Реализация создания нового пользователя с отправком письма с заданием пароля (только администратор)

### ISSUE THREAD

**Issue by KonstantinRaikhert** [Studio-Yandex-Practicum/adaptive_hockey_federation#146]
# Зачем?

Необходимо сделать через форму создание нового пользователя
![2024-02-07_18-55](https://github.com/Studio-Yandex-Practicum/adaptive_hockey_federation/assets/69113745/ed6b6e2c-aa40-43a6-8fcd-79b6e0d0a03c)

# Как нужно делать?

- создать форму
- реализовать шаблон
- настроить пермишены

# Где?

adaptive_hockey_federation/users

**Comment by KonstantinRaikhert** [comment]
@Aleksey-Krd Ты еще в деле?))
Слушай мы же что то уже делали с созданием пользователя, разве нет? Найти в коде не могу...

**Comment by Aleksey-Krd** [comment]
@KonstantinRaikhert в деле конечно))), делали, я же лично это и делал

**Comment by Aleksey-Krd** [comment]
![Image](https://github.com/Studio-Yandex-Practicum/adaptive_hockey_federation/assets/118228004/5f3b4895-50b2-45fa-ad1b-c1e0e0c3b9e3)

users/views

**Comment by KonstantinRaikhert** [comment]
> @KonstantinRaikhert починил у себя, в общем вьюха рабочая, пользователь создаётся, надо реализовать чтоб пароль через почту менялся?

Ага. Необходимо, чтобы письмо приходило на почту этого юзера. Посмотри, есть готовые решения на это на основе джанги. Сам шаблон письма можно сделать пока простой. 
Важно положить функционал по использованию бэкенда почтового помимо консольного, еще и серверного
