### ISSUE TITLE
Реализация функционала создания игрока (без пермишенов)

### ISSUE THREAD

**Issue by KonstantinRaikhert** [Studio-Yandex-Practicum/adaptive_hockey_federation#148]
# Зачем?

Необходима кнопка для форма создания игрока (как выглядить можно взять с других шаблонов)
![2024-02-08_17-37](https://github.com/Studio-Yandex-Practicum/adaptive_hockey_federation/assets/69113745/09d86322-1a9d-4aec-b042-77e492b3afb5)
В форме должны быть те же данные как и в админке - http://127.0.0.1:8000/admin/main/player/add/

# Как нужно делать?

- необходимо доработать шаблон, создать кнопку
- написать форму для шаблона
- добавить необходимые urls
- написать вьюху

# Где?

adaptive_hockey_federation/templates/main/player_id
adaptive_hockey_federation/main/views.py
adaptive_hockey_federation/main/urls.py

**Comment by AntAresWeb** [comment]
Представляю себе такой план действий:
1. Создать ветку feature/create-player, производную  от dev
2. В темплейте base/footer.html добавить кнопку "Создать" видимую для случая, когда этот футтер инклайдится в main/payers/players.html
3. Создать темплейт main/player_id/player_id_create.html по аналогии темплейта для редактирования main/player_id/player_id_edit.html. А может быть не создавать, а использовать который для редактирования?
4. Создать view-класс PlayerIDCreateView, производный от CreateView для работы с этим темплейтом
6. В main/urls.py прописать роут для вызова этого класса.

**Comment by KonstantinRaikhert** [comment]
> Представляю себе такой план действий:
> 
> 1. Создать ветку feature/create-player, производную  от dev
> 
> 2. В темплейте base/footer.html добавить кнопку "Создать" видимую для случая, когда этот футтер инклайдится в main/payers/players.html
> 
> 3. Создать темплейт main/player_id/player_id_create.html по аналогии темплейта для редактирования main/player_id/player_id_edit.html. А может быть не создавать, а использовать который для редактирования?
> 
> 4. Создать view-класс PlayerIDCreateView, производный от CreateView для работы с этим темплейтом
> 
> 6. В main/urls.py прописать роут для вызова этого класса.

👍
По поводу пункта 3:
Необходимо понять насколько возможно использовать один шаблон, скорее всего никаких проблем. Но тогда правильно его переименовать
