### ISSUE TITLE
На странице ID команды поправить баг и дополнить функционал

### ISSUE THREAD

**Issue by KonstantinRaikhert** [Studio-Yandex-Practicum/adaptive_hockey_federation#152]
# Зачем?

На странице состава команды (/teams/{id}/) есть баг с отображением в таблицах
![2024-02-08_17-22](https://github.com/Studio-Yandex-Practicum/adaptive_hockey_federation/assets/69113745/a4118a39-7d5e-4ce4-8fba-78229df8ee98)
Так же отображаются только тренеры и игроки, необходимо добавить возможность отображения других членов команды

# Как нужно делать?

- багфикс нужно проводить во views.py там собираются таблицы
- необходимо дополнить отображение в шаблоне помимо тренера еще "другой". Но заложить возможность отображения всех choices, если будем масштабировать
![2024-02-08_17-23](https://github.com/Studio-Yandex-Practicum/adaptive_hockey_federation/assets/69113745/0b1f8d12-5254-4ab4-8237-9cac5558ec02)

# Где?

adaptive_hockey_federation/main/views.py
adaptive_hockey_federation/templates/main/teams_id

**Comment by pandenic** [comment]
Правильно ли я понял что тут по-сути две задачи:

1) bugfix отображения неиспользуемых неактивных кнопок вы части соответствия столбцам (то есть сместить на 2 вправо)?
![Selection_338](https://github.com/Studio-Yandex-Practicum/adaptive_hockey_federation/assets/114985447/00220e9b-3df7-4040-b79a-cfed81e0044f)

2) feature добавить возможность отображать ещё таблицу "другой" сверху?
![Selection_339](https://github.com/Studio-Yandex-Practicum/adaptive_hockey_federation/assets/114985447/dd459732-9290-4a5c-880f-5ad03e119dab)

**Comment by KonstantinRaikhert** [comment]
> Правильно ли я понял что тут по-сути две задачи:
> 
> 1. bugfix отображения неиспользуемых неактивных кнопок вы части соответствия столбцам (то есть сместить на 2 вправо)?
>    ![Selection_338](https://private-user-images.githubusercontent.com/114985447/304122152-00220e9b-3df7-4040-b79a-cfed81e0044f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDc3NTI1NDAsIm5iZiI6MTcwNzc1MjI0MCwicGF0aCI6Ii8xMTQ5ODU0NDcvMzA0MTIyMTUyLTAwMjIwZTliLTNkZjctNDA0MC1iNzlhLWNmZWQ4MWUwMDQ0Zi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMjEyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDIxMlQxNTM3MjBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1jMWY2YzQwOTBmY2NlYjY1ZTFhMTExMDExYTZhMGJjYjk3NWQxZWE5Mjg2ZTkwYTk1YTg2ZjNjMGQwNGEwYTllJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.OiT1sbM91Y3BZ2SDV5-wTGbnnmtybxK8T1MsI_hO9EY)
> 2. feature добавить возможность отображать ещё таблицу "другой" сверху?
>    ![Selection_339](https://private-user-images.githubusercontent.com/114985447/304122758-dd459732-9290-4a5c-880f-5ad03e119dab.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDc3NTI1NDAsIm5iZiI6MTcwNzc1MjI0MCwicGF0aCI6Ii8xMTQ5ODU0NDcvMzA0MTIyNzU4LWRkNDU5NzMyLTkyOTAtNGE1Yy04ODBmLTVhZDAzZTExOWRhYi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMjEyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDIxMlQxNTM3MjBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1iZjIzMWZlN2EyNDdmMGQ2NDk1ODJiODI0NTRmMDNkMGVmZWZjOTY1ZGNlNWE1OGFjZmYxYWYwMjZhMGExMTdkJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.nS-_E4SRkoY6D1M3-zlbqg8w0uqnRfEfsFVG4vewmqQ)

В целом да!
по второму скрину необходимо, чтобы вывод был масштабируемым. Если мы например добавим в модели помимо тренеры и другой еще например "волонтеры", то и эту группу лиц тоже должен отображать
