### ISSUE TITLE
Реализовать отображение состава на соревнования команд

### ISSUE THREAD

**Issue by KonstantinRaikhert** [Studio-Yandex-Practicum/adaptive_hockey_federation#163]
# Зачем?

Нужно чтобы по кнопке "состав" отображались команды, которые учавствуют или участвовали в соревнованиях

![2024-02-14_21-18](https://github.com/Studio-Yandex-Practicum/adaptive_hockey_federation/assets/69113745/15cdf635-bfec-45d0-8816-66ba28c04bca)

# Как нужно делать?

- создать нужный шаблон
- views
- urls

# Где?

adaptive_hockey_federation/events

**Comment by Nikita527** [comment]
@KonstantinRaikhert не до конца понял задачу. В проекте реализованно отображение списка игроков в команде, через класс PlayerIdView и шаблоны соответствующие ему, мне нужно сделать что-то похожее? В проекте уже есть шаблон competitions_id.html, и соответствующая функция и урл. Мне нужно их доделать или мне что-то нужно сделать кардинально другое. Где-то есть пример как должна выглядеть страница после того, как переходишь по кнопке "Состав"?

**Comment by KonstantinRaikhert** [comment]
Нужно сделать другое отображение. Но можно на основе этих urls и views.
Т.е. у нас на соревнования может учавствовать несколько команд, следовательно нажимая на кнопку мы переходим на список команд на конкретное соревнование.
Ну и конечно было бы неплохо добавить ссылку чтобы можно было посмотреть состав конкретной команды
