### ISSUE TITLE
Реализовать начальный этап по блоку аналитика

### ISSUE THREAD

**Issue by KonstantinRaikhert** [Studio-Yandex-Practicum/adaptive_hockey_federation#164]
# Зачем?

Нужно сделать отображение аналитики. Возьмем пока то, что заказчик указал в макете.
![2024-02-15_18-48](https://github.com/Studio-Yandex-Practicum/adaptive_hockey_federation/assets/69113745/f7555d08-5ff2-4f81-aa06-aaf442b8f52a)
![2024-02-15_18-48_1](https://github.com/Studio-Yandex-Practicum/adaptive_hockey_federation/assets/69113745/3b0de9fb-6a60-43fc-a56f-a4d71cbbbbc9)

# Как нужно делать?

- создать отдельное приложение, чтобы разделить
- возможно лучше сделать отдельные функции для получения кверисетов
- модели вроде тут не предвидятся, поэтому вьюхи и ендпоинты

# Где?

analytics

**Comment by pandenic** [comment]
Добавил драфт пул реквеста и там написал комментарии и темы для обсуждения.
