### ISSUE TITLE
Не отображаются поля заданные choices в админке

### ISSUE THREAD

**Issue by pandenic** [Studio-Yandex-Practicum/adaptive_hockey_federation#167]
# Где был обнаружен баг ?

В админке некорректно отображаются поля где выбор значения ограничен списком вариантов.
![Selection_349](https://github.com/Studio-Yandex-Practicum/adaptive_hockey_federation/assets/114985447/32a5e019-dbb9-4017-b0fb-050ff29ad8b3)

main/models.py
![Selection_350](https://github.com/Studio-Yandex-Practicum/adaptive_hockey_federation/assets/114985447/b32136f9-4fc9-486b-9291-36607845e2c0)

core/constants.py
![image](https://github.com/Studio-Yandex-Practicum/adaptive_hockey_federation/assets/114985447/15613ed6-12bf-485a-9971-f235a9f905bf)

Однако в базе данных они есть:
![Selection_352](https://github.com/Studio-Yandex-Practicum/adaptive_hockey_federation/assets/114985447/504d7165-58a6-4a1a-a048-ee615da9e418)

Вероятно проблема в настройках каждой из админок main/admin/ или всей админки. Скорее всего нужно создать преднастроенное поле и растиражировать (как в файле main/admin/inlines.py)

**Comment by KonstantinRaikhert** [comment]
@Nurbek878 Привет! Прошу посмотреть на эту таску и написать, готов ли ты приступить?)

**Comment by Nurbek878** [comment]
Добрый вечер! Пока не смотрел таску. Немного загружен на работе. Думаю смогу наверное.12:43, 14 марта 2024 г., Konstantin Raikhert ***@***.***>:
@Nurbek878 Привет! Прошу посмотреть на эту таску и написать, готов ли ты приступить?)

—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you were mentioned.Message ID: ***@***.***>
-- Отправлено из мобильного приложения Яндекс Почты

**Comment by Nurbek878** [comment]
Хотел добавить, что это не только проблема в списке админки. Они не корректно отображаются и при редактировании на основной странице. И при редактировании внутри Персональных данных в админке. При этом если добавить новое значение или поменять старое, то все отображается.
![Uploading 1.jpg…]()
![Uploading 2.jpg…]()

**Comment by KonstantinRaikhert** [comment]
@Nurbek878 Посмотри пожалуйста тогда как тестовые данные создаются, может дело в фабриках?
