### ISSUE TITLE
Вынести все схемы из views в отдельные файлы schema

### ISSUE THREAD

**Issue by pandenic** [Studio-Yandex-Practicum/adaptive_hockey_federation#170]
# Зачем?

Схемы для context в views для загрузки в templates вынести в отдельный файл schema. Упрощает чтение кода, убирая визуальный мусор в виде огромных словарей.

# Как нужно делать?

Создать отдельные файлы schema в папках где есть views.

# Где?

![Selection_355](https://github.com/Studio-Yandex-Practicum/adaptive_hockey_federation/assets/114985447/d81496d6-77f8-47a7-973a-ce2aee0833b3)
![Selection_354](https://github.com/Studio-Yandex-Practicum/adaptive_hockey_federation/assets/114985447/aef0479b-fa2f-4c62-b4bd-df3fba51c72f)

**Comment by KonstantinRaikhert** [comment]
@mysm Привет! У тебя есть возможность заниматься задачей?

**Comment by mysm** [comment]
> [@mysm](https://github.com/mysm) Привет! У тебя есть возможность заниматься задачей?

Привет!

**Comment by KonstantinRaikhert** [comment]
@mysm Да, в целом так, только используя функции нужно type hintings применять. Чтобы понимать например что за объект players
