### ISSUE TITLE
Начать работу над пермишенами пользователей (игроки)

### ISSUE THREAD

**Issue by KonstantinRaikhert** [Studio-Yandex-Practicum/adaptive_hockey_federation#171]
# Зачем?

Отчасти они реальзованы, но не подключены до конца. 
Суть такова:
- админ может все
- модератор может менять данные на команды, соревнования, игроки
- агенты могут только менять данные на свою команду и своих игроков

У нас это сейчас реализовано через группы:
![2024-02-19_20-42](https://github.com/Studio-Yandex-Practicum/adaptive_hockey_federation/assets/69113745/da59f68b-d87b-4ccf-8a74-6378cc5ea931)
![2024-02-19_20-43](https://github.com/Studio-Yandex-Practicum/adaptive_hockey_federation/assets/69113745/05bedfa2-e389-46d3-9304-18d465b994ad)

Задача данной таски - попробовать реализовать доступы к **игрокам**.

# Как нужно делать?

- обязательно нужно проверить и дополнить, где необходимо views (как вариант дополнить миксином [PermissionRequiredMixin](https://docs.djangoproject.com/en/5.0/topics/auth/default/))
- в шаблонах можно по тэгу 
![2024-02-19_21-18](https://github.com/Studio-Yandex-Practicum/adaptive_hockey_federation/assets/69113745/0e227a9f-66d0-4edd-9de0-180477b1454c)

**ВАЖНО!** 
Если пользователь не имеет прав к удалению и редактированию, то доступы к методам (create, post, delete) тоже должны быть запрещены

# Где?

adaptive_hockey_federation/main

**Comment by KonstantinRaikhert** [comment]
@AntAresWeb Привет! Есть сложности с задачей?

**Comment by AntAresWeb** [comment]
> [@AntAresWeb](https://github.com/AntAresWeb) Привет! Есть сложности с задачей?

Константин, привет!
Вроде всё по таске сделал, запушил, откомментировал в PR.

**Comment by KonstantinRaikhert** [comment]
> > [@AntAresWeb](https://github.com/AntAresWeb) Привет! Есть сложности с задачей?
> 
> Константин, привет! Вроде всё по таске сделал, запушил, откомментировал в PR.

Привет! Спасибо, вечером посмотрю
