### ISSUE TITLE
Начать работу над пермишенами пользователей (команды)

### ISSUE THREAD

**Issue by KonstantinRaikhert** [Studio-Yandex-Practicum/adaptive_hockey_federation#172]
# Зачем?

Отчасти они реальзованы, но не подключены до конца. 
Суть такова:
- админ может все
- модератор может менять данные на команды, соревнования, игроки
- агенты могут только менять данные на свою команду и своих игроков

У нас это сейчас реализовано через группы:
![2024-02-19_20-42](https://github.com/Studio-Yandex-Practicum/adaptive_hockey_federation/assets/69113745/da59f68b-d87b-4ccf-8a74-6378cc5ea931)
![2024-02-19_20-43](https://github.com/Studio-Yandex-Practicum/adaptive_hockey_federation/assets/69113745/05bedfa2-e389-46d3-9304-18d465b994ad)

Задача данной таски - попробовать реализовать доступы к **командам**.

# Как нужно делать?

- обязательно нужно проверить и дополнить, где необходимо views (как вариант дополнить миксином [PermissionRequiredMixin](https://docs.djangoproject.com/en/5.0/topics/auth/default/))
- в шаблонах можно по тэгу 
![2024-02-19_21-18](https://github.com/Studio-Yandex-Practicum/adaptive_hockey_federation/assets/69113745/0e227a9f-66d0-4edd-9de0-180477b1454c)

**ВАЖНО!** 
Если пользователь не имеет прав к удалению и редактированию, то доступы к методам (create, post, delete) тоже должны быть запрещены

В шаблонах иконки должны убираться, если нет необходимых прав

# Где?

adaptive_hockey_federation/main

**Comment by VesselchackU** [comment]
Принял. Покопаюсь, будут вопросы - напишу.

**Comment by VesselchackU** [comment]
И снова привет. Можно прояснить некоторые детали?
1. Кто может СОЗДАВАТЬ команды - это только админам доступный функционал? 
2. У модели команды полей, которые можно в принципе поменять - четыре (название, город, модератор, представитель). Вот. В брифе я увидел такое как:
![Image](https://github.com/Studio-Yandex-Practicum/adaptive_hockey_federation/assets/118609265/79c3e1e7-3925-48b0-9805-593501f0589a)
... и поэтому не очень понятно, например, какие данные по команде может изменить, скажем, модератор. 
2.1. Модератор может поменять представителя команды (по моей логике, исходящей из простого мироощущения, - да)? 
2.2. Модератор может менять модератора команды (по логике - нет). 
2.3. А представитель команды может поменять модератора в своей команде (по логике - нет)? 
2.4. Представитель команды может поменять представителя (по логике - нет)?
2.5. Если представитель вообще ничего не может (смена города и названия, думаю, практически исключены, а если допустить, что такое в редких случаях возможно, то это все равно, опять же, по логике - не прерогатива представителя), то, я правильно понимаю, что ему нужно вообще запретить диалог редактирования данных команды? 
3. Я правильно понимаю, что в мою таску входят чисто вопросы, касающиеся внесения изменений в основные поля модели "Team"? Потому что я вижу, что в части пермишенов по игрокам - есть другая таска. 

Спасибо за разъяснения. И сорри за многобукаф.

**Comment by KonstantinRaikhert** [comment]
@VesselchackU действительно многабукаф))
1. Да, админ обладает возможностью удалять всё, и создавать всё. 
2. куратор - агент, тут правильно. Агент может взаимодействовать только со своей командой и игроками и тренерами из своей команды. Может менять данные, загружать или удалять документы. Удалять или дополнять игроков, тренеров. НО не может удалить свою команду. И соотвественно другие тоже. МОДЕРАТОР - роль, которая имеет ограниченный функционал админа. Может делать всё, кроме удаления (тут будем позже корректировать с заказчиком, к сожалению, он пока сам не может определиться)
3. Модератору доступно вносить изменения во все команды, но не удалять их.
4. Нет. Куратора может поменять админ и возможно модератор (можем пока реализовать, что имеет такую возможность)
5. Как раз нет. Агент должен иметь возможность редактировать состав своей команды, внутренние данные.
6. Да. Необходимо начать проработку этих пермишенов. Я уверен, что вылезет много подводных камней, поэтому разделил таску, чтобы 2 разработчика шли параллельно и могли советоваться..)
