### ISSUE TITLE
На документы добавить валидацию по типу файла и размеру

### ISSUE THREAD

**Issue by KonstantinRaikhert** [Studio-Yandex-Practicum/adaptive_hockey_federation#175]
# Зачем?

В сущности Document сейчас можно загрузить все что угодно. Необходимо ограничить до картинок, таблиц и текстов.

# Как нужно делать?

- сделать кастомный валидатор на тип файла (можно кстати поискать пакет)
- то же самое на размер
- не забыть добавить в helptext информацию об этом

# Где?

**Comment by pandenic** [comment]
Какое ограничение на размер должно быть? 
Я так понял самые большие будут картинки или pdf. Это будут сканы файлов, фотки видимо. Тогда я бы сделал настраиваемый  админом показатель максимального размера одного файла. Либо можно взять средний какой-нибудь. Например, как на госуслугах или в других гос конторах. Мегабайт 15 на файл или типа того.

**Comment by pandenic** [comment]
А загружать файлы можно только при создании игрока получается?

**Comment by pandenic** [comment]
И ещё вопрос: зачем мы делим шаблон создания и редактирования игрока? Можно всё в один объединить, мне кажется.

**Comment by KonstantinRaikhert** [comment]
@pandenic Ты еще с нами?) Просто понять, будешь доделывать или уже нет..)

**Comment by pandenic** [comment]
Дада) я уже почти доделал) прошу прощение за задержку
