### ISSUE TITLE
Некорректное отображение формы создания и изменения сущностей (команды, пользователи и прочее с такой же формой)

### ISSUE THREAD

**Issue by VesselchackU** [Studio-Yandex-Practicum/adaptive_hockey_federation#180]
# Где был обнаружен баг ?

/teams/create/
/teams/{id}/edit/
/users/create/
/users/{id}/edit/

# Скриншоты
![image](https://github.com/Studio-Yandex-Practicum/adaptive_hockey_federation/assets/118609265/bda95a7c-9947-4b4d-96ad-627dbc1bac68)
Везде одинаково: при входе на страницу - отображается половина формы.

![image](https://github.com/Studio-Yandex-Practicum/adaptive_hockey_federation/assets/118609265/d15b83f6-cf62-4811-b52c-5f394e75248a)
Можно сдвинуть полосой прокрутки, но все равно не красиво. 

Браузеры: Хром, Эдж - одинаковое поведение. Другие браузеры не пробовал. 

# Предложения и предположения как исправить

Наверное, что-то в одном из базовых шаблонов надо подправить.

**Comment by KonstantinRaikhert** [comment]
@VesselchackU Это будет править наш фронтендер Илья) Обсуждали с ним это сегодня
