### ISSUE TITLE
Доработка smoke тестов.

### ISSUE THREAD

**Issue by KonstantinRaikhert** [Studio-Yandex-Practicum/adaptive_hockey_federation#182]
# Зачем?

Необходимо проверить доступность всех urls  в проекте. Для этого используются так называемые smoke tests
Необходимо структурировать и дополнить эти тесты. ДУмаю даже вынести в отдельный файл

# Как нужно делать?
Один из важных моментов, лучше использовать правильные инструменты. Чтобы создать например пользователя - необходимо воспользоваться фабриками. У нас на каждую сущность сейчас есть фабрики (factories.py)
Например как я дополнил инициализацию, чтобы тест не падал:
![2024-02-22_23-07](https://github.com/Studio-Yandex-Practicum/adaptive_hockey_federation/assets/69113745/6df459b0-a1ac-413f-842e-055d4e5e7b76)

**командой python manage.py show_urls можно посмотреть все зарегистрированные "ручки"**

# Где?

adaptive_hockey_federation/tests

**Comment by VesselchackU** [comment]
Принял. Приступаю.
