### ISSUE TITLE
Дополнить кастомную миграцию для выдачи необходимых прав по группе 

### ISSUE THREAD

**Issue by KonstantinRaikhert** [Studio-Yandex-Practicum/adaptive_hockey_federation#184]
# Зачем?

Есть миграция, которая создаёт группы, но в ней нет настроенных правильно прав, её нужно дополнить в соответствии с брифом (что каждая роль может)
![2024-02-23_01-21](https://github.com/Studio-Yandex-Practicum/adaptive_hockey_federation/assets/69113745/266c7b8d-c39a-4f0d-9caa-8030aeae190c)

# Как нужно делать?

в миграциях можно прописывать непосредственно по codename. Например для агентов прописается
`<QuerySet [{'id': 62, 'name': 'Can change Игрок', 'content_type_id': 16, 'codename': 'change_player'}]>`

# Где?

adaptive_hockey_federation/users/migrations/0003_setting_group.py

**Comment by pandenic** [comment]
У меня такой вопрос: а зачем нам редактировать именно adaptive_hockey_federation/users/migrations/0003_setting_group.py, если у нас есть для установки пермишеннов специальная функция?

![image](https://github.com/Studio-Yandex-Practicum/adaptive_hockey_federation/assets/114985447/611ee74a-06ea-45dd-8b66-906534e48a65)

**Comment by KonstantinRaikhert** [comment]
> У меня такой вопрос: а зачем нам редактировать именно adaptive_hockey_federation/users/migrations/0003_setting_group.py, если у нас есть для установки пермишеннов специальная функция?
> 
> ![image](https://private-user-images.githubusercontent.com/114985447/307574199-611ee74a-06ea-45dd-8b66-906534e48a65.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDg4NTY1ODgsIm5iZiI6MTcwODg1NjI4OCwicGF0aCI6Ii8xMTQ5ODU0NDcvMzA3NTc0MTk5LTYxMWVlNzRhLTA2ZWEtNDVkZC04YjY2LTkwNjUzNGU0OGE2NS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMjI1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDIyNVQxMDE4MDhaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0wMmFlNWFlZmE2ZDA0YjdlZTFhNTVhY2RmN2ZhZWQ2OGVkM2UwNmYyZDNiMDdhMDE2Yjk3YTRiNWY0ZmEyMzdkJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.OYKYJueOgsYtCH9D8FHHmfdVLXEXuXQAwKmZBBtU0mI)

Действительно.. пропустил этот момент. Значит необходимо более явно как то обозначить. То есть не трогать миграцию, но функцию поместить в скрипт permissions.py. И уже туда положить инфу с констант и саму функцию. 
Ну и собственно добавить в списки MODERATORS_PERMS, AGENTS_PERMS необходимые права.
Или как считаешь? Может есть более удобный вариант?)

**Comment by pandenic** [comment]
Дада, лучше функцию оставить и не трогать миграцию. Константы, наверно, лучше оставить в constants для единообразия. Переместить, в смысле переименовать в permissions?

**Comment by pandenic** [comment]
Хотя в constants только для permissions константы. Можно и перенести, наверно.

**Comment by pandenic** [comment]
Согласно брифу у модератора должна быть возможность менять конкретного игрока:
![Selection_366](https://github.com/Studio-Yandex-Practicum/adaptive_hockey_federation/assets/114985447/ecfbd713-4504-470d-b88d-d0a5d8967e79)

Однако в пермишенах добавляется ещё и возможность редактировать пользователя:
![Selection_367](https://github.com/Studio-Yandex-Practicum/adaptive_hockey_federation/assets/114985447/36591485-b507-48b4-851a-afc8450153d7)

Редактирование команды смотрится уместно, если игрока нужно перекинуть в другую команду, но редактирование пользователя мне кажется это нужно убрать, верно? 

Ещё вопрос по связанным с игроками таблицами типо: Город, Диагноз, Дисциплина, Нозология нужно ли их сделать просматриваемыми хотя бы, а на уровне кода уже запретить редактирование?

Вообще есть ещё проблема с созданием и проверкой user'a потому что приего создании и указании, например, как модератора:
![image](https://github.com/Studio-Yandex-Practicum/adaptive_hockey_federation/assets/114985447/d11f3eae-0da7-4fc5-a569-d5f73120841a)

Он не попадает в группу "Модераторы":
![image](https://github.com/Studio-Yandex-Practicum/adaptive_hockey_federation/assets/114985447/8b876450-8c0b-4597-89c0-e261ecabd000)

Это я думаю, что смогу поправить.

Но проверку корректности выбора самих пермишенов, в плане какие пермишенны что в итоге запрещают, сейчас, вероятно, провести не получится. 

Подскажи тогда в каких границах тогда эта задача будет? что нужно сделать, кроме переименования в permissions и переноса констант?

**Comment by VesselchackU** [comment]
Можно свои 5 копеек вставить? 
У нас тут просто получается, что то ли два, то ли три разраба одновременно делают механизм зачисления пользовтеля в группу в зависимости от роли. Денис, я, на всякий случай уведомляю, он на данный момент уже реализован в ветке dev. 
А с пермишенами (просто они пересекались у меня с двумя тасками и с тестами в том числе) - надо просто определиться, какие у кого (особенно с модератором - по брифу у него самые странные полномочия), и забить их в константы, которые уже тоже существуют.

**Comment by pandenic** [comment]
Окей, понял. Посмотрю
