### ISSUE TITLE
Реализация добавления игроков, тренеров и других их карточки состава команды

### ISSUE THREAD

**Issue by KonstantinRaikhert** [Studio-Yandex-Practicum/adaptive_hockey_federation#185]
# Зачем?

В макете есть вот такое, логичный функционал, которых необходимо добавить
![2024-02-23_01-29](https://github.com/Studio-Yandex-Practicum/adaptive_hockey_federation/assets/69113745/cf946176-3143-4b65-be74-d6e57c1b66cc)

# Как нужно делать?

Сделать формы, где уже будет текущая команда. Возможности изменять её нет.
По возможности использовать существующие ендпоинты
Так же необходимо реализовать CRUD для Staffmember

# Где?

main

**Comment by AntAresWeb** [comment]
Привет, Константин!
Понял задачу так:
На страничке профиля конкретной команды при нажатии кнопки (на футере) "Добавить" вызывать создание профиля нового игрока. И, при записи нового игрока в базу привязать его к команде и роль в команде (игрок или тренер).
То есть делается фича для удобства заполнения состава команды членами, которых ещё нет в базе?

**Comment by KonstantinRaikhert** [comment]
> Привет, Константин! Понял задачу так: На страничке профиля конкретной команды при нажатии кнопки (на футере) "Добавить" вызывать создание профиля нового игрока. И, при записи нового игрока в базу привязать его к команде и роль в команде (игрок или тренер). То есть делается фича для удобства заполнения состава команды членами, которых ещё нет в базе?

Да, создание необходимых представлений для этого

**Comment by AntAresWeb** [comment]
Константин, привет!
Разобрался как обрабатывать кнопку Добавить, чтобы вызвать нужное представление. Стал рефакторить представление PlayerIDCreateView и внезапно осознал, что нужно делать отдельный модуль (представление, шаблон, форма) для создания тренеров и других. Так как они инфологически не вписываются в сущности игрока. Делать?

**Comment by KonstantinRaikhert** [comment]
> Константин, привет! Разобрался как обрабатывать кнопку Добавить, чтобы вызвать нужное представление. Стал рефакторить представление PlayerIDCreateView и внезапно осознал, что нужно делать отдельный модуль (представление, шаблон, форма) для создания тренеров и других. Так как они инфологически не вписываются в сущности игрока. Делать?

Да, тренера и пушер-тьюторы это другие сущности и необходимо сделать для них новые представления и урлы. Извини, что долго ждал ответа. Действительно не видел комментарий

**Comment by AntAresWeb** [comment]
Создавать ишью для реализации CRUD представителей команды (тренеры и пушер-тьютеры)? Или без этого взяться за работу?
Кстати, добавление игорка в команду я сделал. Спушил свою ветку, но PR не запускал.
