### ISSUE TITLE
Роли пользователя и группы

### ISSUE THREAD

**Issue by VesselchackU** [Studio-Yandex-Practicum/adaptive_hockey_federation#195]
# Зачем?

У нас есть группы - администраторы, модераторы, агенты. По замыслу у них - разные права. Это удобно. 
Также у нас у пользователя есть поле role, которое тоже может принимать одно из значений:
![image](https://github.com/Studio-Yandex-Practicum/adaptive_hockey_federation/assets/118609265/7bdc26dc-bac2-4f6f-865d-6c7bb288b971)
Однако, между группами и ролью пользователя нет в настоящее время никакой связи. При создании пользователя ему определяются только роли. При этом на объем прав влияет только назначение пользователя суперпользователем. То есть при присвоении пользователю роли, например, агент или модератор, никаких пермишенов, свойственных этим группам, у пользователя не появляется. А значит, возможна ситуация, когда, несмотря на громкую роль, у пользователя нет никаких прав  ни на просмотр команд, ни на добавление игроков и т.д. 
Больше того, не до конца ясно, позволяет ли концепция нашего приложения пользователю быть членом одновременно двух групп... Если да, то тогда не вижу смысла в ролях. Если нет, то, ПМСМ, нет особого смыла в группах...
Кроме того, по настоящее время нет точной определенности с тем, у какой группы какие должны быть разрешения. 

# Как нужно делать?

1. В модели пользователя сделать отдельный метод, например, set_role, который будет присваивать роль и добавлять пользователя в соответствующую группу. 
2. В метод clean() (или в какой-то другой, вызываемый автоматом перед сохранением в БД - не разбирался еще в этом), в зависимости от назначенной роли добавлялся в соответствующую группу.
3. Подумать, точно ли могут п.1 и п.2 быть вместе и не будут ли мешать друг другу.
4. Четко определиться с разрешениями для каждой группы и внести их в админку и БД

# Где?

1-3 users/models
4 users/utils

**Comment by KonstantinRaikhert** [comment]
@VesselchackU Мне кажется лучше тебе отдать)
А по логике работы я согласен. Со стороны юзеры это должно выглядеть как просто выбор роли при добавлении или изменении пользователя.
На бэке уже все необходимые привязки к группе.

По твоим пунктам:
1. не обязательно отдельный метод, а просто использовать save
2. Тут нужно почитать документацию, там есть несколько методов у модели, вроде все они атомарны в транзакции. Но лучше уточнить
3. Думаю не должно возникнуть конфликтов
4. Занимается этим Денис. После фидбэка от заказчика дополним
