### ISSUE TITLE
После проработки пермишенов раскоментить тесты на urls, отрефакторить тесты

### ISSUE THREAD

**Issue by KonstantinRaikhert** [Studio-Yandex-Practicum/adaptive_hockey_federation#197]
# Зачем?

Сейчас присутствует некоторая каша в тестах. Поэтому хочется немного отрефакторить.
Выделить отдельным файлом smoke tests.
Другими файлами CRUD на каждую сущность. Можно в этом же файле пермишены

# Как нужно делать?

- Основая задача в рамках этого тикета вычленить смоки тесты, добавить новые. Вроде как увеличилось количество доступных ендпоинтов.

- Вторая задача, получив все ендпоинты, проверить, где какие пермишены нам следует поправить

# Где?

adaptive_hockey_federation/tests

**Comment by KonstantinRaikhert** [comment]
@VesselchackU Показалось, что сейчас важны тесты стали.

**Comment by VesselchackU** [comment]
Ок. Принял. Можно мне тогда чуть больше подробностей? 

1. Какие тесты в этом проекте мы считаем smoke. 
1.1 Доступность энд-поинта для суперюзера?
1.2 Тогда тесты урлов с пермишенами - это уже за рамками smoke-тестов?

2. Что понимается под CRUD-тестами?
2.1. Только правильное принудительное создание/изменение/удаление моделей в БД?
2.2. Тесты валидации полей?
2.3. Или работа форм сюда тоже входит?

3. Мне кажется, я видел таску по CRUD-тестам. Мы не будем пересекаться?

**Comment by KonstantinRaikhert** [comment]
> Ок. Принял. Можно мне тогда чуть больше подробностей?
> 
> 1. Какие тесты в этом проекте мы считаем smoke.
>    1.1 Доступность энд-поинта для суперюзера?
>    1.2 Тогда тесты урлов с пермишенами - это уже за рамками smoke-тестов?
> 2. Что понимается под CRUD-тестами?
>    2.1. Только правильное принудительное создание/изменение/удаление моделей в БД?
>    2.2. Тесты валидации полей?
>    2.3. Или работа форм сюда тоже входит?
> 3. Мне кажется, я видел таску по CRUD-тестам. Мы не будем пересекаться?

Основная идея немного их разграничить. Смоки тесты действительно можно сделать для суперюзера.
Вообще по этому пооводу можно созвониться и обсудить, что скажешь?
