### ISSUE TITLE
Сделать различные формы для реадктирования пользователя в зависимости от роли

### ISSUE THREAD

**Issue by KonstantinRaikhert** [Studio-Yandex-Practicum/adaptive_hockey_federation#199]
# Зачем?

У агента (представителя команды) необходимо реализовать добавление команд (можно несколько) для курирования. А модераторам и админам такая возможность не нужна.

# Как нужно делать?

Предполагаю, что необходимо сделать разные формы и выдавать в зависимости от роли.

# Где?

adaptive_hockey_federation/users/forms.py

**Comment by pandenic** [comment]
Ещё в текущей форме при редактировании пользователя не хватает обратной связи о том какое поле задано с ошибкой.

**Comment by pandenic** [comment]
Так же при обновлении данных пользователя отсутствует обратная связь, если пользователь допустил ошибку. То есть, если ошибка, страница просто сбрасывается на форму с данными пользователя и ничего не сообщает.

**Comment by KonstantinRaikhert** [comment]
@xxfeel Есть тут продвижения? Насколько ваще реально?...)
