### ISSUE TITLE
Неинформативные сведения о пользователях в оснастке "группы" в админке

### ISSUE THREAD

**Issue by VesselchackU** [Studio-Yandex-Practicum/adaptive_hockey_federation#201]
# Где был обнаружен баг ?

Админка:
В оснастке "группы" пользователи отображаются в виде емайлов. 
Мне кажется, это вообще не удобно и гораздо красивше будет, если там будут ФИО либо ФИО с емайлом.

# Скриншоты

![image](https://github.com/Studio-Yandex-Practicum/adaptive_hockey_federation/assets/118609265/94d20e90-14cf-4044-8ada-0cc12f4e275b)

# Предложения и предположения как исправить

Переделать настройки админки.

**Comment by VesselchackU** [comment]
Так, ну я вижу тут два варианта: 
1. Простой и дико эффективный: переделать `__str__()` в модели User. Сейчас он выдает урезанный до 15 символов е-майл. Такой же урезанный вариант идет в рассылку при регистрации, кстати. Я бы предложил переделать на Фамилию + Инициалы, либо на полные ФИО либо ФИО + email. Кроме, как в админке да в рассылке объект пользователя больше, вроде, нигде для отображения не используется - везде по отдельным полям. 
2. Переопределять форму и виджет в админке группы. Черевато сложностями и багами. Но могу покопаться, если это надо. 

Я бы вообще сразу пошел по первому варианту, но я подумал, что чем-то же руководствовались, когда именно таким образом `__str__() ` в юзере делали...

**Comment by KonstantinRaikhert** [comment]
> Так, ну я вижу тут два варианта:
> 
> 1. Простой и дико эффективный: переделать `__str__()` в модели User. Сейчас он выдает урезанный до 15 символов е-майл. Такой же урезанный вариант идет в рассылку при регистрации, кстати. Я бы предложил переделать на Фамилию + Инициалы, либо на полные ФИО либо ФИО + email. Кроме, как в админке да в рассылке объект пользователя больше, вроде, нигде для отображения не используется - везде по отдельным полям.
> 2. Переопределять форму и виджет в админке группы. Черевато сложностями и багами. Но могу покопаться, если это надо.
> 
> Я бы вообще сразу пошел по первому варианту, но я подумал, что чем-то же руководствовались, когда именно таким образом `__str__() ` в юзере делали...

Я думаю первый вариант адекватный. И мне кажется, будет удобнее фамилия и инициалы. В той же самой админке будет лучше смотреться
