### ISSUE TITLE
Сделать гиперссылки из блока команды на участников и из игроков на команду (для реадктирования)

### ISSUE THREAD

**Issue by KonstantinRaikhert** [Studio-Yandex-Practicum/adaptive_hockey_federation#203]
# Зачем?

Заказчик подметил, что ему будет это удобнее. Иметь возможность перехода по ссылкам из других блоков
![2024-02-29_19-45](https://github.com/Studio-Yandex-Practicum/adaptive_hockey_federation/assets/69113745/f06bb69d-4581-4688-9684-40dbe89b9c79)
![2024-02-29_19-46](https://github.com/Studio-Yandex-Practicum/adaptive_hockey_federation/assets/69113745/2e01f150-3636-4c30-aa15-311face47bca)

# Как нужно делать?

- подредактировать необходимые шаблоны, добавив путь к url
- еще сразу тут нужно будет изменить STAFF_POSITION_CHOICES с "Другой" на "Пушер - тьютор"
- так же думаю нужно убрать должность с таблиц (неактуально)

**Comment by VesselchackU** [comment]
Я уже сделал из расчета, что в нескольких))).
Теперь второй вопросик: что означает "(для редактирования)" в названии таски? Надо ссылку сделать на форму редактирования команды??

**Comment by VesselchackU** [comment]
А имя и фамилию игрока в карточке команды обязательно в разных столбцах таблицы показывать? Сортировка-то все равно по фамилии идет. Может, объединить их в один столбец. Красивше же будет, чем когда фамилия синяя (это я про гиперссылку), а имя черное.

**Comment by KonstantinRaikhert** [comment]
> Вопросик: У нас один и тот же игрок может быть в нескольких командах?
> 
> ![Image](https://private-user-images.githubusercontent.com/118609265/309190845-ac35c5b7-fbbf-4800-9d79-fe0d75a80141.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDkyODkxNTIsIm5iZiI6MTcwOTI4ODg1MiwicGF0aCI6Ii8xMTg2MDkyNjUvMzA5MTkwODQ1LWFjMzVjNWI3LWZiYmYtNDgwMC05ZDc5LWZlMGQ3NWE4MDE0MS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzAxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMwMVQxMDI3MzJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT02YjE1MDhiNjUyMjg0MGY5ZjkzZGZkOTJmMTAyMGJlZjExOWNkYTUyMDAxYzk5YTAxNzE4OTllNzZiMTY0ZGYwJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.nY7uPhhi27Ve_3Dci5tis3KBGbjR53xaXcmIYUesIXk)
> 
> ![Image](https://private-user-images.githubusercontent.com/118609265/309191136-6df5aae6-7fa2-41b5-ae2b-a9d257e3825e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDkyODkxNTIsIm5iZiI6MTcwOTI4ODg1MiwicGF0aCI6Ii8xMTg2MDkyNjUvMzA5MTkxMTM2LTZkZjVhYWU2LTdmYTItNDFiNS1hZTJiLWE5ZDI1N2UzODI1ZS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzAxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMwMVQxMDI3MzJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT02ZjMwZmIzZWVmMzk2NzE2MmQwNzBhZGQwMDBkMzg1NGRkZjAyNzZmMWUyMjI1NGY0NDU5MTBmNmY2YTQ3NDQ0JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.RWJcNCOQbrkHTdjoFocFhoR65uuE48VDJQpbDufbGos)
> 
> Второй скрин - из вьюхи просмотра карточки игрока.

Я задавал такой вопрос заказчику, сказал, что в принципе такое возможно

**Comment by KonstantinRaikhert** [comment]
> Я уже сделал из расчета, что в нескольких))). Теперь второй вопросик: что означает "(для редактирования)" в названии таски? Надо ссылку сделать на форму редактирования команды?? Мне кажется, что это не очень логично. А на карточку команды со списком игроков - самое то))

Не не. Как раз имелось ввиду на карточку команды (для редактирования - иметь возможность переключиться на быстрое редактирование с карточки)

**Comment by KonstantinRaikhert** [comment]
> А имя и фамилию игрока в карточке команды обязательно в разных столбцах таблицы показывать? Сортировка-то все равно по фамилии идет. Может, объединить их в один столбец. Красивше же будет, чем когда фамилия синяя (это я про гиперссылку), а имя черное.

Да, можно реализовать отображение такое. Поиск и так должен работать)
