### ISSUE TITLE
Некорректный зоновый код пользователя: проблема с фалидацией, либо с фабрикой тестовых данных

### ISSUE THREAD

**Issue by pandenic** [Studio-Yandex-Practicum/adaptive_hockey_federation#205]
# Где был обнаружен баг ?

Фабрика тестовых данных генерирует невалидные номера телефонов, т.е. с несуществующими кодами стран. 
ЛИБО
Некорректно настроена валидация номера пользователя при регистрации / обновлении пользователя.

Поэтому когда хочешь во вкладке "пользователи" изменить любые данные пользователя - ничего сохранить не получится.

# Скриншоты

![Selection_373](https://github.com/Studio-Yandex-Practicum/adaptive_hockey_federation/assets/114985447/66d9ae8e-64da-4eee-9680-bb5dbe051570)

# Предложения и предположения как исправить

Фабрика генерирует некорректные данные и загружает их в бд. Предполагаю, что валидация работает на уровне приложения, а фабрика пишет напрямую в бд. 
Можно настроить проверку на уровне фабрики или вплидировать все данные через приложение.

ЛИБО

Если проблема в валидаторе, то написать кастромный валидатор для этого поля.
adaptive_hockey_federation/users/models.py

**Comment by KonstantinRaikhert** [comment]
@VeraUrsul для справки, у нас есть в проекте PhoneNumber. Так, на всякий случай)

**Comment by VeraUrsul** [comment]
> [@VeraUrsul](https://github.com/VeraUrsul) для справки, у нас есть в проекте PhoneNumber. Так, на всякий случай)

Спасибо)
