### ISSUE TITLE
Изменить цвет текста сообщений при валидации вводимых значений

### ISSUE THREAD

**Issue by AntAresWeb** [Studio-Yandex-Practicum/adaptive_hockey_federation#207]
# Зачем?

![изображение](https://github.com/Studio-Yandex-Practicum/adaptive_hockey_federation/assets/80886928/d6d88e21-e397-4319-b358-4d80d0c6ea87)

Для того, чтобы пользователь сразу увидел где он допустил ошибку при вводе информации в валидируемом поле формы ввода информации (создание нового или редактирование существующего объекта) необходимо сообщение об ошибке выделять другим цветом, например, красным.  

# Как нужно делать?

Провести рефакторинг во всех шаблонах (templates) ввода нового или редактирования существующего объекта.

# Где?

/adaptive_hockey_federation/templates

**Comment by KonstantinRaikhert** [comment]
Проводится рефакторинг шаблонов. Таска неактуально. Будет присутствовать в новых стилях
