### ISSUE TITLE
Не работает ссылка установки и сброса пароля для пользователя

### ISSUE THREAD

**Issue by KonstantinRaikhert** [Studio-Yandex-Practicum/adaptive_hockey_federation#208]
# Где был обнаружен баг ?

После пулреквесте #202 поломалась генерация ссылки

# Скриншоты

![Снимок экрана от 2024-03-02 09-29-09](https://github.com/Studio-Yandex-Practicum/adaptive_hockey_federation/assets/69113745/7902c6f9-050e-491d-9ecf-98a57d2dcf37)

# Предложения и предположения как исправить

удалили эту строку, в файле users.forms, форма для создания пользователя:
set_permission_create_user(self.cleaned_data["role"], user)

Необходимо тщательно проверить и протестировать. Возможно, что-то еще пропало

**Comment by VesselchackU** [comment]
Ребят, привет. 
Как авторо ПР поясняю: 
строка `set_permission_create_user(self.cleaned_data["role"], user)` была удалена в связи с тем, что был удален сам метод, на который данная строка ссылается. Назначение групп происходит в самой модели юзера, в методе save (это обсуждалось). А в форме создания пользователей в файле `users.forms` надо в методе save() в строке `user = super(UsersCreationForm, self).save()` убрать `commit=False`. Мой косяк, недоглядел. Но уже исправил. Если дадите отмашку, могу сделать ПР. Протестировано. Пользователи создаются и изменяются. Письмо на почту приходит.
