### ISSUE TITLE
Ввести главную страницу и реализовать ТОЛЬКО поиск на ней

### ISSUE THREAD

**Issue by KonstantinRaikhert** [Studio-Yandex-Practicum/adaptive_hockey_federation#227]
# Зачем?

Главную страницу мы делаем по факту для модератора. По брифу - модератор имеет право только менять данные игрока и находит его только по поиску.

![2024-03-08_17-06](https://github.com/Studio-Yandex-Practicum/adaptive_hockey_federation/assets/69113745/36a4b302-5e79-43f4-bcef-7f01a1f8c5a3)

# Как нужно делать?
- на данном ендпоинте реализовать вьюху только с поиском. queryset только от поисковой строки
- в шаблоне необходимо поправить, на главной странице поиск только по игрокам

# Где?

adaptive_hockey_federation/main

**Comment by DoomHunter190** [comment]
Хотел бы уточнить, на main странице нехообходимо сделать поиск , только по фамилии, имени? 

![Image](https://github.com/Studio-Yandex-Practicum/adaptive_hockey_federation/assets/124585181/a4b6cf85-4734-4e98-a793-7eda855f1db7)

**Comment by KonstantinRaikhert** [comment]
> Хотел бы уточнить, на main странице нехообходимо реализовать поиск, только по фамилии, имени?
> 
> ![Image](https://private-user-images.githubusercontent.com/124585181/311633710-a4b6cf85-4734-4e98-a793-7eda855f1db7.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTAxNDYxMTYsIm5iZiI6MTcxMDE0NTgxNiwicGF0aCI6Ii8xMjQ1ODUxODEvMzExNjMzNzEwLWE0YjZjZjg1LTQ3MzQtNGU5OC1hNzkzLTdlZGE4NTVmMWRiNy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzExJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMxMVQwODMwMTZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0xNjViNjk1Y2Q3YjdlMzM0NDJmYmEzMTNjZTgwOTllYTE3OWFlMzBjNGI1OGExNTE5NTM4NmQ0M2YwNGY4OTJjJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.3WElPkp5_y1SGfBQuU1wj4jEVTrCf3OeYspgTQxMzfU)

Да, сейчас реализуем только такой функционал, т.к. при других фильтрах может выйти большая выборка. А по боифу заказчика это не нужно

**Comment by KonstantinRaikhert** [comment]
> ![image](https://private-user-images.githubusercontent.com/124585181/312000696-eac93962-9b00-4a3e-8001-a1c784956db7.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTAyNTkwMjcsIm5iZiI6MTcxMDI1ODcyNywicGF0aCI6Ii8xMjQ1ODUxODEvMzEyMDAwNjk2LWVhYzkzOTYyLTliMDAtNGEzZS04MDAxLWExYzc4NDk1NmRiNy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzEyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMxMlQxNTUyMDdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1lNGNiYmE1ZTQxMDE4MjMzZjYzYWQ0ZTQ5OWYzNjYzNzBiZmYyODUzMDJhNTE2MGI0MWFkNWEwMGIyN2ZjMzIyJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.piZpQsAP9Z9B1OvyjHFxgpwN9wBoWiPWj1t-VvTxjPY) Реализовал поиск, но есть вопросы: У меня получается дубляж раздела "Игроки". 1) Нужно ли оставлять кнопки редактирование игроков ? 2) По поводу выбора типа поиска, может лучше оставить только "все", чтобы он сразу искал и по фамилии и имени. Пример запроса: ![image](https://private-user-images.githubusercontent.com/124585181/312002012-2bd3c602-fce2-4bf4-9c20-cf57f2a01b83.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTAyNTkwMjcsIm5iZiI6MTcxMDI1ODcyNywicGF0aCI6Ii8xMjQ1ODUxODEvMzEyMDAyMDEyLTJiZDNjNjAyLWZjZTItNGJmNC05YzIwLWNmNTdmMmEwMWI4My5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzEyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMxMlQxNTUyMDdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1lZjBkNWFiYTdkNWZiNDMzNDBiYTg3OTNjYTliMjM5YTZjMzYxNjA0ZmYwMDJhYzhmNzFiNWVlYzU1OGY4NWQzJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.OVjXfDqWBI4xPAA_mviEy3z1i7XyKqt9hVUVLzbfP7M) Может еще что-то нужно убрать из выборки ?

Давай выпадающее меню просто уберём и чтобы в строке поиска было просто написано "Игрок", либо "Поиск по игрокам"
Что касается кнопок редактирования в листе, то лучше их убрать. А уже непосредственно в карточке игрока есть необходимые кнопки.
Эта страница по факту создаётся для модераторов. Позже будем настраивать доступ
