### ISSUE TITLE
У админа не отображается кнопка на создание суперпользователя

### ISSUE THREAD

**Issue by KonstantinRaikhert** [Studio-Yandex-Practicum/adaptive_hockey_federation#233]
# Где был обнаружен баг ?

Нужно настроить права на создание пользователей для администратора

# Скриншоты

![2024-03-10_18-41](https://github.com/Studio-Yandex-Practicum/adaptive_hockey_federation/assets/69113745/aa5b3576-ddf2-4175-a9f7-cc66251925c0)

# Предложения и предположения как исправить

*Возможные догадки, как исправить.*

**Comment by VeraUrsul** [comment]
Прошу уточнение

![Image](https://github.com/Studio-Yandex-Practicum/adaptive_hockey_federation/assets/122533248/fd19ab13-20b5-420f-83c4-9bf42fc80e67)
На месте красного прямоугольника находится кнопка "Создать пользователя", где необходимо разместить кнопку для создания суперпользователя?
Кнопка "Создать пользователя" действует: пользователь создается.

**Comment by KonstantinRaikhert** [comment]
@VeraUrsul Извиняюсь, похоже поправили в другом ПР. Закрою ишью и новую таску закреплю
