### ISSUE TITLE
Представителям команды и модераторам показывать дополнительную информацию на главном экране

### ISSUE THREAD

**Issue by VesselchackU** [Studio-Yandex-Practicum/adaptive_hockey_federation#242]
# Зачем?

Модераторы могут просмотреть отдельного игрока, но им неоткуда взять ссылку на него, так как доступ к спискам игроков для них закрыт. То же самое касается представителей команды: им неоткуда взять ссылку на свою команду. Кроме того, сразу после логина идет редирект на список игроков. Пока ты - суперюзер, всё ок. Но у представителя и модератора - сразу 403. 

# Как нужно делать?

Мне кажется, на главном экране, как минимум, представителю команды, надо показывать ссылку на свою команду (команды), а модераторам - ну тоже что-нибудь, на что они имеют право посмотреть и нажать, чтобы перейти к реализации своих полномочий.

# Где?

Мне кажется, где-то в main.views надо это реализовывать, а точнее - проработкой контекста пересылаемого при рендере в `def main()` в зависимости от роли пользователя. Либо разделить это представление на два - для представителей и для модераторов, может, даже с отдельными урл.

**Comment by KonstantinRaikhert** [comment]
@VesselchackU Это решается сейчас предварительной таской создания поиска на главной #227 
Я думаю это ишью можно чуть отредактировать)

**Comment by KonstantinRaikhert** [comment]
@VesselchackU Это решим после некоторого наведения порядка в пермишенах с модераторами

**Comment by KonstantinRaikhert** [comment]
Сейчас это решается в ПР #274
Это ишью тогда закроем)
