### ISSUE TITLE
Внедрить в наши формы для редактирования Players новый стили

### ISSUE THREAD

**Issue by KonstantinRaikhert** [Studio-Yandex-Practicum/adaptive_hockey_federation#243]
# Зачем?

Сделали более красивые стили для формы, сейчас их необходимо внедрить в наши шаблоны, взять с примера с шаблона **player_id_edit.html**
![2024-03-13_15-07](https://github.com/Studio-Yandex-Practicum/adaptive_hockey_federation/assets/69113745/0971e9d4-6b38-4206-a776-5a47e8361bfb)
![2024-03-13_15-07_1](https://github.com/Studio-Yandex-Practicum/adaptive_hockey_federation/assets/69113745/c0527eb3-3c30-4f9b-b2bd-35a9662e47b3)

# Как нужно делать?

- сделать замены в шаблоне.
- возможно потребуется переопределение виджетов в форме уже в джанге
- так же прошу попробовать реализовать отображение поля ошибок только в том случае, когда они возникаю
- 
![2024-03-13_15-08](https://github.com/Studio-Yandex-Practicum/adaptive_hockey_federation/assets/69113745/a31bb2bd-d05a-4d79-81ea-a1fdc00bb58c)

# Где?

adaptive_hockey_federation/templates/main/player_id/player_id_edit.html
adaptive_hockey_federation/main/forms.py

**Comment by KonstantinRaikhert** [comment]
@Aleksey-Krd Я думаю у тебя получится) Ну если согласен

**Comment by KonstantinRaikhert** [comment]
@xxfeel После миграций можно будет тебя попросить заново накатить миграции на стейдже и БД заполнить?)

**Comment by xxfeel** [comment]
> @xxfeel После миграций можно будет тебя попросить заново накатить миграции на стейдже и БД заполнить?)

Да, не вопрос), сделаю))

**Comment by Aleksey-Krd** [comment]
@KonstantinRaikhert вопросики есть,какая информация должна быть в области под названием редактирование профиля игрока что на скриншоте, ну и вот такой вариант полей подойдёт? красным поле будет в случае ошибки и под ним наименование ошибки, стиль можно хоть какой забабахать) вариант оформления мне нужен, что ты хочешь видеть

![Image](https://github.com/Studio-Yandex-Practicum/adaptive_hockey_federation/assets/118228004/edb3a7ff-143c-40e6-a8f5-5d86c0c55243)



![Image](https://github.com/Studio-Yandex-Practicum/adaptive_hockey_federation/assets/118228004/ac0efba0-8d63-46bd-845f-8c61e0c85704)



![Image](https://github.com/Studio-Yandex-Practicum/adaptive_hockey_federation/assets/118228004/6d390687-001c-4c3d-914f-34892c94c8dd)

**Comment by Aleksey-Krd** [comment]
@KonstantinRaikhert или это образец? что на первом скрине?)) только сейчас допёр, так и должны выглядеть поля?)))
