### ISSUE TITLE
Поресерчить на тему пермишенов, изучение стандартных методов джанги для наших целей.

### ISSUE THREAD

**Issue by KonstantinRaikhert** [Studio-Yandex-Practicum/adaptive_hockey_federation#244]
# Зачем?

Есть сейчас проблема в представителях команд. По брифу представитель команды имеет возможность редактировать свою команду и игроков. Необходимо понять, можем ли мы расширить стандартные пермишены джанги для этой реализации

P.S. Не очень сейчас хочется переходить на сторонние расширения, возможно их нам будет труднее ввести в проект.

# Что нужно сделать.

Реализовать в пермишенах доступ к смоей команде на url (и только к своим игрокам).

**Comment by KonstantinRaikhert** [comment]
@VesselchackU Есть желание покопаться?)

**Comment by VesselchackU** [comment]
Да, конечно. Копну в этом направлении.

**Comment by VesselchackU** [comment]
Рассуждения вслух: навскидку простейшим решением вижу передачу дополнительного контекста во вьюху списка команд и списка игроков, и в зависимости от пользователя показывать или не показывать ему ссылки на игроков и команды. То есть на своих игроков - ссылки, а на остальных - гольный текст. Но это не решает проблему доступа к конкретному игроку через, к примеру, адресную строку. Значит, надо и во вьюхах id игрока и команды тоже проверять, кто хочет посмотреть, и райзить пермишн денайед. Но я сначала посмотрю, мож действительно какой-то гламурный способ через расширения именно пермишенов есть... 
Тут еще одна проблемка, правда есть, которую я как раз недавно подсветил: 
https://github.com/Studio-Yandex-Practicum/adaptive_hockey_federation/issues/242

**Comment by VesselchackU** [comment]
Итак. Вот, к чему привел мой ресёрч. 

Есть один вариант, на который меня навел ГигаЧат - это использовать декоратор user_passes_test
```
from django.contrib.auth.decorators import user_passes_test
from django.http import Http404
from django.shortcuts import get_object_or_404

def has_object_permission(user, obj):
    # Ваш код для проверки, имеет ли пользователь доступ к объекту
    return True

class ViewClass(View):
    **@user_passes_test**(has_object_permission, raise_exception=True)
    def get(self, request, pk):
        obj = get_object_or_404(YourModel, pk=pk)
        # Ваш код для обработки запроса
```


![Image](https://github.com/Studio-Yandex-Practicum/adaptive_hockey_federation/assets/118609265/6e59ca14-2ed5-4c3a-ad85-7b89b3443d31)

Оф. документация джанги подтверждает эти выводы гпт))).

Как говорится, простенько и со вкусом, не выходим за чистый джанго; да, придется немножно подработать ряд вьюх, но, на первый взгляд выглядит решаемо. 

Есть второй вариант. Формально он тоже не выходит за рамки чистой джанги, но, как мне кажется, сильно усложнит код, хотя, может, и облегчит жизнь в будущем. Ссылка со стэковерфлоу: 
https://code.djangoproject.com/wiki/RowLevelPermissionsDeveloper

Всё остальное - из серии мидлварей.

Если выбирать из двух вышеописанных, то, как по мне, так кажется проще первый вариант. Но, это, конечно, не чистые пермишены.

**Comment by KonstantinRaikhert** [comment]
@VesselchackU Первый вариант действительно интересный, смущало, что в названии test, но почитав доку, понял)
Давай попробуем реализовать данный функционал для игроков? Посмотрим, насколько это будет адекватно.
Если все ок, тогда переведем ПР в рабочий и будем внедрять

**Comment by VesselchackU** [comment]
М-дя... Вторая ссылка - это всё-таки какая-то миддлварь. Причем не очень мне понятная. 

На просторах интернет-поиска большинство рекомендуют для этих целей django-guardian. Я почитал документацию краем глаза. В принципе, не такой сложный, но это полноценный auth-backend со всеми вытекающими: правка settings.py и проч. Не исключено, для при его настройке для уже начатого проекта придется попотеть.... В том числе из-за кастомной модели пользователя (но это, согласно документации, вроде бы решаемо). А так, в принципе, не слишком сильно отличается от джанговских - так же через декораторы `@permission_required` можно работать, только они там с доп.параметрами, и всё. 

https://django-guardian.readthedocs.io/en/stable/index.html

**Comment by VesselchackU** [comment]
Ну и вот мое мнение:

Мидлвари в этом вопросе целесообразны в случаях, когда:
- планируется, что юзеру будут даваться разрешения на несколько разных видов объектов (для унификации)
- между юзером и объектом в БД отсутствует явная связь (мидлварь как раз такую пообъектную связь и формирует)

Но у нас, если вопрос только в представителях - командах - игроках, то эта связь уже есть через FK и M2M. Поэтому, мне кажется, проще сделать стандартными джанговскими средствами. Гипотетически, можно даже свой декоратор конкретно под команды и игроков написать, чтоб красивенько было и задекорировать либо вьюху, либо методы get и post. 

В какую сторону идём?

**Comment by KonstantinRaikhert** [comment]
> Ну и вот мое мнение:
> 
> Мидлвари в этом вопросе целесообразны в случаях, когда:
> 
> * планируется, что юзеру будут даваться разрешения на несколько разных видов объектов (для унификации)
> * между юзером и объектом в БД отсутствует явная связь (мидлварь как раз такую пообъектную связь и формирует)
> 
> Но у нас, если вопрос только в представителях - командах - игроках, то эта связь уже есть через FK и M2M. Поэтому, мне кажется, проще сделать стандартными джанговскими средствами. Гипотетически, можно даже свой декоратор конкретно под команды и игроков написать, чтоб красивенько было и задекорировать либо вьюху, либо методы get и post. Ну да, это не будет пермишеном в чистом виде, и в админке не увидишь и принудительно не назначишь, но функцию свою делать будет - для представителя будут доступны к просмотру и редактированию только его команда (команды), к которым он привязан, и игроки соответствующих команд (я ж правильно понимаю, что **создание** игрока представителю недоступно?).
> 
> Либо давай django-guardian прикручивать.
> 
> В какую сторону идём?

Да, на данном этапе нам нужна реализация с наименьшими потерями. Декоратор мне всё же нравится больше. Учитывая, что сервис для внутренного пользования, можно всё же допустить реализацию попроще, главное не давать юзеру слишком много свободы.
Итого:
давай попробуем реализацию без midlleware при помощи функции обработчика своей.
Кстати еще один нюанс по поводу guardian, последнее обновление было 3 года назад, значит обновления нет и с новыми версиями Django могут появиться проблемы. 
Либо возможно, если плохо будет получаться со своей реализацией, поищем другие пакеты.

**Comment by VesselchackU** [comment]
Ок. Принял, начинаю.

**Comment by VesselchackU** [comment]
Ну и еще в догонку))). По-хорошему бы, конечно, вот этот ПР смержить, если он готов. https://github.com/Studio-Yandex-Practicum/adaptive_hockey_federation/pull/219. Там по игрокам прям глубокие изменения.

**Comment by KonstantinRaikhert** [comment]
> @KonstantinRaikhert , так и еще вопрос остался. По поводу этого: #242 Будем возвращать представителю возможность смотреть списки команд и игроков? Или пока для проверки функционала просто пермишен временно закоментить во вьюхе списков?

Для проверки можно закомментить. По поводу #219 есть там недолги, выясним, сможем ли мы сегодня его смержить
