### ISSUE TITLE
Написать тесты на CRUD игрока. 

### ISSUE THREAD

**Issue by KonstantinRaikhert** [Studio-Yandex-Practicum/adaptive_hockey_federation#255]
# Зачем?

Пора покрывать проект тестами.
Тесты на CRUD игрока. ОБЯЗАТЕЛЬНО сделать TODO пометку пермишенов. Как будут польностью реализованы, поправим тесты

# Как нужно делать?

- обязательно используем фабрики в качестве тестовых данных

# Где?

adaptive_hockey_federation/tests

**Comment by ViacheslavMelnikov** [comment]
Начинаю работу над новой задачей.
