### ISSUE TITLE
Написать тесты на CRUD команды.

### ISSUE THREAD

**Issue by KonstantinRaikhert** [Studio-Yandex-Practicum/adaptive_hockey_federation#256]
# Зачем?

Пора покрывать проект тестами.
Тесты на CRUD команды. ОБЯЗАТЕЛЬНО сделать TODO пометку пермишенов. Как будут польностью реализованы, поправим тесты

# Как нужно делать?

- обязательно используем фабрики в качестве тестовых данных

# Где?

adaptive_hockey_federation/tests

**Comment by Nurbek878** [comment]
Как я увидел, что будут тесты по игроку и по пользователям, поэтому думаю лучше тесты по каждой сущности делать в отдельном файле. Создал файл command_test по аналогии с url_test
