### ISSUE TITLE
Поправить стили для выпадающих списков и закрепить футер в отображении основного окна

### ISSUE THREAD

**Issue by KonstantinRaikhert** [Studio-Yandex-Practicum/adaptive_hockey_federation#264]
# Зачем?

В блоке аналитика:
- хотелось бы иметь кнопку идеинтичную стилю и выпадающие списки интуитивно понятны, что они выпадающие)
Воззможно стоит использовать те же стили, что и в формах игрока?
- сделать футер отображаемых. А табличку с аналитикой и игроками со скроллом
![2024-03-19_16-54](https://github.com/Studio-Yandex-Practicum/adaptive_hockey_federation/assets/69113745/1f490854-36e7-47ba-ada3-742917b15d9f)
![2024-03-19_16-56](https://github.com/Studio-Yandex-Practicum/adaptive_hockey_federation/assets/69113745/55bb325c-e08d-40e8-bff7-7bc308917a11)
![2024-03-19_16-57](https://github.com/Studio-Yandex-Practicum/adaptive_hockey_federation/assets/69113745/dcaace93-2370-456d-a25e-9554e6b6fa35)

**Comment by Ilya-Ivashchenk0** [comment]
привет, нужно что бы футер был виден всегда фиксировано?

остальное понял

**Comment by KonstantinRaikhert** [comment]
> привет @KonstantinRaikhert 
> 
> 
> 
> нужно что бы футер был виден всегда фиксировано?
> 
> 
> 
> остальное понял
> 
> 

Привет!
Да, вроде как на остальных страницах везде футер виден и переключается контент пагинацией.

**Comment by Ilya-Ivashchenk0** [comment]
так будет интуитивно понятно?
![image](https://github.com/Studio-Yandex-Practicum/adaptive_hockey_federation/assets/120082609/7ef220a2-ae73-4b68-96cd-86425d6a4818)
@KonstantinRaikhert

**Comment by Ilya-Ivashchenk0** [comment]
![image](https://github.com/Studio-Yandex-Practicum/adaptive_hockey_federation/assets/120082609/fa071000-73cf-45c9-9be6-8b29ecc06f94)

**Comment by Ilya-Ivashchenk0** [comment]
кнопка по стилю
![image](https://github.com/Studio-Yandex-Practicum/adaptive_hockey_federation/assets/120082609/a8ba9425-6394-493d-b267-e90f380f6c6f)

**Comment by Ilya-Ivashchenk0** [comment]
футер сделал фиксированным на всех страницах

**Comment by KonstantinRaikhert** [comment]
> футер сделал фиксированным на всех страницах

По моему отлично!
Думаю в dev)
