### ISSUE TITLE
Создать модель "Выгрузки" и реализовать фабрику к ней

### ISSUE THREAD

**Issue by KonstantinRaikhert** [Studio-Yandex-Practicum/adaptive_hockey_federation#267]
# Зачем?

Модель нам необходима для того, чтобы держать информацию в памяти и отображать операции по выгрузкам.
Фабрики необходимы, чтобы проще было тестировать

# Как нужно делать?

1. реализовать модель, необходимы поля:
- Имя выгрузки (в будущем будет генериться в зависимости от выбранной страницы). НЕ уникально
- Дата выгрузки
- Пользователь (кто запросил выгрузку)
- Ссылка на файл (сам файл)
2. фабрику реализовать по подобию остальных, за исключением генерации табличного файла. Его думаю генерировать с той же библиотекой, которую подключили
3. Завести это приложение в админку
4. Добавить изменения в ER диаграмму

# Где?

adaptive_hockey_federation/unloads

**Comment by KonstantinRaikhert** [comment]
@Nikita527 Тут правда просьба не затягивать с этой таской)

**Comment by Nikita527** [comment]
@KonstantinRaikhert, привет! За ранее прощу прощения. Почему-то при ПР создается отдельная таска. Не могу разобраться на каком шаге ошибка. Отправил запрос на ревью.

**Comment by KonstantinRaikhert** [comment]
> @KonstantinRaikhert, привет! За ранее прощу прощения. Почему-то при ПР создается отдельная таска. Не могу разобраться на каком шаге ошибка. Отправил запрос на ревью.

Ну это сейчас не так важно. Важнее твой ПР смержить, чтобы продолжить работу с выгрузками)
