### ISSUE TITLE
На странице создания и редактирования Игрока проверить и починить валидацию на файл

### ISSUE THREAD

**Issue by KonstantinRaikhert** [Studio-Yandex-Practicum/adaptive_hockey_federation#282]
# Где был обнаружен баг ?

На странице редактирования или создания Игрока есть форма добавить файл. 
Были настроены определенные валидаторы. Но это сейчас не работает..
![2024-03-23_17-07](https://github.com/Studio-Yandex-Practicum/adaptive_hockey_federation/assets/69113745/2236dd16-ca30-4917-8a1d-f7759632e838)
![2024-03-23_17-27](https://github.com/Studio-Yandex-Practicum/adaptive_hockey_federation/assets/69113745/c25589f3-b460-4ee9-a026-dd7b32c42695)

# Предложения и предположения как исправить

Вероятнее всего нужно дополнить форму, добавить необходимые валидаторы.
В base_settings эти настройки перенести в константы
Проверить работоспособность

**Comment by ViacheslavMelnikov** [comment]
Начал работу над новой задачей

**Comment by ViacheslavMelnikov** [comment]
Привет! Всё сделал. Сейчас оформлю и сделаю коммит

**Comment by ViacheslavMelnikov** [comment]
Привет! Когда я делал коммит Git сообщал о 10 изменениях. Скажи с какой ветки сделать клон. Внесу изменения. Всего изменил 7 файлов.
constants.py
utils.py
player_view.py
mixins.py
player_id_create_edit.html
player_id.html
base_settings.py


Я делал клон с dev

**Comment by ViacheslavMelnikov** [comment]
Привет! Вчера всё перепроверил. Вообщем у меня была старая версия ветки dev. Ну из этого ошибки и получились. С утра сел делать валидацию на файл. Форма игрока на которая используется для player_id_create_edit.html не имеет полей модели Document. Прикрутить валидатор, чтобы было сообщение пользователю (если размер или тип файла не соответствует) не получается. Проверка сама работает, а сообщения нет. Да и проверка включается только после сохранения данных по игроку.
