### ISSUE TITLE
Вопрос с двумя скроллами на странице.

### ISSUE THREAD

**Issue by KonstantinRaikhert** [Studio-Yandex-Practicum/adaptive_hockey_federation#285]
# Зачем?

Сначала я это обнаружил на странице с аналитикой
![2024-03-23_19-06](https://github.com/Studio-Yandex-Practicum/adaptive_hockey_federation/assets/69113745/bfaf5898-c808-4031-b1da-4eaf609ab0fc)

Но решил сменить количество отображаемых строчек и понял, что так везде)
![2024-03-23_19-05](https://github.com/Studio-Yandex-Practicum/adaptive_hockey_federation/assets/69113745/10b364f8-d26f-44f4-b02d-a948a65472ee)

# Как нужно делать?

Возможно нам нужно, чтобы хедер и футер был всегда на одной странице, а то что в теле скроллилось.

Тут больше вопрос, насколько это адекватно можно сделать? Два скролла как то неудобно мне показалось.

**Comment by KonstantinRaikhert** [comment]
@Ilya-Ivashchenk0 Хотел спросить, видел эту карточку? А то как то ответа не получил))

**Comment by Ilya-Ivashchenk0** [comment]
> @Ilya-Ivashchenk0 Хотел спросить, видел эту карточку? А то как то ответа не получил))

привет, постараюсь исправить

**Comment by Ilya-Ivashchenk0** [comment]
> @Ilya-Ivashchenk0 Хотел спросить, видел эту карточку? А то как то ответа не получил))

https://github.com/Studio-Yandex-Practicum/adaptive_hockey_federation/pull/305
