### ISSUE TITLE
В карточке (форме) редактирования команды применить такие же стили, как и в форме Игроки

### ISSUE THREAD

**Issue by KonstantinRaikhert** [Studio-Yandex-Practicum/adaptive_hockey_federation#286]
# Зачем?

Сейчас так:
![2024-03-23_19-10](https://github.com/Studio-Yandex-Practicum/adaptive_hockey_federation/assets/69113745/998bc5d4-798b-4540-8e44-96f047567707)

Хотелось бы вот так:
![2024-03-23_18-57_1](https://github.com/Studio-Yandex-Practicum/adaptive_hockey_federation/assets/69113745/2106d74e-903e-4dea-a63f-957b3fe7a82a)

# Как нужно делать?

Посмотреть, как реализована форма Игроков и применить те же стили и поля тут (выпадающие меню особо важны)

**Comment by KonstantinRaikhert** [comment]
@Aleksey-Krd В работе?)

**Comment by Aleksey-Krd** [comment]
ох, забыл за неё совсем, сегодня сделаю
