### ISSUE TITLE
Значок на редактирование команды должен появляется только у представителя этой команды

### ISSUE THREAD

**Issue by VeraUrsul** [Studio-Yandex-Practicum/adaptive_hockey_federation#290]
# Зачем?

Чтобы в списке команд представитель команды сразу видел ту к которой прикреплен и может её редактировать
![2024-03-24_19-13-56](https://github.com/Studio-Yandex-Practicum/adaptive_hockey_federation/assets/122533248/d71f8cc0-90c7-4e30-9261-2a30bec9914e)

# Как нужно делать?

*Как мы выполняем реализацию данной задачи, какие действия нужны для достижения цели.*

# Где?

templates/main/teams

**Comment by KonstantinRaikhert** [comment]
@AntAresWeb Это только для представителя команды (агента)

**Comment by AntAresWeb** [comment]
>Это только для представителя команды (агента)

Как понял, представитель команды - это пользователь (User) который в модели Team связан в поле curator?
