### ISSUE TITLE
Скорректировать наличие кнопок в соответствии с правами у представителя команды в разделе "Соревнования"

### ISSUE THREAD

**Issue by VeraUrsul** [Studio-Yandex-Practicum/adaptive_hockey_federation#291]
# Зачем?

Для корректного отображения возможностей Представителя команды
![2024-03-24_22-32-28](https://github.com/Studio-Yandex-Practicum/adaptive_hockey_federation/assets/122533248/3870fd2e-d467-4154-a4bd-11361fb9fafa)

![2024-03-24_22-34-36](https://github.com/Studio-Yandex-Practicum/adaptive_hockey_federation/assets/122533248/37c60ffd-6b4c-496b-9ff8-228a61995264)

# Как нужно делать?

*Как мы выполняем реализацию данной задачи, какие действия нужны для достижения цели.*

# Где?

templates/main/competitions

**Comment by KonstantinRaikhert** [comment]
@VeraUrsul Привет! Сама возьмешь?
по второму скрину необходимо эти кнопки просто убрать у представителя

**Comment by KonstantinRaikhert** [comment]
@Nikita527 Необходимо помочь Вере, сейчас пока нет возможности довести таску. 
Подробности в ПР #296
