### ISSUE TITLE
Письма представителям команд

### ISSUE THREAD

**Issue by VesselchackU** [Studio-Yandex-Practicum/adaptive_hockey_federation#295]
# Зачем?
Во-первых, наверное, это не сейчас, а если останется время после разработки основного функционала (а его, скорее всего не останется)))). Во вторых, так-то с точки зрения ТЗ - совершенно незачем, но всё-таки можно сделать приложение более юзер-френдли. Типа когда команду добавляют в соревнования, представителю посылается письмо, что вот, мол, ваша команда добавлена в соревнование, которое состоится там-то и там-то, а подробности можно посмотреть вот по такой-то ссылочке.

# Как нужно делать?

Вот тут затычка небольшая. Боюсь, для отслеживания придется определить явно промежуточную модель команда-соревнования (ну или попытаться выдернуть ее через through). И в методе save() реализовать этот функционал.

**Comment by KonstantinRaikhert** [comment]
Мне кажется, такое можно решить через сигналы

**Comment by Aleksey-Krd** [comment]
@KonstantinRaikhert ну попробовать всегда можно)

**Comment by Aleksey-Krd** [comment]
@KonstantinRaikhert тут такое дело, в списке участников команд нет ни кнопок сохранения, ни каких нибудь промежуточных вещей, то есть либо допустить команду либо отстранить, то есть в момент нажатия кнопочки допустить мы отсылаем письмо, так?
