### ISSUE TITLE
В поле для поиска должно отображаться название раздела.

### ISSUE THREAD

**Issue by Nikita527** [Studio-Yandex-Practicum/adaptive_hockey_federation#300]
# Где был обнаружен баг ?

В каждом разделе нужно проверить.

# Скриншоты

Как должно быть:
![Снимок экрана 2024-03-28 134716](https://github.com/Studio-Yandex-Practicum/adaptive_hockey_federation/assets/120462996/05c57554-bc4f-4452-949d-588e664c1d8e)

# Предложения и предположения как исправить

Посмотреть шаблон отвечающий за шапку сайта.

**Comment by DoomHunter190** [comment]
Поправлю баг в своей задаче на рефакторинг [#170](https://github.com/Studio-Yandex-Practicum/adaptive_hockey_federation/issues/170)
