### ISSUE TITLE
Привести в порядок тесты

### ISSUE THREAD

**Issue by KonstantinRaikhert** [Studio-Yandex-Practicum/adaptive_hockey_federation#301]
# Зачем?

В принципе всё уже обсуждалось, если доп вопросы, предалагаю обсудить тут

**Comment by VesselchackU** [comment]
Те, что уже ребята написали - будешь мерить?

**Comment by VesselchackU** [comment]
Ну и по существу. У нас ограничение на поля с ФИО - точно 256 символов? Я исходя из этого тесты делаю?
![image](https://github.com/Studio-Yandex-Practicum/adaptive_hockey_federation/assets/118609265/5ee6f324-d840-4a6f-b50f-08089e63dd37)
