### ISSUE TITLE
Пагинация отрабатывает неккоректно, при использовании поиска

### ISSUE THREAD

**Issue by KonstantinRaikhert** [Studio-Yandex-Practicum/adaptive_hockey_federation#303]
# Где был обнаружен баг ?

Используя поиск, получаем выборку.  Пагинация не работает в избранном списке, если нажать далее, то фильтр сброситься

# Скриншоты

![image](https://github.com/Studio-Yandex-Practicum/adaptive_hockey_federation/assets/69113745/811284ab-f75c-4603-a874-324bf57bd7f2)
![image1](https://github.com/Studio-Yandex-Practicum/adaptive_hockey_federation/assets/69113745/b2d94fab-db60-403a-8991-a82166b8c0c5)

**Comment by KonstantinRaikhert** [comment]
@xxfeel Нужно проверить, понять масштабы бедствия и можем ли решить без фронта)

**Comment by xxfeel** [comment]
@KonstantinRaikhert , поресёрчил на данную тему. Проблема в том, что данные фильтрации/поиска при переходе на другую страницу не передаются, и открывается просто например страница №2 например с игроками. Решается изменением параметров пагинации в шаблоне, примерно таким образом:
вместо
```
<a class="page-link pg-list" href="?page={{ num }}">{{ num }}</a>
```
прописываем:
```
<a class="page-link pg-list" href="?page={{ num }}{% if request.GET.search %}&search={{ request.GET.search }}{% endif %}">{{ num }}</a>
```
Должно помочь=)
Пробуем исправить?
