### ISSUE TITLE
Реализовать выгрузку для игроков

### ISSUE THREAD

**Issue by KonstantinRaikhert** [Studio-Yandex-Practicum/adaptive_hockey_federation#304]
# Зачем?

Приступаем к модулю выгрузок. Нам необходимо, чтобы при нажатии кнопки выгрузить создавался объект выгрузок и генерировался excel файл.
![2024-03-29_16-07](https://github.com/Studio-Yandex-Practicum/adaptive_hockey_federation/assets/69113745/3c2d22fd-7876-4cb0-be12-80b170df76c7)

# Как нужно делать?

Задача состоит из нескольких этапов:
- для кнопки необходимо привязать какой то endpoint, чтобы отработка происходила по нему
- нужно написать представление, которое генерирует excel файл, его выдаёт а так же сохранят объект unloads

Важной!
Есть готовая функция по экспорту excel файла, возможно её необходимо модифицировать
adaptive_hockey_federation/unloads/utils.py **export_excel**

# Где?

adaptive_hockey_federation/unloads

**Comment by KonstantinRaikhert** [comment]
@ViacheslavMelnikov Привет! Справишься? :)

**Comment by KonstantinRaikhert** [comment]
> Привет! Надо, значит надо! Постараюсь. Слушай, я ещё раз проверю, но при создании пользователя после нескольких мержев по результатам моей работы (ФИО игрока только на русском и допускается знак минуса (тире), плюс виджет календарь ограничивали минимальной и максимальной датой. Так вот фамилию Петров-Водкин указать не получается и виджет не работает как я его сделал. Можно я эту тему дополнительно к этой задачке гляну? Ок?

Да, давай. Дельное замечание!
Только давай это в ишью с багами, сделай пожалуйста и соответственно отдельной веткой. Иначе может все смешаться и трудно улавливать

**Comment by ViacheslavMelnikov** [comment]
Привет! Ишью по багам с созданием поля ФИО и указанием даты игрока сделал и уже скинул пул реквест решение. Сейчас вплотную занимаюсь решением задачи выгрузки.

**Comment by ViacheslavMelnikov** [comment]
Выгрузку сделал. Сейчас сделаю красиво название столбцов и отправлю коммит

**Comment by KonstantinRaikhert** [comment]
> Выгрузку сделал. Сейчас сделаю красиво название столбцов и отправлю коммит

Точнее пул реквест?

**Comment by KonstantinRaikhert** [comment]
@ViacheslavMelnikov Сегодня будут обновления? :)
Необходимо выработать рабочую фичу, чтобы применить её к остальным разделам
