### ISSUE TITLE
Сделать кастомную миграцию для дисциплин и убрать генерацию в фабриках

### ISSUE THREAD

**Issue by KonstantinRaikhert** [Studio-Yandex-Practicum/adaptive_hockey_federation#321]
# Зачем?

Сейчас у нас дисциплины генерируются фабриками. Для наглядности и дальнейшего использования решено сделать их миграциями (как группы у пользователей).

# Как нужно делать?

1. необходимо создать кастомную миграцию с четырьмя дисциплинами:
- следж-хоккей
- хоккей для незрячих
- специальный хоккей
- роликовый следж-хоккей
2. Фабрику, генерирующую дисциплины нужно упразднить, однако предусмотреть заполнение тестовыми данными, чтобы ничего не ломалось

**Comment by pandenic** [comment]
Для этого нужно создать новую миграцию или добавить в существующую?

**Comment by KonstantinRaikhert** [comment]
> Для этого нужно создать новую миграцию или добавить в существующую?

Создавать новую. Про нюансы, про котрые спрашивал в пачке. 
Сейчас у нас есть сущность Discipline, которая связана с DisciplineLevel и DisciplineName. И возможно это сейчас ошибка в проектировании связей. Необходимо, чтобы задавалась в интерфейсе дисциплина, а уже по необходимой дисциплине происходил выбор числового статуса. Сейчас если посмотреть в интерфейсе немного не так..
![2024-04-04_18-11](https://github.com/Studio-Yandex-Practicum/adaptive_hockey_federation/assets/69113745/e7f52307-0052-452f-aeeb-7b6d55118817)

То есть задачу нужно выполнить! Но вопрос как, будем ли мы переделывать связи в моделях или оставим так и будем шаманить интерфейс. Сегодня на созвоне как раз это и хотел обсудить

**Comment by pandenic** [comment]
Можно сделать тоже самое. В том плане, что я просто перенесу создание Discipline и двух остальных в миграции.
Либо можно вообще оставить только Discipline c одним столбцом, где будет название + числовой статус и уже на уровне view отсекать название в выпадающих меню, например.

**Comment by pandenic** [comment]
Сделал пр
