### ISSUE TITLE
В разделе игроки вместо диагноза сделать команду и классификацию

### ISSUE THREAD

**Issue by KonstantinRaikhert** [Studio-Yandex-Practicum/adaptive_hockey_federation#322]
# Зачем?

![2024-04-02_16-52](https://github.com/Studio-Yandex-Practicum/adaptive_hockey_federation/assets/69113745/806ac711-15ed-47d2-9749-587962acfe36)
![2024-04-02_16-52_1](https://github.com/Studio-Yandex-Practicum/adaptive_hockey_federation/assets/69113745/a51bd0b8-4a56-4301-b72d-8b4750c76ac9)

# Как нужно делать?

*Как мы выполняем реализацию данной задачи, какие действия нужны для достижения цели.*

# Где?

*Где делаем реализацию задачи, какие сервисы задействованы, ссылка на требования, сcылка на API, скриншоты.*

**Comment by DoomHunter190** [comment]
Изменение добавленно в #326
