### ISSUE TITLE
Разделить дисциплину и числовые статусы на отдельные поля

### ISSUE THREAD

**Issue by KonstantinRaikhert** [Studio-Yandex-Practicum/adaptive_hockey_federation#323]
# Зачем?

Проблема в том, что у нас это на уровне проектирования БД, нужно сейчас как то решить эту проблему и разделить дисциплины и числовые статусы, так же отображать их отдельно
![2024-04-02_16-58](https://github.com/Studio-Yandex-Practicum/adaptive_hockey_federation/assets/69113745/585b1ec0-1c2a-45c8-aacf-6de7a3c54f30)

# Как нужно делать?

Возможно это можно реализовать без изменений в структуре моделей

# Где?

adaptive_hockey_federation/main

**Comment by DoomHunter190** [comment]
Возьму

**Comment by DoomHunter190** [comment]
1. В каких разделах нужно разделение ? (только в профиле игрока или еще где-то ?)
2. Желательно создать таску, чтобы прикрутили валидатор к полю "Дисциплина", в формате <Назвиние дисциплины (Статус)> (Если будут добавлять еще дисциплины).
Я хочу реализовать функцию разделение строки на 2 элемента. Деление будет происходит после скобки "(".

**Comment by DoomHunter190** [comment]
![image](https://github.com/Studio-Yandex-Practicum/adaptive_hockey_federation/assets/124585181/9e40d0c4-bd32-45c4-917d-341895ff7a96)
вот так это будет выглядить
