### ISSUE TITLE
Поправить футер в шаблонах

### ISSUE THREAD

**Issue by KonstantinRaikhert** [Studio-Yandex-Practicum/adaptive_hockey_federation#331]
# Где был обнаружен баг ?

Было обнаружено, что некоторые страницы неправильно отображают футер. Скорее всего дело в разметке. Необходимо пробежаться по всем страницам

# Скриншоты

![2024-04-04_18-19](https://github.com/Studio-Yandex-Practicum/adaptive_hockey_federation/assets/69113745/14cac090-0393-4695-8188-8dc565f730ee)
![2024-04-04_18-21](https://github.com/Studio-Yandex-Practicum/adaptive_hockey_federation/assets/69113745/cd093c5c-a34c-4f8b-9ec8-872f283d8742)

# Предложения и предположения как исправить

Поискать различия в шаблонах разметки и поправить

**Comment by Ilya-Ivashchenk0** [comment]
https://github.com/Studio-Yandex-Practicum/adaptive_hockey_federation/pull/334
подправил
