### ISSUE TITLE
Реализвать выгрузку в пользователях по аналогии с игроками

### ISSUE THREAD

**Issue by KonstantinRaikhert** [Studio-Yandex-Practicum/adaptive_hockey_federation#335]
# Зачем?

Сейчас реалдизована выгрузка у игроков, нужно так же сделать у пользователей

# Как нужно делать?

См. players

# Где?

users

**Comment by KonstantinRaikhert** [comment]
@Nikita527 Берешь?)

**Comment by Nikita527** [comment]
@KonstantinRaikhert беру 👌
