### ISSUE TITLE
Реализвать выгрузку в командах по аналогии с игроками

### ISSUE THREAD

**Issue by KonstantinRaikhert** [Studio-Yandex-Practicum/adaptive_hockey_federation#336]
# Зачем?

Сейчас реалдизована выгрузка у игроков, нужно так же сделать у команд

# Как нужно делать?

См. players

# Где?

unloads

**Comment by KonstantinRaikhert** [comment]
@AntAresWeb Возьмешь? Может что-то свое предложишь в реализации?)

**Comment by KonstantinRaikhert** [comment]
> Посмотрел, что уже сделано. Выгрузка работает не совсем так, как нужно:
> 
> 1. Файл создаётся на стороне сервера.
> 2. В таблицу базы данных записывается константное имя файла. А нужно, чтобы имя файла было уникальным, коль уж мы хотим сохранять запросы на выгрузку в БД и файлы (как результат выгрузки) на сервер?
> 3. Создаваемый во время очередного запроса на выгрузку файл не грузится по сети на компьютер пользователя. А нужно чтобы передавался?
>    Ну и наверное нужно, чтобы пользователь мог выбрать тип выгружаемого файла. Хотя бы *.csv, *.xlsx или *.pdf?
>    Также нужно при запросе на выгрузку обработать разрешения пользователя на данный функционал?
> 
> P.S. А вообще есть необходимость сохранять в базу данных выгружаемые пользователем файлы?

1. А где должен создаваться файл? Мы же бэкенд...
2. Тут нужно будет делать позже какую то универсальную функцию для всех сущностей, чтобы генерировать имена
3. Сейчас только xlsx, не нужно перегружать функционал сейчас) Дополнительных запросов от заказчика пока не было.

Необходимо сохранять видимо еще для истории, кто и что запрашивал.


В итоге получилось приступить к задаче?

**Comment by AntAresWeb** [comment]
Не знал, что заказчик хочет иметь историю загрузок, отсюда у меня возникли 1 и 3 вопросы... Теперь понятно.
Для получения уникального имени загружаемого файла у нас уже есть функция, которая используется для генерации имен загружаемых документов игрока.

Вчера практически не было времени посмотреть код. Сегодня добрался, изучаю, пишу заметки. Нашел один баг - вываливается ошибка при загрузке файла  FileNotFoundError at /unloads/players/ Знаю почему, поправлю.
Попутно добавлю экшен для удаления файла с диска при удалении записи о выгруженном файле из модели **Unload**.
Думаю, что нужно попутно провести кое какой рефакторинг представления **DataExportView** - вынести рутину связанную с подготовкой имени файла в utils.
Ну и ещё один вопрос. Насколько необходимо наведение красоты в выгружаемом файле с разными шрифтами? Это желание заказчика?

**Comment by AntAresWeb** [comment]
Ставлю таску на паузу.
