### ISSUE TITLE
Необходимо сделать правильное представление StaffTeamMember

### ISSUE THREAD

**Issue by KonstantinRaikhert** [Studio-Yandex-Practicum/adaptive_hockey_federation#342]
# Зачем?

Сотрудник команды (StaffTeamMember) может состоять в разных командах как тренер, так и пушер-тьютор. Сейчас во вьюхе некорректно - StaffMember.
Соответственно, если у нас один человек занимает две должности в команде, то:
    1. Не отображаются обе записи
    2. При удалении одной удаляются две, поскольку происходит касакадное удаление.

# Как нужно делать?

Переработать персонал команд. Поправить отображение в шаблоне, если участие в нескольких командах, то лучше отображать несколько карточек
![2024-04-10_19-18](https://github.com/Studio-Yandex-Practicum/adaptive_hockey_federation/assets/69113745/08ef876d-35a1-4370-8b0b-633a189f46b2)

# Где?

main/controllers/staff_views.py

**Comment by KonstantinRaikhert** [comment]
@xxfeel А сейчас готов?))

**Comment by xxfeel** [comment]
> @xxfeel А сейчас готов?))

Привет!) Да, готов 😄
Сегодня сяду, разберусь. @DoomHunter190 последний коммит в ветке актуальный?

**Comment by VesselchackU** [comment]
Привет. @xxfeel , @KonstantinRaikhert . Я хотел бы уточнить "диагноз" проблемы), так как при написании тестов выявил эту проблемку, а в тудушке, если честно, наверное, не совсем полно ее описал, ибо ночь была))), а потом чёт руки не дошли выправить по человечьи. 
Так вот: 
Если сейчас в админке создать одного StaffMember и там же в админке создать с этим StaffMember двух StaffTeamMember-ов (типа в одних командах тренер, а в других - пушер-тьютор), то на сайте:
1. Будет отражаться только один.
2. При попытке изменить его вылазит ошибка о том, что метод get() вернул два объекта.
![image](https://github.com/Studio-Yandex-Practicum/adaptive_hockey_federation/assets/118609265/aca70f55-df45-4619-8496-7ec8f6e0e8e5)
хотя просто посмотреть - пожалуйста
3.  Ну и если удаляем, то удаляются каскадно оба.

**Comment by KonstantinRaikhert** [comment]
> Привет. @xxfeel , @KonstantinRaikhert . Я хотел бы уточнить "диагноз" проблемы), так как при написании тестов выявил эту проблемку, а в тудушке, если честно, наверное, не совсем полно ее описал, ибо ночь была))), а потом чёт руки не дошли выправить по человечьи. Так вот: Если сейчас в админке создать одного StaffMember и там же в админке создать с этим StaffMember двух StaffTeamMember-ов (типа в одних командах тренер, а в других - пушер-тьютор), то на сайте:
> 
> 1. Будет отражаться только один.
> 2. При попытке изменить его вылазит ошибка о том, что метод get() вернул два объекта.
>    ![image](https://private-user-images.githubusercontent.com/118609265/321631655-aca70f55-df45-4619-8496-7ec8f6e0e8e5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI4NDg2MDgsIm5iZiI6MTcxMjg0ODMwOCwicGF0aCI6Ii8xMTg2MDkyNjUvMzIxNjMxNjU1LWFjYTcwZjU1LWRmNDUtNDYxOS04NDk2LTdlYzhmNmUwZThlNS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDExJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQxMVQxNTExNDhaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1iNWI4NmZjNjlhMDExNDM1MGU3NmRiMjM0NzI3MzU1ZjJhMmI2ZWU2MDU3MTk3MjE3MzRmZTVmNjZlNWE1ZDNmJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.vrpXr_38KbR5lDm188i6PhkcsQz8v-bpZF_k7uyOSns)
>    хотя просто посмотреть - пожалуйста
> 3. Ну и если удаляем, то удаляются каскадно оба.

Ага, спасибо!
@xxfeel У тебя может появились вопросы?

**Comment by xxfeel** [comment]
Да, вопросы есть =)
Не совсем понимаю как сотрудник которому присвоена квалификация, допустим тренер, может быть в другой команде пушером. В другой команде он может быть тоже только тренером.

![Image](https://github.com/Studio-Yandex-Practicum/adaptive_hockey_federation/assets/106034945/66189c3b-77df-4cdb-8f9e-cc7efb15dea3)

Можно конечно создать дополнительную запись, в таблице ```staffteammember``` (что опубликована выше), в поле staff_position поменять запись на "пушер-тьютор", но что будет в полях ```заметки``` и ```квалификация```, то же самое что и в первой записи, то есть копипаст?

или так и должно работать?

**Comment by xxfeel** [comment]
Да, вопросы есть =)
Не совсем понимаю как сотрудник которому присвоена квалификация, допустим тренер, может быть в другой команде пушером. В другой команде он может быть тоже только тренером.


![Image](https://github.com/Studio-Yandex-Practicum/adaptive_hockey_federation/assets/106034945/9ec75bdd-48c9-4954-92cd-fe501224692d)


Можно конечно создать дополнительную запись, в таблице ```staffteammember``` (что опубликована выше), в поле staff_position поменять запись на "пушер-тьютор", но что будет в полях ```заметки``` и ```квалификация```, то же самое что и в первой записи, то есть копипаст?

или так и должно работать?

**Comment by KonstantinRaikhert** [comment]
@xxfeel @VesselchackU Да, нам бы получить функционал где один StaffMember может быть как тренером, так и пушером.
Давайте сегодня обсудим

**Comment by xxfeel** [comment]
> @xxfeel , @KonstantinRaikhert , если ситуация с возможностью занятия одним человеком функций пушка и тренера невозможна (хотя, например, допускаю, что в одной команде он может быть одновременно и тем и другим, если например сотрудников не хватает), то тогда нет смысла разделять эти две модели, поскольку получаем неимоверное усложнение. Либо модель  StaffTeamMember должна являться моделью through с дополнительными полями для связки StaffMember - Team.

@VesselchackU , солидарен с тобой. Поле  ```staff_position``` из модели ```StaffTeamMember``` убрать, в промежуточной модели многие-к-многим в поле ```team``` добавить это самое поле ```staff_position```, вроде должно получится, и не будет дублирований. 
@KonstantinRaikhert на созвон сегодняшний в лучшем случае опоздаю, либо вовсе не получится прийти. Если меня не будет, срезюмируйте сюда итоги пожалуйста))

**Comment by VesselchackU** [comment]
> @VesselchackU , солидарен с тобой. Поле `staff_position` из модели `StaffTeamMember` убрать, в промежуточной модели многие-к-многим в поле `team` добавить это самое поле `staff_position`, вроде должно получится, и не будет дублирований.

@xxfeel Я имел ввиду, что в модели StaffMember сделать м2м поле teams (ну, или в Team сделать м2м staff_members, что, пожалуй, более логично), а в этом м2м в параметрах указать, что through=StaffTeamMember. Ну и StaffTeamMember настроить так, чтобы он нормально работал как промежуточная модель. Нам, правда, придется, конечно, вьюхи потом все переколбашивать... Но, их и так придется.
Блин, чего-то из такой маленькой проблемки большая работа вылезает....

**Comment by KonstantinRaikhert** [comment]
> > @VesselchackU , солидарен с тобой. Поле `staff_position` из модели `StaffTeamMember` убрать, в промежуточной модели многие-к-многим в поле `team` добавить это самое поле `staff_position`, вроде должно получится, и не будет дублирований.
> 
> @xxfeel Я имел ввиду, что в модели StaffMember сделать м2м поле teams (ну, или в Team сделать м2м staff_members, что, пожалуй, более логично), а в этом м2м в параметрах указать, что through=StaffTeamMember. Ну и StaffTeamMember настроить так, чтобы он нормально работал как промежуточная модель. Нам, правда, придется, конечно, вьюхи потом все переколбашивать... Но, их и так придется. Блин, чего-то из такой маленькой проблемки большая работа вылезает....

Дааа блин.. поэтому важно активно коммуницировать с заказчиком, и чтобы такие правки не вылезали в конце сдачи))
Для этого и был поднят stage. В коммерческой разработке конечно активнее все мониторится.
Все же решаемо. Предлагаю декомпозировать. Для начала определить нужные связи и заполнение БД. Далее править шаблоны

**Comment by KonstantinRaikhert** [comment]
@xxfeel Посмотрел я на модели и понял что нам стоит поправить

```
class StaffTeamMember(models.Model):

    staff_member = models.ForeignKey(
        StaffMember,
        on_delete=models.CASCADE,
        verbose_name=_("Сотрудник"),
        help_text=_("Сотрудник"),
    )
staff_position = models.CharField(
        max_length=CHAR_FIELD_LENGTH,
        choices=STAFF_POSITION_CHOICES,
        default=EMPTY_VALUE_DISPLAY,
        verbose_name=_("Статус сотрудника"),
        help_text=_("Статус сотрудника"),
    )
    team = models.ManyToManyField(
        Team,
        related_name="team_members",
        verbose_name=_("Команда"),
        help_text=_("Команда"),
    )
    qualification = models.CharField(
        max_length=CHAR_FIELD_LENGTH,
        default=EMPTY_VALUE_DISPLAY,
        blank=True,
        verbose_name=_("Квалификация"),
        help_text=_("Квалификация"),
    )
    notes = models.TextField(
        default=EMPTY_VALUE_DISPLAY,
        verbose_name=_("Описание"),
        help_text=_("Описание"),
        blank=True,
    )
class Meta:
        verbose_name = "Сотрудник команды"
        verbose_name_plural = "Сотрудники команды"
        constraints = [
            models.UniqueConstraint(
                name="staff_member_position_unique",
                fields=[
                    "staff_member",
                    "staff_position",
                ],
            ),
        ]
        permissions = [
            ("list_view_staff", "Can view list of Персонала команды"),
        ]
```
тут видимо на стоит поменять удаление связанной сущности, чтобы стафф не удалялся при удалении из команды.
В остальном вроде все нормально по моделям. Мы можем добавить несколько команд. А вот может uniqueconstaint стоит снести.

Далее по формам. Кажется есть вариант добавить в шаблон выпадающий список
![2024-04-12_18-27](https://github.com/Studio-Yandex-Practicum/adaptive_hockey_federation/assets/69113745/d11fc69c-ed49-42b6-8aab-819f065013c9)

И сделать проверку в форме, Если не выбрана персона, то берем из полей

**Comment by KonstantinRaikhert** [comment]
@VesselchackU Согласен? Или лучше по другому

**Comment by KonstantinRaikhert** [comment]
@xxfeel На созвоне пришли к выводу, что в модели StaffTeamMember поле team поменять на ForeignKey. И тогда вроде наши проблемы должны разрешиться

**Comment by xxfeel** [comment]
> @xxfeel На созвоне пришли к выводу, что в модели StaffTeamMember поле team поменять на ForeignKey. И тогда вроде наши проблемы должны разрешиться

Спасибо, принял =)

**Comment by xxfeel** [comment]
@KonstantinRaikhert , привет, переназначь пожалуйста задачу на другого разработчика, сейчас пока нет возможности заниматься. Извиняюсь за доставленные неудобства.

**Comment by VesselchackU** [comment]
@KonstantinRaikhert На неделе смогу заняться, если что

**Comment by VesselchackU** [comment]
Предлагаю сделать что-то в этом роде
![image](https://github.com/Studio-Yandex-Practicum/adaptive_hockey_federation/assets/118609265/f372042f-3142-43d3-ae61-9d1bc55e7a9a)

**Comment by KonstantinRaikhert** [comment]
> Предлагаю сделать что-то в этом роде ![image](https://private-user-images.githubusercontent.com/118609265/322296287-3261ec91-4fb0-4594-b445-6fe6675798a8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTMxMjI3MjAsIm5iZiI6MTcxMzEyMjQyMCwicGF0aCI6Ii8xMTg2MDkyNjUvMzIyMjk2Mjg3LTMyNjFlYzkxLTRmYjAtNDU5NC1iNDQ1LTZmZTY2NzU3OThhOC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDE0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQxNFQxOTIwMjBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0xYTk0MmIyOWYzODRkMTcyMjk0ZWVlMTE4OGM1YTNjMTVlNWNiZDZjN2NmNWMzMjg1N2E4ODY4NTNjYzdjYWQ5JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.fS6wBZZhyIewDFjhsg0AnEpoXa0t1jV6VqJpHPcLulg)

Спасибо, что откликнулся! Перезначаю на тебя.

**Comment by VesselchackU** [comment]
@KonstantinRaikhert Привет. Переделал модели. Прежде, чем подступиться к вьюхам, надо бы разобраться с фабриками, чтобы make fill-test-db корректно отрабатывал создание фикстур. Можешь дать кого в помощь на эту работу? Там не так глобально, мне кажется, просто я до этого с фабриками особо не разбирался, и на это время уйдет. Если да, я запушу просто свою ветку и там мы с кем-нить будем работать. Желательно бы, конечно, кого-нибудь, кто с фабриками уже разбирался. Если нет такой возможности - ок, просто чуть подольше будет...

**Comment by KonstantinRaikhert** [comment]
@Aleksey-Krd Привет! Сможешь помочь с фабриками?

**Comment by Aleksey-Krd** [comment]
@KonstantinRaikhert привет, да смогу, что нужно сделать?

**Comment by VesselchackU** [comment]
> @KonstantinRaikhert привет, да смогу, что нужно сделать? 

@Aleksey-Krd Скачай себе ветку features/refactor_staffs. В ней изменены модели: Team, StaffMember, StaffTeamMember (https://github.com/Studio-Yandex-Practicum/adaptive_hockey_federation/issues/342#issuecomment-2054152316). 
Задача - поправить фабрики и Makefile так, чтобы они корректно выполняли заполнение БД текстурами. У нас теперь от StaffMember напрямую М2М к Team, а StaffTeamMember - это промежуточная модель между ними с доп. полями. Надо, думаю, чтоб в итоге создавалось плюс-минус по два StaffTeamMember на одну команду. Один - тренер, и один - пушер. Обрати внимание на новый UniqueConstraint в StaffTeamMember. Идеально, если будет пара-тройка случаев, где в одной команде тренером и пушером один StaffMember является (но это не обязательно, если сильно геморройно - ну его)

Если возьмёшься, сделай, наверное, от ветки features/refactor_staffs дочернюю ветку и в ней работай, а потом - ПР не в дев, а в features/refactor_staffs. 

Makefile и factories - в твоём распоряжении, а вот от редактирования models, urls, views - по возможности воздержись.

**Comment by Aleksey-Krd** [comment]
@KonstantinRaikhert понял, принял, сегодня сделаю

**Comment by Aleksey-Krd** [comment]
@VesselchackU что-то у тебя тут в моделях как мне кажется не совсем всё правильно), у тебя ошибки при миграциях есть какие нибудь?

**Comment by Aleksey-Krd** [comment]
![Screenshot_6](https://github.com/Studio-Yandex-Practicum/adaptive_hockey_federation/assets/118228004/82b22536-70ff-4eaa-8c3f-a7d222e973ed)
 вы первых ругается, раз во 2 ругается что поле team в модели StaffTeamMember - > Невозможно добавить поле "команда", значение которого не может быть равно нулю, в staff team member без указания значения по умолчанию. Это связано с тем, что базе данных требуется что-то для заполнения существующих строк.

**Comment by Aleksey-Krd** [comment]
ну и когда миграции вроде добавлены, ловлю ошибку 
![Screenshot_7](https://github.com/Studio-Yandex-Practicum/adaptive_hockey_federation/assets/118228004/3333eded-e8be-4414-8f6f-781aa74b3d99)

**Comment by Aleksey-Krd** [comment]
@KonstantinRaikhert ответьте люди добрые)) почему мы не можем сделать вот так?
![Screenshot_10](https://github.com/Studio-Yandex-Practicum/adaptive_hockey_federation/assets/118228004/88651c4d-a3f8-4f17-b521-a138e18c12db)
![Screenshot_8](https://github.com/Studio-Yandex-Practicum/adaptive_hockey_federation/assets/118228004/849f3aca-896a-429f-b111-96ee9731db23)
![Screenshot_9](https://github.com/Studio-Yandex-Practicum/adaptive_hockey_federation/assets/118228004/7bc764fc-31eb-4b1c-ad56-c151bbbf55e6)

**Comment by Aleksey-Krd** [comment]
@KonstantinRaikhert я не могу запустить у себя вариант с ветки features/refactor_staffs, ошибки показал выше

**Comment by VesselchackU** [comment]
@Aleksey-Krd Привет. Через полчасика доберусь до компа гляну. Чёт, странно, все должно было быть ок. Неужели чего-то пропустил...

**Comment by Aleksey-Krd** [comment]
@VesselchackU в твоей ветке новых миграций нет, как ты проверял, что работает?

**Comment by Aleksey-Krd** [comment]
@VesselchackU понял, хорошо буду ждать - отпиши тогда когда сделаешь

**Comment by VesselchackU** [comment]
@Aleksey-Krd Так, вроде поправил, миграции сделал, запушил. Попробуй, будет мигрировать - нет? На пустой БД  всё норм проходит.

**Comment by VesselchackU** [comment]
> @VesselchackU так, мне нужно минут 30 - я отпишусь

@Aleksey-Krd Да без проблем.

**Comment by VesselchackU** [comment]
> ответьте люди добрые)) почему мы не можем сделать вот так?

@Aleksey-Krd Потому что в этом и есть корень проблемы, из-за которой мы и пустились в рефакторинг этой связки Team - StaffMember - StaffTeamMember :-)=). Можешь почитать переписку в начале issue. Но на самом деле там даже еще глубже проблема...

**Comment by Aleksey-Krd** [comment]
@Vesse
![Screenshot_2024-04-15-22-37-22-95_21da60175e70af211acc4f26191b7a77](https://github.com/Studio-Yandex-Practicum/adaptive_hockey_federation/assets/118228004/3a8c8b4b-2650-496a-9f27-77d56e5bb935)
lchackU корень проблемы вот здесь))) во вьюхе редактирования, потому что get возвращает первое найденное значение которое нашёл, потому и ругается когда вы хотите получить два, здесь просто надо вьюху подшаманить

**Comment by Aleksey-Krd** [comment]
@VesselchackU Судя по проблеме что вы там озвучили, если создавать на основе staffmembera тренера и пушера, у них по идее должны быть разные ID шники один что он тренер, другой, что он пуштутор в таблице staffteammember, ну а когда мы добавляем в команду его то соответственно разные ID из таблицы staffteammember берутся и у нас спокойно может быть как тренер так и пушер в одной команде один и тот же человек, ну я так вижу здесь это, тут никаких противоречий у нас нет, таблицы staffmember и таблицы staffteammember это 2 разные таблицы

**Comment by Aleksey-Krd** [comment]
@VesselchackU а добавляются эти данные из-за того, что связь m2m в промежуточную таблицу которая называется примерно staffteammember_team где у нас только ID, ID_staffteammember и id_team

**Comment by VesselchackU** [comment]
> @VesselchackU Судя по проблеме что вы там озвучили, если создавать на основе staffmembera тренера и пушера, у них по идее должны быть разные ID шники один что он тренер, другой, что он пуштутор в таблице staffteammember, ну а когда мы добавляем в команду его то соответственно разные ID из таблицы staffteammember берутся и у нас спокойно может быть как тренер так и пушер в одной команде один и тот же человек, ну я так вижу здесь это, тут никаких противоречий у нас нет, таблицы staffmember и таблицы staffteammember это 2 разные таблицы

Так тут в том-то и дело, что они существовали как-то параллельно и несогласованно. 
- Вот есть Вася. Я хочу его взять в команду тренером. Вася, добавься в мою команду с опцией "тренер" - так должно быть. 
- Вот есть Вася. Я хочу его взять в команду тренером. Вася, запишись в таблицу Сотрудники команды по должности тренер, а потом я в этой таблице найду запись Вася-тренер, и возьму себе в команду Васю-тренера. При том, что есть поле notes, которое, подразумевается, что в каждой команде может быть разное... Так, кстати, а это так? Блин, спросить надо... @KonstantinRaikhert . Ну, короче, вот это так, как у нас было...

**Comment by VesselchackU** [comment]
В общем, об этом можно бесконечно спорить. Я рассказал о возможной проблеме. Поговорили, решили исправить так. Как говорится, за что боролся, на то и напоролся))))))

**Comment by Aleksey-Krd** [comment]
@VesselchackU у нас есть Вася в таблице StaffMember под id = 1, этот Вася пошёл в команду допустим id=1 на позицию тренера тем самым создалась запись в таблице staffteammember  допустим первая с id =1, где id Василия = 1 и  staff_position = 'тренер'? и в таблицу staffteammember_team делается запись id=1 staffmember=1 id_team=1. Дальше Вася решил, что этого для его персоны не достаточно и он хочет быть еще и пушером, дальше в таблице staffteammember появится запись с id=2, где id Василия снова = 1, но staff_position = 'пуштутер' и дальше в таблицу staffteammember_team делается запись id=2 staffmember=2 id_team=1

**Comment by KonstantinRaikhert** [comment]
Тут можно и поспорить, главное истину найти, и меньшей кровью))

Итак, получается, что в изначальном варианте есть проблема, что тренер будет добавлен в разные команды но только с одним описанием. Это не проблема, квалификация и описание (доп. поля) это заметки непосредственно о его тренерской компетенции.

Кажется действительно залезли в дебри. Давайте попробуем накидать плюсы и минусы этих двух реализаций. Точнее даже так. Какими проблеми нам обернется оставить старую версию структуры в БД?

**Comment by Aleksey-Krd** [comment]
@VesselchackU и мы спокойно можем как из команды узнать про этого василия, так и от василия узнать про команду

**Comment by Aleksey-Krd** [comment]
@VesselchackU ну и соответственно если вдруг Вася решит, что и этого ему мало и захочет стать тренером второй команды, в таблице staffteammember_team появятся еще 2 записи, условно говоря id=3 staffteammember=2 id_team=4 id=3 staffteammember=1 id_team=4, тут вроде никаких противоречий нет

**Comment by VesselchackU** [comment]
> Какими проблеми нам обернется оставить старую версию структуры в БД?

Ну, так-то ничего неразрешимого, кроме длинной цепочки sfaff - foreignkey - staffmember - manytomeny - team. Получается, чтобы отобразить в команде фио сотрудника, надо всю эту цепочку обратно пройти. А вот еще вопрос, notes и  qualufication - это характеристики именно человека или человека-тренера? А у пушера квалификация есть?

**Comment by Aleksey-Krd** [comment]
@VesselchackU почему бы нам просто не избавиться от таблицы staffmember?))))

**Comment by Aleksey-Krd** [comment]
и не наследоваться от BasePerson минуя эту таблицу стафа разрешив пустые поля как это например сделано в таблице игрока? вообще накой нужна таблица staffmember какого её предназначение?

**Comment by Aleksey-Krd** [comment]
тогда связь сократиться до staffmember - manytomeny - team

**Comment by VesselchackU** [comment]
> и не наследоваться от BasePerson минуя эту таблицу стафа разрешив пустые поля как это например сделано в таблице игрока? вообще накой нужна таблица staffmember какого её предназначение?

Ну, типа есть один человек. Зачем вбивать его два раза. А вдруг он женился/замуж вышла и фамилию поменял. В двух командах менять? Ну и... там, типа телефон)))))))))

**Comment by Aleksey-Krd** [comment]
@VesselchackU что значит в двух командах менять? команда тут причём? ты меняешь запись определённого сотрудника.... данные в команды подтягиваются от одной и той же записи сотрудника в бд

**Comment by Aleksey-Krd** [comment]
ты если сейчас у игрока фамилию поменяешь, тебе дополнительные манипуляции надо делать в командах или фамилия там автоматически поменяется?)))

**Comment by VesselchackU** [comment]
> @VesselchackU что значит в двух командах менять? команда тут причём? ты меняешь запись определённого сотрудника.... данные в команды подтягиваются от одной и той же записи сотрудника в бд

А если их два: тренер и пушок?

**Comment by Aleksey-Krd** [comment]
@VesselchackU а ну вот тут уже согласен, в этот момент действительно нужна отдельная таблица)))

**Comment by VesselchackU** [comment]
@KonstantinRaikhert Костя, спасай! Меня @Aleksey-Krd в сомнения ввёл)))). Я уже почти согласен, что ниче менять не надо))), кроме вьюх. Ребят, давайте, мож это голосом завтра обсудим? А сейчас пока переночуем с этим мыслями... У меня, чет уже башка не варит совсем. Я либо часов в 14 либо в 18 (СПб) обсудить это.

**Comment by Aleksey-Krd** [comment]
@VesselchackU ну опять же никаких противоречий со старым вариантом связей бд нет, просто когда мы меняем личные данные сотрудника, нужно меня именно staffmember, если командные то staffteammember собственно как это сейчас и организованно...

**Comment by KonstantinRaikhert** [comment]
@VesselchackU @Aleksey-Krd Да я сам запутался😅
На самом деле пока тоже согласен, что как то переусложнили. Но! Надо со свежей головой обдумать.
Давайте действительно созвонимся завтра. Предлагаю в вечернее время. @Aleksey-Krd В какое время сможешь?

**Comment by Aleksey-Krd** [comment]
@VesselchackU ну если между 18-00 и 19-00 это произойдёт то смогу

**Comment by VesselchackU** [comment]
@Aleksey-Krd  Ок. Давай тогда пока остановим насчет фабрик. Спасибо, что навел на некоторые мысли. Я теперь не уверен, что предложенный мной путь был правильный. Давайте завтречка голосом - продуктивнее будет. @KonstantinRaikhert Предпочтительнее на 18, конечно. Либо потом уже в районе 20:30

**Comment by KonstantinRaikhert** [comment]
Хорошо, днем напишу еще раз в пачке

**Comment by Aleksey-Krd** [comment]
@KonstantinRaikhert @VesselchackU 
![Screenshot_12](https://github.com/Studio-Yandex-Practicum/adaptive_hockey_federation/assets/118228004/cf0292b0-c50a-4cfd-ac62-fd35b77168f3)
![Screenshot_11](https://github.com/Studio-Yandex-Practicum/adaptive_hockey_federation/assets/118228004/07d82ef9-10bf-46e4-801a-33d49089cbc7)
хочу обратить внимание, что вьюха отображения всё корректно показывает

**Comment by Aleksey-Krd** [comment]
@KonstantinRaikhert @VesselchackU привет, что-то активность пропала по этой ишью) как успехи? Помощь нннада)? Меня кстати от пачки отключили, связь только тут

**Comment by VesselchackU** [comment]
Привет! Я в процессе. По основной работе затыки просто образовались. Я доделаю, помощь не треба. Хотел сделать, как с выбором городов в командах - с красивым инкрементарным поиском, но там есть ньюанс... В городах уникальное имя и я фактически в поле выбора просто парсил его и превращал в id города. А тут в поле нужно указывать полные ФИО, которые парсить опасно, ибо какой-нибудь «Магомед  оглы» все испортит. Я, в общем, пытался освоить java скрипты для того, чтобы скрыто от пользователя подставлять id вместо ФИО в список. Но понял, что слишком много времени потрачу.  В общем, пока остановился на том, что буду просто в дополнение к ФИО в скобках id указывать. Дай денёк другой ещё, ок? 12:56, 22 апреля 2024 г., WalkA1one ***@***.***>:
@KonstantinRaikhert @VesselchackU привет, что-то активность пропала по этой ишью) как успехи? Помощь нннада)? Меня кстати от пачки отключили, связь только тут

—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you were mentioned.Message ID: ***@***.***>
С уважением, Виктор Ушакевичmailto: ***@***.***

**Comment by Aleksey-Krd** [comment]
@VesselchackU у нас есть скрипт который встраивается поиск в select поле

**Comment by KonstantinRaikhert** [comment]
> @KonstantinRaikhert @VesselchackU привет, что-то активность пропала по этой ишью) как успехи? Помощь нннада)? Меня кстати от пачки отключили, связь только тут

Вот блин... Попробую узнать, как добавить доступ
