### ISSUE TITLE
В разделе соревнования, при создании соревнования, добавить выбор дисциплины  (дисциплин может быть несколько)

### ISSUE THREAD

**Issue by KonstantinRaikhert** [Studio-Yandex-Practicum/adaptive_hockey_federation#345]
# Зачем?

Заказчику важно, чтобы соревнования включали в себя дисциплины.

# Как нужно делать?

- добавить связь в модели (дисциплин может быть несколько)
- поправить фабрики на соревнования
- реализовать отображение в списке соревнований дисциплину
- в форме создания и редактирования соревнования добавить виджет как в форме игрока (по командам)

# Где?

adaptive_hockey_federation/competitions

**Comment by KonstantinRaikhert** [comment]
@pandenic Готов взять таску?)

**Comment by pandenic** [comment]
Да, могу, в целом

**Comment by KonstantinRaikhert** [comment]
> Да, могу, в целом

Если есть вопросы, то давай обсудим.

**Comment by pandenic** [comment]
Вообщем я предлагаю сделать так: 
1) убираю модель DisciplineName, переношу name в модель Discipline, меняю discipline_level с ForeignKey на ManyToMany.
2) везде (игроки, команды и прочие места) заменяю discipline на disciplines, проверяю и дебажу.
3) делаю миграции по дисциплинам
4) меняю фабрики соответственно
5) добавить в соревнования по плану выше

**Comment by pandenic** [comment]
@KonstantinRaikhert что думаешь?

**Comment by KonstantinRaikhert** [comment]
@pandenic Сейчас как раз хочу одобрить ПР #326 и там мы сделали по другому.. Давай его смержу, а уже на его основе реализуем

**Comment by KonstantinRaikhert** [comment]
Я не против переименования модели, нужно подумать..

**Comment by pandenic** [comment]
Там не переименование, а избавление от лишней, скорее. Окей, подожду тогда мерджа

**Comment by KonstantinRaikhert** [comment]
> Вообщем я предлагаю сделать так:
> 
> 1. убираю модель DisciplineName, переношу name в модель Discipline, меняю discipline_level с ForeignKey на ManyToMany.
> 2. везде (игроки, команды и прочие места) заменяю discipline на disciplines, проверяю и дебажу.
> 3. делаю миграции по дисциплинам
> 4. меняю фабрики соответственно
> 5. добавить в соревнования по плану выше

Для понимания:
1. Переименовать можно с DisciplineName на Discipline, но пока неясно нужно ли. discipline_level у нас имеет связь только с одной дисциплиной.

> В следж хоккее у нас 6 числовых статусов от 1 до 6
в хоккее незрячих :В1, В2, В3, В4, В5, б\к
В специальном хоккее: А, В, С

Т.е. дисциплины и числовые статусы мы потом зашьем в миграции. 
2. Игрок например может быть только в одной дисциплине и с одним числовым статусом. Команда может быть только с одной дисциплиной. А вот соревнования могут проводиться с множеством команд в различных дисциплинах (например первенство приморского края).
3. Миграции можно сделать и в этом ПР совместить например ту таску с миграциями настоящих данных, но может быть это не так удобно будет. 
4. Фабрики конечно где нужно, можно поправить
5. Ну и по инфе выше. У соревнований может быть несколько команд с различными дисциплинами. Т.е. наверно на уровне шаблонов и форм прокинуть фильрацию по дисциплинам

**Comment by pandenic** [comment]
Ну то есть останется только одна модель Discipline, где будет только name, в котором будет название + уровень. И это мы будем заполнять в миграции, правильно понял?

**Comment by KonstantinRaikhert** [comment]
> Ну то есть останется только одна модель Discipline, где будет только name, в котором будет название + уровень. И это мы будем заполнять в миграции, правильно понял?

Ну я бы модель уровней все же наверно оставил. Во первых ломать меньше, во вторых нам необходимо иметь дисциплину с привязанным набором уровней, и choicefield для нас не подойдет, оставляем возможно корректировки в админке. А уже на уровне форм позже сделаем выбор необходимых уровней с помощью выпадающего меню и формирования с помощью фронта

**Comment by pandenic** [comment]
Посмотрел #326 получается мы сделали две слабосвязанные модели с названием и уровнем дисциплины?
Тогда я делаю миграции в отдельном пр и с соревнованиями в этом. Мне кажется так ревьюить будет проще

**Comment by KonstantinRaikhert** [comment]
> Посмотрел #326 получается мы сделали две слабосвязанные модели с названием и уровнем дисциплины?
> Тогда я делаю миграции в отдельном пр и с соревнованиями в этом. Мне кажется так ревьюить будет проще

Была утилизирова модель Discipline и поэтому кажется что малосвязны. Сейчас нужно чуть побыстрее и с меньшей болью решать проблемы. Нам бы в конец месяца уложиться

**Comment by pandenic** [comment]
Окей. Сегодня-завтра тогда сделаю.

**Comment by KonstantinRaikhert** [comment]
> Окей. Сегодня-завтра тогда сделаю. 

Спасибо!👍

**Comment by pandenic** [comment]
Есть вопрос по поводу виджета: он написан с применением JS. Если есть, кто может переписать его для дисциплин быстро, было бы супер. Либо я перепишу сам.

**Comment by KonstantinRaikhert** [comment]
> Есть вопрос по поводу виджета: он написан с применением JS. Если есть, кто может переписать его для дисциплин быстро, было бы супер. Либо я перепишу сам.

@Ilya-Ivashchenk0 Случайно не ты писал?)
@pandenic Подсвети пожалуйста название

**Comment by pandenic** [comment]
![image](https://github.com/Studio-Yandex-Practicum/adaptive_hockey_federation/assets/114985447/599e7135-162d-4b1b-8055-b41a732f906c)

**Comment by Ilya-Ivashchenk0** [comment]
> > Есть вопрос по поводу виджета: он написан с применением JS. Если есть, кто может переписать его для дисциплин быстро, было бы супер. Либо я перепишу сам.
> 
> @Ilya-Ivashchenk0 Случайно не ты писал?) @pandenic Подсвети пожалуйста название

привет, нет это не мной написано. но так понимаю это написано на примере того класса который я писал, только вместо 1 их 3.

что нужно поправить?

**Comment by pandenic** [comment]
Мне бы понять как быстро это переделать на другую модель. Если есть возможность подсказать, что нужно поменять в js и в каких файлах?

**Comment by Ilya-Ivashchenk0** [comment]
> Мне бы понять как быстро это переделать на другую модель. Если есть возможность подсказать, что нужно поменять в js и в каких файлах?

может созонимся?

**Comment by pandenic** [comment]
Через пол часа удобно будет?

**Comment by Ilya-Ivashchenk0** [comment]
> Через пол часа удобно будет?

+

**Comment by pandenic** [comment]
Супер. Предлагаю в google meet в 21: https://meet.google.com/imw-uemn-zei

**Comment by pandenic** [comment]
Обнаружил что при создании соревнования, дата показывается в американском формате mm/dd/yyyy

**Comment by KonstantinRaikhert** [comment]
> Обнаружил что при создании соревнования, дата показывается в американском формате mm/dd/yyyy

Понял, проверим по проекту. 
Вы пришли к какому то результату вчера?

**Comment by pandenic** [comment]
Пришли. Вроде понял примерно. На странице показывается, но при нажатии на кнопку создание, в бд не создаётся.

**Comment by pandenic** [comment]
У меня по работе жёсткая загрузка вчера прилетела. До выходных терпит или лучше передать?

**Comment by KonstantinRaikhert** [comment]
> У меня по работе жёсткая загрузка вчера прилетела. До выходных терпит или лучше передать?

До выходных терпит!)

**Comment by pandenic** [comment]
Обнаружил некорректное название функции:
![image](https://github.com/Studio-Yandex-Practicum/adaptive_hockey_federation/assets/114985447/6161ad09-b4a8-4fe8-a849-8342f4bf6602)

По факту она работает только для модели Team

**Comment by pandenic** [comment]
Ещё некорректно ишется уведомление если ставишь дату раньше текущей. Поправлю.

![image](https://github.com/Studio-Yandex-Practicum/adaptive_hockey_federation/assets/114985447/e985cf63-8dc0-4301-90ae-363da434367d)

**Comment by pandenic** [comment]
Ещё зачем-то виджет выбора называется selector-teams, а не универсально, например, selector-many-objects или типа того.
![image](https://github.com/Studio-Yandex-Practicum/adaptive_hockey_federation/assets/114985447/97aa7996-dfeb-4ad6-b96f-2b16c6e50b1c)

Предлагаю переименовать в будущем.
