### ISSUE TITLE
Провести подготовку загрузки реальных данных Игроков в БД.

### ISSUE THREAD

**Issue by KonstantinRaikhert** [Studio-Yandex-Practicum/adaptive_hockey_federation#355]
# Зачем?

У нас есть команда `make fill-db` - вот она должна загружать реальные данные из json файлов (фикстур) в БД.
Но для этого нужно провести некоторую подготовку.

# Как нужно делать?

- посмотреть на json файлы. Понять что в них не хватает и какими фейками мы можем их дополнить для загрузки
- проверить по моделям, что все сходится.

JSON скину архивом в пачку.

**Comment by alicezweig** [comment]
### discipline

1. **discipline_name должна загружаться в БД первой, тк discipline_level зависит от нее**
Необходимо поменять местами 'main_disciplinename': 'DisciplineName' и 'main_disciplinelevel': 'DisciplineLevel' в 
core/config/dev_settings.py > FILE_MODEL_MAP

2. **main_discipline.json**
Сейчас парсится в отдельную модель Discipline, которой больше нет. 
Строчка  'main_discipline': 'Discipline', больше не нужна в core/config/dev_settings.py > FILE_MODEL_MAP

3. Удалить "main_disciplinelevel" из parser/importing_db.py > MODELS_ONE_FIELD_NAME тк в модели появилось еще одно поле. 
   Исправить key на "main_disciplinelevel" (неверно написано имя файла) в 169
   Исправить name=item["name"] в 172 (согласно данным main_disciplinelevel.json)
   Добавить discipline_name_id= ??? в 173 

4. **Связь между discipline_level и discipline_name**
У модели DisciplineLevel есть поле discipline_name, которого нет в main_disciplinelevel.json, а связь name и level в БД создается в миграциях. 
    - либо вручную переписать main_disciplinelevel.json те добавить "discipline_name_id"  согласно main_discipline.json.  (там немного, я сделала так и данные загрузились корректно)
      В parser/importing_db.py > importing_real_data_db добавить discipline_name=item['discipline_name_id'] на 173.
    - либо в importing_real_data_db парсить данные для main_discipline_level из двух файлов, связь брать из main_discipline.json
    - либо оставить как есть, создавать таблицы  с данными в миграции (правда сейчас они там не такие как в json) и убрать эти файлы из парсинга
 
5. **Team и Staff**
    Модель Team не соответствует main_team.json, в модели отсутствует поле "staff_team_member_id". 
    Я не совсем поняла, какая связь в итоге будет между этими моделями, поэтому закомментила 190 в parser/importing_db.py > importing_real_data_db. Данные загрузились. 

6. **Player**
    Модель Player не соответствует данным main_player.json:
    - в данных дисциплина представлена через поле "discipline_id" (из файла main_discipline.json), в модели через поля  "discipline_name" и "discipline_level".
      Я закомментировала 208-209 в importing_real_data_db, поля могут быть null, данные загрузились. 
Возможно, предварительно придется распарсить main_discipline.json, сохранить данные в переменную и оттуда получать discipline_level_id для каждого Player по discipline_id из main_player.json. Тк discipline_name определяется только из discipline_level, и дисциплины уже загружены в БД, discipline_name можно будет взять из БД по discipline_level_id. 
    (Нужно ли это поле? Возможно, получать discipline_name можно аннотируя кверисет)

   - поле "document_id" отсутствует в модели, но присутствует в данных (хотя везде null). Закомментировала 210 в  importing_real_data_db

**Comment by alicezweig** [comment]
Если менять данные можно, то дисциплины я уже поменяла. 
Для Player, я сделала функцию которая на основе этих данных помогает заполнить модель, там можно не менять данные. Но могу и поменять.
По сути, это все что мешало загружать данные, если ориентироваться на модели которые сейчас в dev.
Или нужно заполнить все поля, чтобы пустых не было?
Завтра могу до 13.00 в любое время созвониться
