### ISSUE TITLE
Поиск с выгрузкой должны работать по всем представленным полям

### ISSUE THREAD

**Issue by KonstantinRaikhert** [Studio-Yandex-Practicum/adaptive_hockey_federation#358]
# Зачем?

Возможно не все представленные поля правильно отрабатывают в поиске.

# Как нужно делать?

Необходимо пройтись по всем формам поиска и проверить корректность работы. Если где-то не так, попробовать поправить.
Но есть вероятность, что полей немало. Можно декомпозировать и начать с определенных

**Comment by AntAresWeb** [comment]
Задачу принял

**Comment by AntAresWeb** [comment]
### **Bugs&Fix**

**Раздел Игроки (players)**
Обнаружен баг. Если задан пустой фильтр, то при переходе через пагинатор на другую страницу вываливается ошибка 500 KeyError at /players/

Решается

**Comment by AntAresWeb** [comment]
### **Тестирование**
**Раздел Игроки (players)**
При выгрузке данных в файл попадают только отобранные по фильтру игроки. Требуемая функциональность достигнута.

**Comment by KonstantinRaikhert** [comment]
> ### **Bugs&Fix**
> **Раздел Игроки (players)** Обнаружен баг. Если задан пустой фильтр, то при переходе через пагинатор на другую страницу вываливается ошибка 500 KeyError at /players/ _**Решено**_
> 
> **Раздел Пользователи (users)** Обнаружен баг. При попытке выгрузить отфильтрованные по критерию Имя данные вываливается ошибка 500 KeyError at /unloads/users/ Для фильтрации в отображении и выгрузке используется разный код. Требуется рефакторинг. _**Решается...**_

Отлично! Спасибо
