### ISSUE TITLE
НОЗОЛОГИЯ И ДИАГНОЗ...

### ISSUE THREAD

**Issue by KonstantinRaikhert** [Studio-Yandex-Practicum/adaptive_hockey_federation#359]
# Зачем?

Это больше ошибка, чем новая фича. Но работа видимо будет немалая и нужно на этапе реализации оценить, возможно ли ее декомпозировать и отдать часть другому разработчику.

Итак: У нас неправильно реализована сущность, по ERD нужно было так:
![2024-04-26_18-44](https://github.com/Studio-Yandex-Practicum/adaptive_hockey_federation/assets/69113745/f4f1ee1c-d2fe-4a9f-9488-d7a9c890f4cd)
А получилось вот так:
![2024-04-26_19-33](https://github.com/Studio-Yandex-Practicum/adaptive_hockey_federation/assets/69113745/f7035a16-db7f-47d6-8f2f-c84014c8d289)
 
Проблема в том, что у нас нозология - тип заболевания и их там не больше 8. А вот по каждой нозологии есть диагноз с непосредственным названием. 

# Как нужно делать?

Нужно начать с моделей и по мере продвижения менять вьюхи и шаблоны. Вероятнее всего заденет много сущностей (Игроки, Аналитика, Выгрузки)

# Где?

main

**Comment by DoomHunter190** [comment]
@KonstantinRaikhert поправь меня, если не так понял. У нас отсутствует поле "Diagnosis name", которое вместе с FK(nosology) дает нам название "name" заболевания?

**Comment by KonstantinRaikhert** [comment]
Да. И отображение неправильно у нас реализовано

**Comment by DoomHunter190** [comment]
@KonstantinRaikhert Начал с модели, добавил поле:

![Image](https://github.com/Studio-Yandex-Practicum/adaptive_hockey_federation/assets/124585181/4fe923af-dcb1-404f-8c03-7685dd7ae126)

Так же сейчас поменял в админки отображение:

![Image](https://github.com/Studio-Yandex-Practicum/adaptive_hockey_federation/assets/124585181/f667cde3-2a11-4da6-8092-6f44e284e930)

![Image](https://github.com/Studio-Yandex-Practicum/adaptive_hockey_federation/assets/124585181/9311ff42-98d0-4332-9a8f-8e2df6581fbd)

Через админку добавляется, работает.

![Image](https://github.com/Studio-Yandex-Practicum/adaptive_hockey_federation/assets/124585181/bd5275b0-02f6-4d3f-a78a-ead35ce24cd4)

Мне бы сейчас понять, что мы редактируем в плане форм для редактирование и как у нас должна она отображаться на страницах ?

**Comment by DoomHunter190** [comment]
Так же добавляем как числовой статус ? 

![Image](https://github.com/Studio-Yandex-Practicum/adaptive_hockey_federation/assets/124585181/e21d959d-9520-410c-a908-2b784cbb8916)



![Image](https://github.com/Studio-Yandex-Practicum/adaptive_hockey_federation/assets/124585181/6ac9565a-879a-4c5a-b49a-01f985cf7475)

**Comment by KonstantinRaikhert** [comment]
> Так же добавляем как числовой статус ?
> 
> ![Image](https://private-user-images.githubusercontent.com/124585181/326264492-e21d959d-9520-410c-a908-2b784cbb8916.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQzMjUyNTcsIm5iZiI6MTcxNDMyNDk1NywicGF0aCI6Ii8xMjQ1ODUxODEvMzI2MjY0NDkyLWUyMWQ5NTlkLTk1MjAtNDEwYy1hOTA4LTJiNzg0Y2JiODkxNi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDI4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQyOFQxNzIyMzdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT00YmY0MDE0OWQxM2RjN2FiMGVhMDdlM2RiMzQzMTk4Nzg4MTkxYTcxNTM4ZDgwMDgzMGM4M2JmOWZmNzkxNTQ4JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.u_v4esod9CmSZXqKAVx_4Az7dOw2bAvJx4tuPj7_n1g)
> 
> ![Image](https://private-user-images.githubusercontent.com/124585181/326264508-6ac9565a-879a-4c5a-b49a-01f985cf7475.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQzMjUyNTcsIm5iZiI6MTcxNDMyNDk1NywicGF0aCI6Ii8xMjQ1ODUxODEvMzI2MjY0NTA4LTZhYzk1NjVhLTg3OWEtNGM1YS1iNDlhLTAxZjk4NWNmNzQ3NS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDI4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQyOFQxNzIyMzdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1hN2RlZmNkOGE1OGI0YWRlNDc3YzBiYWEyYmNjMDQ1NGY3Mzk4ZTk3YWI3MGU3NjhmNjBhMDQ4YzJiNTk1NTk2JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.W4xSEvE3SnFN8n1L-dfltI3hpfsJL0JRz6WfcF8Aca8)

Нозология - выбор выпадающий список.
Диагноз - поле для заполнения.

**Comment by DoomHunter190** [comment]
> > Так же добавляем как числовой статус ?
> > ![Image](https://private-user-images.githubusercontent.com/124585181/326264492-e21d959d-9520-410c-a908-2b784cbb8916.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQzMjUyNTcsIm5iZiI6MTcxNDMyNDk1NywicGF0aCI6Ii8xMjQ1ODUxODEvMzI2MjY0NDkyLWUyMWQ5NTlkLTk1MjAtNDEwYy1hOTA4LTJiNzg0Y2JiODkxNi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDI4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQyOFQxNzIyMzdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT00YmY0MDE0OWQxM2RjN2FiMGVhMDdlM2RiMzQzMTk4Nzg4MTkxYTcxNTM4ZDgwMDgzMGM4M2JmOWZmNzkxNTQ4JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.u_v4esod9CmSZXqKAVx_4Az7dOw2bAvJx4tuPj7_n1g)
> > ![Image](https://private-user-images.githubusercontent.com/124585181/326264508-6ac9565a-879a-4c5a-b49a-01f985cf7475.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQzMjUyNTcsIm5iZiI6MTcxNDMyNDk1NywicGF0aCI6Ii8xMjQ1ODUxODEvMzI2MjY0NTA4LTZhYzk1NjVhLTg3OWEtNGM1YS1iNDlhLTAxZjk4NWNmNzQ3NS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDI4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQyOFQxNzIyMzdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1hN2RlZmNkOGE1OGI0YWRlNDc3YzBiYWEyYmNjMDQ1NGY3Mzk4ZTk3YWI3MGU3NjhmNjBhMDQ4YzJiNTk1NTk2JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.W4xSEvE3SnFN8n1L-dfltI3hpfsJL0JRz6WfcF8Aca8)
> 
> Нозология - выбор выпадающий список. Диагноз - поле для заполнения.

@KonstantinRaikhert Я же могу модели Player добавить новые поля ? Чтобы привязать нозологию и заболевание к игроку

**Comment by KonstantinRaikhert** [comment]
> > > Так же добавляем как числовой статус ?
> 
> > > ![Image](https://private-user-images.githubusercontent.com/124585181/326264492-e21d959d-9520-410c-a908-2b784cbb8916.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQzMjUyNTcsIm5iZiI6MTcxNDMyNDk1NywicGF0aCI6Ii8xMjQ1ODUxODEvMzI2MjY0NDkyLWUyMWQ5NTlkLTk1MjAtNDEwYy1hOTA4LTJiNzg0Y2JiODkxNi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDI4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQyOFQxNzIyMzdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT00YmY0MDE0OWQxM2RjN2FiMGVhMDdlM2RiMzQzMTk4Nzg4MTkxYTcxNTM4ZDgwMDgzMGM4M2JmOWZmNzkxNTQ4JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.u_v4esod9CmSZXqKAVx_4Az7dOw2bAvJx4tuPj7_n1g)
> 
> > > ![Image](https://private-user-images.githubusercontent.com/124585181/326264508-6ac9565a-879a-4c5a-b49a-01f985cf7475.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQzMjUyNTcsIm5iZiI6MTcxNDMyNDk1NywicGF0aCI6Ii8xMjQ1ODUxODEvMzI2MjY0NTA4LTZhYzk1NjVhLTg3OWEtNGM1YS1iNDlhLTAxZjk4NWNmNzQ3NS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDI4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQyOFQxNzIyMzdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1hN2RlZmNkOGE1OGI0YWRlNDc3YzBiYWEyYmNjMDQ1NGY3Mzk4ZTk3YWI3MGU3NjhmNjBhMDQ4YzJiNTk1NTk2JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.W4xSEvE3SnFN8n1L-dfltI3hpfsJL0JRz6WfcF8Aca8)
> 
> > 
> 
> > Нозология - выбор выпадающий список. Диагноз - поле для заполнения.
> 
> 
> 
> @KonstantinRaikhert Я же могу в модели Player добавить новые поля ? Чтобы привязать нозологию и заболевание к игроку 

Да, если это целесообразно. Но возможно тут нужно изменить поле? Так как заболевание в принципе уже было привязано. Какую связь тебе нужно реализовать?

**Comment by DoomHunter190** [comment]
> > > > Так же добавляем как числовой статус ?
> > 
> > 
> > > > ![Image](https://private-user-images.githubusercontent.com/124585181/326264492-e21d959d-9520-410c-a908-2b784cbb8916.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQzMjUyNTcsIm5iZiI6MTcxNDMyNDk1NywicGF0aCI6Ii8xMjQ1ODUxODEvMzI2MjY0NDkyLWUyMWQ5NTlkLTk1MjAtNDEwYy1hOTA4LTJiNzg0Y2JiODkxNi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDI4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQyOFQxNzIyMzdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT00YmY0MDE0OWQxM2RjN2FiMGVhMDdlM2RiMzQzMTk4Nzg4MTkxYTcxNTM4ZDgwMDgzMGM4M2JmOWZmNzkxNTQ4JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.u_v4esod9CmSZXqKAVx_4Az7dOw2bAvJx4tuPj7_n1g)
> > 
> > 
> > > > ![Image](https://private-user-images.githubusercontent.com/124585181/326264508-6ac9565a-879a-4c5a-b49a-01f985cf7475.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQzMjUyNTcsIm5iZiI6MTcxNDMyNDk1NywicGF0aCI6Ii8xMjQ1ODUxODEvMzI2MjY0NTA4LTZhYzk1NjVhLTg3OWEtNGM1YS1iNDlhLTAxZjk4NWNmNzQ3NS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDI4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQyOFQxNzIyMzdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1hN2RlZmNkOGE1OGI0YWRlNDc3YzBiYWEyYmNjMDQ1NGY3Mzk4ZTk3YWI3MGU3NjhmNjBhMDQ4YzJiNTk1NTk2JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.W4xSEvE3SnFN8n1L-dfltI3hpfsJL0JRz6WfcF8Aca8)
> > 
> > 
> > > 
> > 
> > 
> > > Нозология - выбор выпадающий список. Диагноз - поле для заполнения.
> > 
> > 
> > [@KonstantinRaikhert](https://github.com/KonstantinRaikhert) Я же могу в модели Player добавить новые поля ? Чтобы привязать нозологию и заболевание к игроку
> 
> Да, если это целесообразно. Но возможно тут нужно изменить поле? Так как заболевание в принципе уже было привязано. Какую связь тебе нужно реализовать?

Ничего не нужно делать с моделью Player, немного ступил))) Вот так будет выглядеть "Профиль игрока"
Пойдет ?


![Image](https://github.com/Studio-Yandex-Practicum/adaptive_hockey_federation/assets/124585181/230001b1-8a56-48d0-a876-ba12a2a5f03e)

Сегодня постараюсь добить форму для редактирование. Сделаю ПР и сможем разбить задачку на 2 подзадачи для выгрузки и для заполнение данными.

**Comment by DoomHunter190** [comment]
@KonstantinRaikhert А нам вообще нужно делать возможность редактирования "Нозологии" и "Заболевания" ? Просто сейчас пользователь сможет выбрать "Диагноз", а "Нозология" и "Заболевание" сама подставиться по выбранному диагнозу 


![Image](https://github.com/Studio-Yandex-Practicum/adaptive_hockey_federation/assets/124585181/b9fdd8f7-c5a4-4685-a1b6-7867b56a176d)

**Comment by KonstantinRaikhert** [comment]
@DoomHunter190 Как в итоге? Справляешься?)

**Comment by DoomHunter190** [comment]
> @DoomHunter190 Как в итоге? Справляешься?)
Не все так просто, как казалось))
Сделал кастомку для двух полей нозологии и диагноза. Нозологию можно выбрать, диагноз можно ввести, тут все просто. У меня сейчас тупик в плане создания нового диагноза, там логика такая: Мы берем пару болезни и нозологии, проверяем есть ли такая пара в БД, если нет, то создаем новую запись и возвращаем ключ диагноза для дальнейшей валидации (возвращаем диагноз, т.к. у нас в модели только поле диагноза, чтобы его привязать к игроку). За тык в том, что мне нужно передать из поля нозологии id в кастомный класс. 
![image](https://github.com/Studio-Yandex-Practicum/adaptive_hockey_federation/assets/124585181/d1a42841-52ee-404c-8b0a-5d0085cc7c77)
![image](https://github.com/Studio-Yandex-Practicum/adaptive_hockey_federation/assets/124585181/8f6a4e4a-e325-4d3a-b1dd-111fdfd5e144)

**Comment by KonstantinRaikhert** [comment]
> > @DoomHunter190 Как в итоге? Справляешься?)
> > Не все так просто, как казалось))
> > Сделал кастомку для двух полей нозологии и диагноза. Нозологию можно выбрать, диагноз можно ввести, тут все просто. У меня сейчас тупик в плане создания нового диагноза, там логика такая: Мы берем пару болезни и нозологии, проверяем есть ли такая пара в БД, если нет, то создаем новую запись и возвращаем ключ диагноза для дальнейшей валидации (возвращаем диагноз, т.к. у нас в модели только поле диагноза, чтобы его привязать к игроку). За тык в том, что мне нужно передать из поля нозологии id в кастомный класс.
> > ![image](https://private-user-images.githubusercontent.com/124585181/327316365-d1a42841-52ee-404c-8b0a-5d0085cc7c77.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQ2MzA0NTUsIm5iZiI6MTcxNDYzMDE1NSwicGF0aCI6Ii8xMjQ1ODUxODEvMzI3MzE2MzY1LWQxYTQyODQxLTUyZWUtNDA0Yy04YjBhLTVkMDA4NWNjN2M3Ny5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTAyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUwMlQwNjA5MTVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1iYmFkY2M3MTFkYjU1ZTczMzI3ZWE5MDg2MTZmY2Q1Yjk3MjcyMzI5MWVmODVkNjk4MzZjODk4YTBjYzQwMzQ1JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.ZKOZZCsKo7R_Eu1dQYIV9P7dprYAjvUw3xVX1JHe2Qo)
> > ![image](https://private-user-images.githubusercontent.com/124585181/327316488-8f6a4e4a-e325-4d3a-b1dd-111fdfd5e144.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQ2MzA0NTUsIm5iZiI6MTcxNDYzMDE1NSwicGF0aCI6Ii8xMjQ1ODUxODEvMzI3MzE2NDg4LThmNmE0ZTRhLWUzMjUtNGQzYS1iMWRkLTExMWZkZmQ1ZTE0NC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTAyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUwMlQwNjA5MTVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT01NDIzZTA5ZGFlZDFlOWRjZjQ2ZWNmMzg5MTAxMzU3YjRmYjE0OWMwNGRjNWVkOWNmZWEyN2E1ZmRiYmY3NDljJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.C9eTi7a3FC7oD7RLEWS0iEDNJvmDlN84HxbKcGxjorM)

Ага.. давай может драфт ПР? Посмотрю тоже вечерком

**Comment by DoomHunter190** [comment]
> > > @DoomHunter190 Как в итоге? Справляешься?)
> > > Не все так просто, как казалось))
> > > Сделал кастомку для двух полей нозологии и диагноза. Нозологию можно выбрать, диагноз можно ввести, тут все просто. У меня сейчас тупик в плане создания нового диагноза, там логика такая: Мы берем пару болезни и нозологии, проверяем есть ли такая пара в БД, если нет, то создаем новую запись и возвращаем ключ диагноза для дальнейшей валидации (возвращаем диагноз, т.к. у нас в модели только поле диагноза, чтобы его привязать к игроку). За тык в том, что мне нужно передать из поля нозологии id в кастомный класс.
> > > ![image](https://private-user-images.githubusercontent.com/124585181/327316365-d1a42841-52ee-404c-8b0a-5d0085cc7c77.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQ2MzA0NTUsIm5iZiI6MTcxNDYzMDE1NSwicGF0aCI6Ii8xMjQ1ODUxODEvMzI3MzE2MzY1LWQxYTQyODQxLTUyZWUtNDA0Yy04YjBhLTVkMDA4NWNjN2M3Ny5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTAyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUwMlQwNjA5MTVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1iYmFkY2M3MTFkYjU1ZTczMzI3ZWE5MDg2MTZmY2Q1Yjk3MjcyMzI5MWVmODVkNjk4MzZjODk4YTBjYzQwMzQ1JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.ZKOZZCsKo7R_Eu1dQYIV9P7dprYAjvUw3xVX1JHe2Qo)
> > > ![image](https://private-user-images.githubusercontent.com/124585181/327316488-8f6a4e4a-e325-4d3a-b1dd-111fdfd5e144.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQ2MzA0NTUsIm5iZiI6MTcxNDYzMDE1NSwicGF0aCI6Ii8xMjQ1ODUxODEvMzI3MzE2NDg4LThmNmE0ZTRhLWUzMjUtNGQzYS1iMWRkLTExMWZkZmQ1ZTE0NC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTAyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUwMlQwNjA5MTVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT01NDIzZTA5ZGFlZDFlOWRjZjQ2ZWNmMzg5MTAxMzU3YjRmYjE0OWMwNGRjNWVkOWNmZWEyN2E1ZmRiYmY3NDljJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.C9eTi7a3FC7oD7RLEWS0iEDNJvmDlN84HxbKcGxjorM)
> 
> Ага.. давай может драфт ПР? Посмотрю тоже вечерком

Только вечером смогу сделать после 19 по Мск, не проблема ?)
