### ISSUE TITLE
Изменить валидатор на загрузку паспортных данных. Проблема в загрузке реальных данных

### ISSUE THREAD

**Issue by KonstantinRaikhert** [Studio-Yandex-Practicum/adaptive_hockey_federation#360]
# Зачем?

Необходимо доработать валидатор, проблема с загрузкой реальных данных.

# Как нужно делать?

Необходимо поменять регулярное выражение в валидаторе. Главное, чтобы в строке было либо паспорт либо свидетельсво о рождении. Без цифр, может стоят не в начале строке.

# Где?

adaptive_hockey_federation/main/forms.py

def clean_identity_document(self)

**Comment by Eldaar-M** [comment]
Нужно поменять именно само регулярное выражение в функции re.fullmatch() или можно заменить эту функцию на re.search()?
