### ISSUE TITLE
Раздел Аналитика. При фильтрации с  конкретной дисциплиной возникает ошибка.

### ISSUE THREAD

**Issue by AntAresWeb** [Studio-Yandex-Practicum/adaptive_hockey_federation#361]
# Где был обнаружен баг ?

Раздел **Аналитика**
Если выбрать конкретную дисциплину и попробовать отфильтровать, то возникает ошибка.

# Скриншоты

![image](https://github.com/Studio-Yandex-Practicum/adaptive_hockey_federation/assets/80886928/cb38b117-e6ab-4a96-a4e5-d3003fc5c4cb)

![image](https://github.com/Studio-Yandex-Practicum/adaptive_hockey_federation/assets/80886928/8e5fed4d-ef3c-475c-813a-1a630199883c)

# Предложения и предположения как исправить

Нужно исправить.

**Comment by KonstantinRaikhert** [comment]
@AntAresWeb Сам понимаешь куда копать? Или другому отдадим?)

**Comment by KonstantinRaikhert** [comment]
@AntAresWeb Сейчас не вижу, проблему видимо исправили. Закрываю ишью
