### ISSUE TITLE
Подредактировать админку

### ISSUE THREAD

**Issue by KonstantinRaikhert** [Studio-Yandex-Practicum/adaptive_hockey_federation#382]
# Зачем?

Админка в данном проекте - неглавное, но будет оставлена на всякий случай.
Поэтому необходимо подправить отображение (см скрин)

# Как нужно делать?

![2024-05-07_18-43](https://github.com/Studio-Yandex-Practicum/adaptive_hockey_federation/assets/69113745/51509c1a-3080-428e-92b0-a86bdbfaee34)

Касаемо сортировки в БД игроков и команд:
- Игроки
- Команды
- Сотрудники
- Названия дисциплин
- Числовые статусы
- Нозология
- Диагнозы

Документы и сотрудники команды убрать

**Comment by KonstantinRaikhert** [comment]
@ssb000ss Ответь пожалуйста тут, если увидел таску

**Comment by ssb000ss** [comment]
Увидел в разработке.

**Comment by ssb000ss** [comment]
Вопрос по списку, Города оставить либо убрать из админки?

**Comment by KonstantinRaikhert** [comment]
> Вопрос по списку, Города оставить либо убрать из админки?

Города нужно оставить. Это необходимо, если вдруг надо будет удалить какой нибудь город
