### ISSUE TITLE
Добавить пермишены в Выгрузки

### ISSUE THREAD

**Issue by KonstantinRaikhert** [Studio-Yandex-Practicum/adaptive_hockey_federation#383]
# Зачем?

Необходимо добавить возможность скачивания выгрузок только Администраторам (модераторам и представителям команд запрещено)
![2024-05-07_18-51](https://github.com/Studio-Yandex-Practicum/adaptive_hockey_federation/assets/69113745/b889863f-50d8-402b-9cef-e219f9759eb6)

# Как нужно делать?

Необходимо посмотреть как это реализовано, например, в игроках (вьюхи и шаблоны). И повторить.

# Где?

adaptive_hockey_federation/unloads/views.py

**Comment by Eldaar-M** [comment]
@KonstantinRaikhert Привет! Для модераторов и представителей нужно убрать доступ ко всему разделу или только кнопку выгрузки?

![Image](https://github.com/Studio-Yandex-Practicum/adaptive_hockey_federation/assets/118361764/eb3b3a94-f65d-47a6-aa4e-4149df0931a4)

**Comment by KonstantinRaikhert** [comment]
> @KonstantinRaikhert Привет! Для модераторов и представителей нужно убрать доступ ко всему разделу или только кнопку выгрузки?
> 
> ![Image](https://private-user-images.githubusercontent.com/118361764/330405766-eb3b3a94-f65d-47a6-aa4e-4149df0931a4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTU3MDI5OTQsIm5iZiI6MTcxNTcwMjY5NCwicGF0aCI6Ii8xMTgzNjE3NjQvMzMwNDA1NzY2LWViM2IzYTk0LWY2NWQtNDdhNi1hYTRlLTQxNDlkZjA5MzFhNC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTE0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUxNFQxNjA0NTRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1iYjc4MDVjNjZiY2IxZmY5NTlkMmI0ODdkYzAyMzNlNmJjZmNjMTZkMDY4ZWU5MjVmMDIyZmFjYWFiNWRkZmRlJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.SJj4cciACGddp7quNFiGJhWZAVTwUw3nx975OEO_rnI)

Привет! Ко всему разделу. Им в принципе не нужна данная информация. А где-то будет и конфиденциальна
