### ISSUE TITLE
Поправить админ панель для игроков (Django админ)

### ISSUE THREAD

**Issue by KonstantinRaikhert** [Studio-Yandex-Practicum/adaptive_hockey_federation#384]
# Где был обнаружен баг ?

Был обнаружен после добавления Нозологий. 
Вылезает ошибка при редактировании Игрока через панель администраторов.

# Скриншоты

![328903406-7f86d8a4-24dd-45f3-9492-b8b420380c09](https://github.com/Studio-Yandex-Practicum/adaptive_hockey_federation/assets/69113745/54b4aeb3-b1fe-4024-bff2-5e78eb57ce66)

**Comment by DoomHunter190** [comment]
@KonstantinRaikhert бред какой-то, посмотрел все валидаторы полей в форме, ничего лишнего нету, через сайт форму все создается, а вот если делать через админку он выдает ошибку, но создает пару Диагноза и Нозологии, но не игрока....

**Comment by DoomHunter190** [comment]
> @KonstantinRaikhert бред какой-то, посмотрел все валидаторы полей в форме, ничего лишнего нету, через сайт форму все создается, а вот если делать через админку он выдает ошибку, но создает пару Диагноза и Нозологии, но не игрока....

Посмотрел, ветку от 10 Апреля, создание уже не работало....

**Comment by DoomHunter190** [comment]
> > @KonstantinRaikhert бред какой-то, посмотрел все валидаторы полей в форме, ничего лишнего нету, через сайт форму все создается, а вот если делать через админку он выдает ошибку, но создает пару Диагноза и Нозологии, но не игрока....
> 
> Посмотрел, ветку от 10 Апреля, создание уже не работало....

Нашел в чем проблема, связана с полями команды. Пока думаю как ее решить.
