### ISSUE TITLE
Поправить создание/редактирование игрока в админ панель (Django админ)

### ISSUE THREAD

**Issue by DoomHunter190** [Studio-Yandex-Practicum/adaptive_hockey_federation#395]
# Где был обнаружен баг ?
Вылезает ошибка при редактировании Игрока через панель администраторов.

# Скриншоты
![image](https://github.com/Studio-Yandex-Practicum/adaptive_hockey_federation/assets/124585181/5566a69c-2550-4ce3-9921-c9299694fcba)

# Предложения и предположения как исправить
Скорее всего это связано с полями команд в PlayerForm. Думаю стоит смотреть в этом направлении.

**Comment by V1olenceDev** [comment]
_Traceback_ при попытки **создать или обновить** _Игрока_:
[django_debug.log](https://github.com/Studio-Yandex-Practicum/adaptive_hockey_federation/files/15424887/django_debug.log)

**Ключевые ошибки:**
1. _AttributeError: 'User' object has no attribute 'get_short_name';
2. AttributeError: 'DocumentInline' object has no attribute 'insert_after';
3. TypeError: 'DocumentInline' object is not subscriptable;
4. AttributeError: 'dict' object has no attribute 'id_for_label'._

Получилось избавится от 2 и 3 проблемы путем добавления атрибута insert_after.

Прикрепляю второй _Traceback_ после фикса:
[django_debug_2.log](https://github.com/Studio-Yandex-Practicum/adaptive_hockey_federation/files/15425118/django_debug_2.log)

**Оставшиеся ошибки:**
1. _AttributeError: 'User' object has no attribute 'get_short_name';_
2. _AttributeError: 'dict' object has no attribute 'id_for_label'._

Предполагаю что ошибки возникает при попытке разрешить переменные _'get_short_name'_  и _'id_for_label'_ в шаблоне **'admin/custom_change_form.html'**,

**Comment by DoomHunter190** [comment]
@V1olenceDev Привет! Добавь ПР к задаче

**Comment by DoomHunter190** [comment]
@V1olenceDev немного не так)), сделай Pull request. А потом добавь его через шестеренку
![image](https://github.com/Studio-Yandex-Practicum/adaptive_hockey_federation/assets/124585181/0c21ae93-ea93-4cc0-a419-54c4b1777680)
