### ISSUE TITLE
На странице /players/ реализовать фильтр поиска дисциплин по аналогии с полом.

### ISSUE THREAD

**Issue by KonstantinRaikhert** [Studio-Yandex-Practicum/adaptive_hockey_federation#398]
# Зачем?

Эта реализация будет намного удобнее.
![2024-05-23_18-44](https://github.com/Studio-Yandex-Practicum/adaptive_hockey_federation/assets/69113745/ea87d7e3-a796-49ac-8e7d-f617258b7eca)
![2024-05-23_18-44_1](https://github.com/Studio-Yandex-Practicum/adaptive_hockey_federation/assets/69113745/457bb202-87a3-465e-b10f-c6f8c3b2f76d)

# Как нужно делать?

Необходимо разобраться, как работает фильтр по полу (посмотреть на шаблон в хедере и посмотреть какой скрипт за это отвечает). По аналогии повторить

# Где?

adaptive_hockey_federation/templates/base/header.html

**Comment by KonstantinRaikhert** [comment]
@DoomHunter190 Привет! Возьмешь?)

**Comment by DoomHunter190** [comment]
@KonstantinRaikhert Я правильно понимаю, что нам нужно будет брать данные из БД для выпадающего списка поиска? Просто для пола используется предустановленный список 


![Image](https://github.com/Studio-Yandex-Practicum/adaptive_hockey_federation/assets/124585181/43aae67d-257d-4310-b988-e5a60ab6b829)

**Comment by KonstantinRaikhert** [comment]
> @KonstantinRaikhert Я правильно понимаю, что нам нужно будет брать данные из БД для выпадающего списка поиска? Просто для пола используется предустановленный список
> 
> ![Image](https://private-user-images.githubusercontent.com/124585181/333467027-43aae67d-257d-4310-b988-e5a60ab6b829.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTY1MzI4NjUsIm5iZiI6MTcxNjUzMjU2NSwicGF0aCI6Ii8xMjQ1ODUxODEvMzMzNDY3MDI3LTQzYWFlNjdkLTI1N2QtNDMxMC1iOTg4LWU1YTYwYWI2YjgyOS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTI0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUyNFQwNjM2MDVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT04MGFkYmFmMGIxY2FlNzQxZTYxY2Q1Y2ZmNzY1Nzk4ZjhjNmQ4M2NiZWRjMzg3ZDA0MmY3NjA1NzFhNWQ2NWFjJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.DfLqGTDxPslCC0gJQaQ6Nc-lEXVxHtqVy0qL1IBtvxk)

Хм... этот момент я не учел.. Ну получается что да.
Видимо нужно будет делать отдельный урл и вьюху для обработки этого ajax запроса.

**Comment by DoomHunter190** [comment]
> > [@KonstantinRaikhert](https://github.com/KonstantinRaikhert) Я правильно понимаю, что нам нужно будет брать данные из БД для выпадающего списка поиска? Просто для пола используется предустановленный список
> > ![Image](https://private-user-images.githubusercontent.com/124585181/333467027-43aae67d-257d-4310-b988-e5a60ab6b829.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTY1MzI4NjUsIm5iZiI6MTcxNjUzMjU2NSwicGF0aCI6Ii8xMjQ1ODUxODEvMzMzNDY3MDI3LTQzYWFlNjdkLTI1N2QtNDMxMC1iOTg4LWU1YTYwYWI2YjgyOS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTI0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUyNFQwNjM2MDVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT04MGFkYmFmMGIxY2FlNzQxZTYxY2Q1Y2ZmNzY1Nzk4ZjhjNmQ4M2NiZWRjMzg3ZDA0MmY3NjA1NzFhNWQ2NWFjJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.DfLqGTDxPslCC0gJQaQ6Nc-lEXVxHtqVy0qL1IBtvxk)
> 
> Хм... этот момент я не учел.. Ну получается что да. Видимо нужно будет делать отдельный урл и вьюху для обработки этого ajax запроса.

Правильно понимаю, делаем методом dependent dropdown?

**Comment by KonstantinRaikhert** [comment]
> > > [@KonstantinRaikhert](https://github.com/KonstantinRaikhert) Я правильно понимаю, что нам нужно будет брать данные из БД для выпадающего списка поиска? Просто для пола используется предустановленный список
> > > ![Image](https://private-user-images.githubusercontent.com/124585181/333467027-43aae67d-257d-4310-b988-e5a60ab6b829.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTY1MzI4NjUsIm5iZiI6MTcxNjUzMjU2NSwicGF0aCI6Ii8xMjQ1ODUxODEvMzMzNDY3MDI3LTQzYWFlNjdkLTI1N2QtNDMxMC1iOTg4LWU1YTYwYWI2YjgyOS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTI0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUyNFQwNjM2MDVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT04MGFkYmFmMGIxY2FlNzQxZTYxY2Q1Y2ZmNzY1Nzk4ZjhjNmQ4M2NiZWRjMzg3ZDA0MmY3NjA1NzFhNWQ2NWFjJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.DfLqGTDxPslCC0gJQaQ6Nc-lEXVxHtqVy0qL1IBtvxk)
> > 
> > Хм... этот момент я не учел.. Ну получается что да. Видимо нужно будет делать отдельный урл и вьюху для обработки этого ajax запроса.
> 
> Правильно понимаю, делаем методом dependent dropdown? 

Мне кажется да, недавно очень хорошо была реализована тема с выбором числового статуса по дисциплине.

**Comment by DoomHunter190** [comment]
@KonstantinRaikhert Привет, нужна помощь с скриптом. Жесткий выбор я могу сделать, а вот с ajax что-то не выходит. Представления у меня сделано, url прописана. а вот добавление в выпадающий список не получается реализовать. Сможешь посмотреть пожалуйста в search.js ? 
![image](https://github.com/Studio-Yandex-Practicum/adaptive_hockey_federation/assets/124585181/5f99086c-e739-411a-8a46-e0b190e2ac30)

**Comment by DoomHunter190** [comment]
> > [@KonstantinRaikhert](https://github.com/KonstantinRaikhert) Привет, нужна помощь с скриптом. Жесткий выбор я могу сделать, а вот с ajax что-то не выходит. Представления у меня сделано, url прописана. а вот добавление в выпадающий список не получается реализовать. Сможешь посмотреть пожалуйста в search.js ? ![image](https://private-user-images.githubusercontent.com/124585181/334405690-5f99086c-e739-411a-8a46-e0b190e2ac30.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTY5MDQ0NTUsIm5iZiI6MTcxNjkwNDE1NSwicGF0aCI6Ii8xMjQ1ODUxODEvMzM0NDA1NjkwLTVmOTkwODZjLWU3MzktNDExYS04YTQ2LWUwYjE5MGUyYWMzMC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTI4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUyOFQxMzQ5MTVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT01OTI1ZDcwYTIzNjI5YmI1ODc1NjE5OGIyOWEwZGFkNGRhNDZhZThiZGNkMDNmYjRjMTJhYjBhMTJmNGU1YWFkJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.b-hzzd7wFKvoNzPvw0UyheUN8qR2vjEtzaWoY5tBalA)
> 
> Мне кажется ты усложнил... Тут смотрел? https://simpleisbetterthancomplex.com/tutorial/2018/01/29/how-to-implement-dependent-or-chained-dropdown-list-with-django.html

Смотрел, сейчас реализовал по своему чуть
