### ISSUE TITLE
Проверить и реализовать свою ER-диаграмму

### ISSUE THREAD

**Issue by KonstantinRaikhert** [Studio-Yandex-Practicum/adaptive_hockey_federation#40]
# Что нужно описать?

Сейчас есть реализованные некоторые модели джанго. Необходимо по данной ER-диаграмме сверить модели, проверить связи. Так же свериться с макетом в фигме.
Основная мысль - привести документацию в порядок. Утвердить ER-диаграмму, чтобы потом проще было править.

![Image](https://github.com/Studio-Yandex-Practicum/adaptive_hockey_federation/assets/69113745/278dc82c-6012-4011-929a-033b63e6bd6c)

Нужно воспользоваться [сервисом](https://app.diagrams.net/?src=about) для рисования диаграммы и добавить её в репозиторий в папку docs. Не забыть обновить ссылку в readme. (ссылка на pdf или jpg в docs). Так же необходимо положить исходник диаграммы, для редактирования в дальнейшем.

# Где?

docs
README.md

**Comment by wildcat3333** [comment]
Провела сравнительный анализ модели в проекте, figma и ER-диаграммы из задачи:
1. Figma нет отчества у тренера и игроков, в модели и ER есть - нужно или нет? Мое мнение нужно.
2. Документ игрока (паспорт/ свидетельство о рождении) в figma - нет, модели - нет, ER -  есть. В заявках (файлы) есть. - нужно или нет? Мое мнение нужно.
3. В figma для сущности Команды указаны возраст и состав -  что имеется в виду?
4. У игрока может быть несколько диагнозов?
5. Что такое квалификация у игрока, какие бывают? 
6. У одного тренера может быть несколько команд?
7. Вопрос по модели Health (Медицинские показатели) из проекта. В  figma  и ER-диаграмме нет информации об этом
   - отдельно выделена для "хроническая дыхательная недостаточность"  это Класс A1 B1 и др?
   - параметры пересмотр класса  и подтвержден перманентно   - требуется? 
8. ER-диаграмма   User - есть привязка к команде, непонятно что имеется в виду.

Скрины во вложении  

![Image](https://github.com/Studio-Yandex-Practicum/adaptive_hockey_federation/assets/118195627/33a65824-3af6-4363-b210-63635ab57d99)
![Image](https://github.com/Studio-Yandex-Practicum/adaptive_hockey_federation/assets/118195627/694b322b-7ef4-4a9c-9a75-ee54c5b4b550)
![Image](https://github.com/Studio-Yandex-Practicum/adaptive_hockey_federation/assets/118195627/ad17df9c-5219-4161-8f11-dd2d757e689c)
![Image](https://github.com/Studio-Yandex-Practicum/adaptive_hockey_federation/assets/118195627/b5dc734c-c654-44be-a866-950efc55cfb3)
![Image](https://github.com/Studio-Yandex-Practicum/adaptive_hockey_federation/assets/118195627/24d9a540-be72-49d2-bad6-2679e86ac17b)

**Comment by KonstantinRaikhert** [comment]
Хорошая работа! Отвечу на те вопросы, которые понятны и очевидны. т.к. сам тоже пытаюсь во всём разобраться, а встреча с заказчиком только 12 декабря.
1. Я считаю что нужно сделать отчество.
2. Считаю, что нужно. Только необходимо будет реализовывать скрытие данного поля в зависимости от роли пользователя в дальнейшем в проекте.
3. Я думаю это тоже категории, но необходимо задать этот вопрос заказчику - сделаю.
4. Нет. Но тоже уточню на всякий случай.
5. Квалификация, как понимаю, те самые числовые статуты и классы (В1-В5).
6. Думаю что да. Уточним.
7. Это крайние правки заказчика, видимо будет диагноз заполняться из доступных, которые он описал.
8. Вот это меня больше смущает. Неясно, зачем вообще решение делать так. Но users как понимаю это различные администраторы команд, так и администраторы сервиса в целом. 

Мне кажется, сейчас стоит сделать пул реквест и пусть он висит до понедельника. С этими вопросами обратимся к заказчику. А сейчас займёмся дальнейшим причёсыванием проекта.

**Comment by wildcat3333** [comment]
@KonstantinRaikhert доброго дня!)  еще вопросик
Что такое квалификация у ТРЕНЕРА , какие бывают? 



Если что,  Класс - это сущность диагноза, нашла описание в официальной доке  https://paraicehockey.ru/wp-content/uploads/2022/12/sportivnyy-reglament-fah-22.23.pdf



![Image](https://github.com/Studio-Yandex-Practicum/adaptive_hockey_federation/assets/118195627/8b5d829f-565e-4a6d-a6e5-a81f5391b088)

**Comment by wildcat3333** [comment]
Pull requests +
