### ISSUE TITLE
Работа по API. Отправка JSON с данными по игре на сторонний сервер

### ISSUE THREAD

**Issue by KonstantinRaikhert** [Studio-Yandex-Practicum/adaptive_hockey_federation#416]
# Зачем?

Задача немного с ресерчем. Необходимо реализовать функции: сериализатор объекта Game, и собственно функция отправки request c телом запроса с этим json.
Нам предстоит взаимодействовать с FastAPI (примерный сервис DS выложил в пачке) и поэтому необходимо выяснить:
- как мы будем проходить авторизацию (нам нужно ребятам предложить)
- как сейчас будем испытывать (тут предложение поднять сервис DS локально на другом порту)

# Как нужно делать?

Сервис DS необходимо добавить к нам в рабочую среду через gitignore - будем копировать его в папку локально.
Однако в Makefile и всю обвязку подготовить как обычно

# Где?

adaptive_hockey_federation/video_api

**Comment by KonstantinRaikhert** [comment]
@ItsFreez Я тут в пачке скидывал архив сервиса DS, видел?
Если нет, напиши мне пожалуйста в пачку

**Comment by KonstantinRaikhert** [comment]
@ItsFreez Обновил таску - можно приступать)

**Comment by ItsFreez** [comment]
Да, архив я увидел.
Постараюсь приступить в среду.
Во вторник не успеваю(

**Comment by KonstantinRaikhert** [comment]
@SHURSHALO У Игора пока не получается приступить к задаче, сможешь подхватить?
Предлагаю сначала реализовать подъем сервиса DS локально. Там вроде ничего сложного. в FastAPI просто другой порт указать

**Comment by SHURSHALO** [comment]
@KonstantinRaikhert Завтра посмотрю что да как.

**Comment by KonstantinRaikhert** [comment]
@SHURSHALO @ItsFreez Сейчас функционал по совместному старту двух сервисов работает. Ребят, кто в итоге из вас продолжит работу по таске?

**Comment by ItsFreez** [comment]
Я продолжу

**Comment by KonstantinRaikhert** [comment]
@ItsFreez Привет! Есть наработки?

**Comment by ItsFreez** [comment]
@KonstantinRaikhert Закрываем по итогу задачу?
Запуск двух сервисов параллельно решен.
Авторизацию на конференц-звонке решили, будем использовать cors. Нужно только обратную связь от дс-ов получить, что они смогут внедрить у себя и можем быстро для нашего api сделать.

**Comment by KonstantinRaikhert** [comment]
> @KonstantinRaikhert Закрываем по итогу задачу? Запуск двух сервисов параллельно решен. Авторизацию на конференц-звонке решили, будем использовать cors. Нужно только обратную связь от дс-ов получить, что они смогут внедрить у себя и можем быстро для нашего api сделать.

Да, я им отправил сообщение. Эту тогда закрываем
