### ISSUE TITLE
Починить CI/CD стейджа. Что то поломалось, не обновляет.

### ISSUE THREAD

**Issue by KonstantinRaikhert** [Studio-Yandex-Practicum/adaptive_hockey_federation#437]
# Где был обнаружен баг ?

Необходимо зайти на виртуальную машину. проверить в чем дело. Починить.

# Предложения и предположения как исправить

- Сначала нужно посмотреть на ошибки в actions
- Возможно дело в переменных
- Необходимо мне прислать свой public key и я дам доступ
- Прошу еще обратить внимание, что используются daemons линукса для подьема контейнеров

**Comment by KonstantinRaikhert** [comment]
А стейдж то в итоге у тебя по адресу открывался?)
https://jetrai.online/

**Comment by zaritskiiAA** [comment]
Да, конечно. Сейчас проблема в том, что в workflow Build and push Docker image, каждый раз когда он выполняет запрашивается новый сертификат у  Let Encrypt, а у них ограничения 5 сертов на 168 часов, поэтому пока бан.
Попробуй ещё раз в час дня.
![image](https://github.com/Studio-Yandex-Practicum/adaptive_hockey_federation/assets/166800734/9119c021-58b1-41b3-9f9c-35926965e968)
