### ISSUE TITLE
Убрать кнопку "Выгрузить" с выгрузок и поправить отображение команд в аналитике

### ISSUE THREAD

**Issue by KonstantinRaikhert** [Studio-Yandex-Practicum/adaptive_hockey_federation#440]
# Где был обнаружен баг ?

1. убрать кнопку "Выгрузить" - зачем нам выгружать выгрузки))
![2024-06-03_23-13](https://github.com/Studio-Yandex-Practicum/adaptive_hockey_federation/assets/69113745/36610f76-dc2e-47b6-a06d-5228c75e2c1d)
2. Поправить отображение команд в таблице раздела Аналитика
![2024-06-03_23-12](https://github.com/Studio-Yandex-Practicum/adaptive_hockey_federation/assets/69113745/ba09e5f1-7593-491b-9d79-bc384ae9b473)

**Comment by KonstantinRaikhert** [comment]
@V1olenceDev Привет! Получится выполнить таску?

**Comment by Apicqq** [comment]
> [@V1olenceDev](https://github.com/V1olenceDev) Привет! Получится выполнить таску?

Я забрал таску, ПР линканул
