### ISSUE TITLE
Реализовать редактирование номеров игроков

### ISSUE THREAD

**Issue by KonstantinRaikhert** [Studio-Yandex-Practicum/adaptive_hockey_federation#443]
# Зачем?

Нам нужно сделать отдельное представление и ендпоинт на редактирование номеров игроков, прежде чем они улетят к DS.
сущности GamePlayer
![2024-06-05_20-10](https://github.com/Studio-Yandex-Practicum/adaptive_hockey_federation/assets/69113745/42d94f9f-0ca8-4e54-8177-a774f8808306)

# Как нужно делать?

- прикрутить форму редактирования именно номеров, имена не надо.
- ендпоинт должен быть вида edit_numbers/<game_team>/
- редирект должен возвращать на страницу с информацией (на скрине)

# Где?

adaptive_hockey_federation/games

**Comment by KonstantinRaikhert** [comment]
@Milkyaway13 Привет! Как дела с задачей?

**Comment by Milkyaway13** [comment]
@KonstantinRaikhert привет!
Как раз хотел писать
Я сегодня в ночи наконец-то разобрался до конца с редактированием, все работает и через админку, и через сайт. Единственный вопрос у меня по пермишенам, у нас для приложения games их ещё вообще нет, я так понимаю? Кто может редактировать номера, только суперюзер или админы тоже?
