### ISSUE TITLE
Проблема заполнения реальными данными

### ISSUE THREAD

**Issue by KonstantinRaikhert** [Studio-Yandex-Practicum/adaptive_hockey_federation#446]
# Где был обнаружен баг ?

При заполнении реальными данными (fill-db), у нас есть ошибки, видимо какие то поля в фикстурах не заполнены. Придумать как решить проблему..

# Скриншоты

![2024-06-06_19-01](https://github.com/Studio-Yandex-Practicum/adaptive_hockey_federation/assets/69113745/f959a672-aa32-48a0-a0f7-053e1392e886)
![2024-06-06_19-02](https://github.com/Studio-Yandex-Practicum/adaptive_hockey_federation/assets/69113745/96e68ecd-a934-4be3-b214-27d000cfaea7)

# Предложения и предположения как исправить

посмотреть фикстуры реальных данных. Может неправильно что то заполняется

**Comment by KonstantinRaikhert** [comment]
@Nikita527 Привет! Возьмешь?

**Comment by Nikita527** [comment]
@KonstantinRaikhert привет, разберусь 👌
