### ISSUE TITLE
Реализация одинаковых id для GameTeam и Team, GamePlayer и Player.

### ISSUE THREAD

**Issue by KonstantinRaikhert** [Studio-Yandex-Practicum/adaptive_hockey_federation#449]
# Зачем?

Для отправки данных и простоты нам необходимо чтобы ID данных сущностей совпадали. Создаются объекты при создании игры:
_adaptive_hockey_federation/games/signals.py_
![2024-06-11_16-11](https://github.com/Studio-Yandex-Practicum/adaptive_hockey_federation/assets/69113745/d32f5102-dfc1-461d-bb71-ceaa92b10ff7)

Для справки пример json, который будем отправлять к DS
```
{
"game_id": 0,
"game_link":  "https://disk.yandex.ru/i/JLh__1IbAfmK-Q",
"token": "y0_AgAAAAA8cbR4AAtjkQAAAAD9CA6QAAA7HIEFePpA7qKzGdujIAwVc_JH9w", "player_ids": [100, 200, 300, 400], "player_numbers": [1, 2, 3, 4],
"team_ids": [21, 22]
}
```

# Как нужно делать?

Обязательно провести проверку, что у нас сохраняется правильно. Еще предусмотреть возможности дубликатов.

# Где?

adaptive_hockey_federation/games/signals.py

**Comment by KonstantinRaikhert** [comment]
@Apicqq Привет! Возьмешь?

**Comment by Apicqq** [comment]
> @Apicqq Привет! Возьмешь?

Привет! Да, заберу, сегодня приступлю чуть позже
