### ISSUE TITLE
Добавить pytest в проект и сделать отдельный конфиг джанго для тестов

### ISSUE THREAD

**Issue by KonstantinRaikhert** [Studio-Yandex-Practicum/adaptive_hockey_federation#45]
# Зачем?

Юнит тестирование очень полезная штука, добавим в проект. Сейчас необходимо настроить pytest-django

# Как нужно делать?

Нужно немного поменять структуру приложения, чтобы появилась папка config и там лежали отдельные settings на dev test и возможно prod.
Вижу структуру так:

```
adaptive_hockey_federation
├── core (бывш adaptive_hockey_federation)
    ├── config
        ├── base_settings.py
        ├── dev_settings.py
        ├── prod_settings.py
        └── test_settings.py
    ├── asgi.py
    ├── wsgi.py
    ├── urls.py
├── parser
    ├── user_card.py (core папка в которой он лежит упраздняется)
    ├── docx_parser.py
    ├── ...
...
```
Остальное оставляем без изменений, но главное чтобы приложение джанго работало и в парсерах поменять пути до user_card.py

# Где?

adaptive_hockey_federation

**Comment by KonstantinRaikhert** [comment]
@nrthbnd Работа продвигается? Если плохо со временем или какая то сложность, то лучше заранее сообщить

**Comment by nrthbnd** [comment]
@KonstantinRaikhert сейчас добавлю результат вчерашней работы, далее есть вопросы

**Comment by nrthbnd** [comment]
@KonstantinRaikhert 
https://github.com/Studio-Yandex-Practicum/adaptive_hockey_federation/pull/55
