### ISSUE TITLE
Реализация запроса видео на распознавание

### ISSUE THREAD

**Issue by KonstantinRaikhert** [Studio-Yandex-Practicum/adaptive_hockey_federation#450]
# Зачем?

Есть ответ от датасайентистов, поэтому можем приступить к этому.
![2024-06-11_16-25](https://github.com/Studio-Yandex-Practicum/adaptive_hockey_federation/assets/69113745/3eeccad2-12ef-4fa4-933d-9b272d1eb9ba)

# Как нужно делать?

Нам нужно:
- производить POST запрос в виде JSON на адрес _http://0.0.0.0:8010/process_. вместо локалхоста можно добавить env переменную, так как их сервис будет жить на другом IP
- на примере JSON запроса необходимо составить наше тело запроса:
```
{
"game_id": 0,
"game_link":  "https://disk.yandex.ru/i/JLh__1IbAfmK-Q",
"token": "y0_AgAAAAA8cbR4AAtjkQAAAAD9CA6QAAA7HIEFePpA7qKzGdujIAwVc_JH9w", "player_ids": [100, 200, 300, 400], "player_numbers": [1, 2, 3, 4],
"team_ids": [21, 22]
}
```
player_ids - GamePlayer, team_ids - GameTeam
- как запускается сервис DS у нас можно прочитать в readme (запускается параллельно)

# Где?

adaptive_hockey_federation/video_api

**Comment by KonstantinRaikhert** [comment]
@SHURSHALO Приветствую! Есть возможность выполнить?)

**Comment by SHURSHALO** [comment]
Да, попробую выполнить в ближайшее время
