### ISSUE TITLE
Поправить шаблон отображения игр и отрефакторить поиск

### ISSUE THREAD

**Issue by KonstantinRaikhert** [Studio-Yandex-Practicum/adaptive_hockey_federation#457]
# Где был обнаружен баг ?

Нам нужно добавить иконки отображения редактирования и удаления. Иначе сейчас смотрится криво.
Еще нужно реализовать поиск по играм. Ссылку убрать, а команда оставить одну. Но проводить поиск по обеим командам

# Скриншоты

![2024-06-13_19-37](https://github.com/Studio-Yandex-Practicum/adaptive_hockey_federation/assets/69113745/fe7cb796-145c-4f78-b64b-72262501b02f)

![2024-06-13_19-38](https://github.com/Studio-Yandex-Practicum/adaptive_hockey_federation/assets/69113745/fbfa9c43-b3dc-45ef-b4dc-42c77294c988)

**Comment by ItsFreez** [comment]
@KonstantinRaikhert Иконки редактирования и удаления я добавил. Поиск по ссылке на видео убрал. Вот с поиском по командам запутался. Где находится форма поиска по этим колонкам? Или она дефолтная джанговская?
