### ISSUE TITLE
Сделать страницу с играми, в которых учавствует игрок

### ISSUE THREAD

**Issue by KonstantinRaikhert** [Studio-Yandex-Practicum/adaptive_hockey_federation#462]
# Зачем?

В рамках этой таски предлагаю поправить таблицу игроков (почему то поплыла)
![2024-06-17_19-07](https://github.com/Studio-Yandex-Practicum/adaptive_hockey_federation/assets/69113745/1021d4fb-a960-4a6c-baae-989d73f80e4d)

И основное: необходимо сделать шаблон с играми, в которых участвует игрок. Тут необходимо получать все игры с участием игрока по gameplayer_id
![2024-06-17_19-08](https://github.com/Studio-Yandex-Practicum/adaptive_hockey_federation/assets/69113745/85ba99e2-f8a8-464a-b426-6d37d7a655da)
![2024-06-17_19-08_1](https://github.com/Studio-Yandex-Practicum/adaptive_hockey_federation/assets/69113745/511afb23-8794-4b08-a4f1-6005b860d4e3)

# Как нужно делать?

Если необходимо для рендеринга - то можно реализовать фабрики для игр.

**Comment by KonstantinRaikhert** [comment]
@DoomHunter190 Привет!) Ты еще в деле?))

**Comment by DoomHunter190** [comment]
> @DoomHunter190 Привет!) Ты еще в деле?))

Привет, да. Реализуем

**Comment by KonstantinRaikhert** [comment]
> > @DoomHunter190 Привет!) Ты еще в деле?))
> 
> Привет, да. Реализуем

Отлично! Спасибо)
