### ISSUE TITLE
Ресерч на тему взаимодействия нашего сервиса с API яндекс диска и общего взаимодействия с DS

### ISSUE THREAD

**Issue by KonstantinRaikhert** [Studio-Yandex-Practicum/adaptive_hockey_federation#467]
# Зачем?

Общее взаимодействие примерно понятно. Но было бы круто, если мы реализуем схему (BPMN например) взаимодействия, чтобы структурировать некоторые кейсы.

Важная особенность - хранение всех видео на диске

# Как нужно делать?

Наверно нам тоже нужно будет подключать в проект данную библиотеку
https://yadisk.readthedocs.io/ru/latest/api_reference/sync_api.html

# Где?

docs

**Comment by zaritskiiAA** [comment]
![diagram (2)](https://github.com/Studio-Yandex-Practicum/adaptive_hockey_federation/assets/166800734/585428c9-1395-4010-927d-af2c3c215f2c)

**Comment by zaritskiiAA** [comment]
пока вижу так, что думаешь? Добавил логику со стороны менеджеров тоже, что бы особо нужные видео ставились в приоритет. если в момент когда видео нужно они не ждали пока обработаются все видео, а поставили нужное в начало очереди.
На стороне дс-ов, я отметил, хотелось бы что бы они на своей стороне тоже использовали брокер сообщений, так бы было удобнее.

**Comment by zaritskiiAA** [comment]
щас начну вникать конкретно по технологиям

**Comment by KonstantinRaikhert** [comment]
Принято решение подключить брокеры и воркеры
