### ISSUE TITLE
Поправить разметку в джанго шаблоне (детали игры)

### ISSUE THREAD

**Issue by KonstantinRaikhert** [Studio-Yandex-Practicum/adaptive_hockey_federation#479]
# Где был обнаружен баг ?

Съехала кнопка, необходимо поправить в шаблоне теги html. Кнопка должна быть в середине внизу.
Путь к шаблону - /adaptive_hockey_federation/templates/main/games/game_detail.html

# Скриншоты

![2024-06-27_19-46](https://github.com/Studio-Yandex-Practicum/adaptive_hockey_federation/assets/69113745/86f97d01-9e95-460c-9227-1b5b35558cf5)

# Предложения и предположения как исправить

кажется вот этот блок нужно поместить в общий div

![2024-06-27_19-49](https://github.com/Studio-Yandex-Practicum/adaptive_hockey_federation/assets/69113745/5606e14d-7d1a-48d2-a409-ee6a44ab96ad)

**Comment by KonstantinRaikhert** [comment]
@ffff00-korj Привет! Планируешь таску сделать?)

**Comment by ffff00-korj** [comment]
@KonstantinRaikhert Привет! Да, на выходных разберусь

**Comment by ffff00-korj** [comment]
@KonstantinRaikhert Готово, кнопка впорядке)
