### ISSUE TITLE
Добавить связь с игрой в GameDataPlayer

### ISSUE THREAD

**Issue by KonstantinRaikhert** [Studio-Yandex-Practicum/adaptive_hockey_federation#487]
# Где был обнаружен баг ?

*Описание места и возможных причин бага.*

# Скриншоты

*Сюда добавить возможные скрины с описанием.*

# Предложения и предположения как исправить

*Возможные догадки, как исправить.*

**Comment by zaritskiiAA** [comment]
возьму себе ишус, как раз поправлю часть моковой фичи которая завязана на этой модели
