### ISSUE TITLE
Убрать костыль из stage_deploy.yaml

### ISSUE THREAD

**Issue by zaritskiiAA** [Studio-Yandex-Practicum/adaptive_hockey_federation#488]
# Где был обнаружен баг ?
![image](https://github.com/Studio-Yandex-Practicum/adaptive_hockey_federation/assets/166800734/30dbd39f-e639-4d74-b74f-511bf9e2a1dc)

*Описание места и возможных причин бага.*
stage_deploy,yaml
# Скриншоты
![image](https://github.com/Studio-Yandex-Practicum/adaptive_hockey_federation/assets/166800734/b73e3d67-8680-4749-bfa2-68c14dc9ee44)

# Предложения и предположения как исправить
Сейчас скрипт просто спит минуту, пока  демон adaptive_hockey_deferation.service запускается и выполняет команды прописанные в нём. Этот костыль надо убрать, т.к. никогда точно неизвестно сколько времени ему нужно что бы выполнить все процедуры в том числе разворачивание докер контейнеров.
*Возможные догадки, как исправить.*
Нужно написать небольшой скрипт на bash, который будет проверять статус демона или любая другая внятная альтернатива обычному sleep.

Так же неплохо было бы зайти на сервер и посмотреть, что там происходит. Потому что врядле при текущем сервисе демону требуется больше 60 секунд, может быть, что по каким-то причинам контейнеры не пересобираются.

**Comment by KonstantinRaikhert** [comment]
@trippiez Напиши мне в личку свой public key, дам доступ и инструкции
