### ISSUE TITLE
Создать джанго команду для фабрики фикстур и подключить к makefile

### ISSUE THREAD

**Issue by zaritskiiAA** [Studio-Yandex-Practicum/adaptive_hockey_federation#490]
# Зачем?
В мр-е #483 была добавлена фабрика для JSON player data. Нужно сначала добавить команду в django commands fill-test-db для вызова нового функционала, затем добавить команду в makefile к группе fill-test-db

# Как нужно делать?

*Как мы выполняем реализацию данной задачи, какие действия нужны для достижения цели.*

# Где?
core/managment/commands/fill-test-db.py и makefile

![image](https://github.com/Studio-Yandex-Practicum/adaptive_hockey_federation/assets/166800734/249826e4-d1da-4623-8365-ba64fafd1bc0)

**Comment by KonstantinRaikhert** [comment]
@posredn1k Возможно необходимо добавить сразу ссылку на видео готовую, у нас есть пример на яндекс диск. Нужно, чтобы проверять отработку функционала. А вот уже фреймы в самом JSON пусть будут рандомны

**Comment by posredn1k** [comment]
> @posredn1k Возможно необходимо добавить сразу ссылку на видео готовую, у нас есть пример на яндекс диск. Нужно, чтобы проверять отработку функционала. А вот уже фреймы в самом JSON пусть будут рандомны

Ты имеешь ввиду ссылку оставить одну и ту же на яндекс диск в поле game_link, а номер игрока и фреймы генерить?

**Comment by KonstantinRaikhert** [comment]
> > @posredn1k Возможно необходимо добавить сразу ссылку на видео готовую, у нас есть пример на яндекс диск. Нужно, чтобы проверять отработку функционала. А вот уже фреймы в самом JSON пусть будут рандомны
> 
> Ты имеешь ввиду ссылку оставить одну и ту же на яндекс диск в поле game_link, а номер игрока и фреймы генерить?

Да, думаю как раз для того, чтобы работать с готовым видео и получать на нашей стороне склейку.
Позже будем думать, как подключать яндекс диск. На бесплатном аккаунте большое видео не загрузишь, а апишку нужно прикрутить
