### ISSUE TITLE
Реализовать логику работы кнопки "Видео игр с игроком" в профиле игрока

### ISSUE THREAD

**Issue by zaritskiiAA** [Studio-Yandex-Practicum/adaptive_hockey_federation#491]
# Зачем?
Сейчас, в профиле каждого игрока есть статическая кнопка "Видео игр с игроком", если игрок не участвует ни в одной игре то ему вернется 404 ошибка.
![image](https://github.com/Studio-Yandex-Practicum/adaptive_hockey_federation/assets/166800734/42253d1a-fec5-4397-b7b1-549163ef24d6)
![image](https://github.com/Studio-Yandex-Practicum/adaptive_hockey_federation/assets/166800734/37b8485b-d3b8-4476-bcc0-4c6934f7c876)

# Как нужно делать?
Наверное, хорошей практикой будет, сделать кнопку динамической - если игры есть отображать. если нет  - не отображать.
Просто путь - если игр нет рендерить ответ, что игр с участием игрока нет.

# Где?
представления игрока main/controllers/player_views.py.
шаблон main/player_id/player_id.html - со страницей игрока
шаблон main/player_id/player_id_video_games.html - при нажатие на кнопку

**Comment by zaritskiiAA** [comment]
@PavelNep1996 когда будешь работать с таской, в представлении player_views.PlayerGamesVideo прочитай TODO, там фильтрация кварисетов  сейчас используется по неуникальным атрибутам. Исправь, пожалуйста, на id, что бы не открывался ишус ради этого микро-момента.

**Comment by PavelNep1996** [comment]
@zaritskiiAA, добавил функционал динамической кнопки и доработал фильтрацию кварисетов по id
