### ISSUE TITLE
Записать скринкаст по запуску celery и добавления воркеров.

### ISSUE THREAD

**Issue by KonstantinRaikhert** [Studio-Yandex-Practicum/adaptive_hockey_federation#494]
# Зачем?

Будет очень удобно разобраться другим разработчикам.

**Comment by zaritskiiAA** [comment]
@KonstantinRaikhert  https://disk.yandex.ru/i/H8Q2J4bTeAM6dA

ну, блогер из меня такой себе получился. За звук сори, у меня динамик в вебке.
