### ISSUE TITLE
Пофиксить конфликт миграций в Main

### ISSUE THREAD

**Issue by zaritskiiAA** [Studio-Yandex-Practicum/adaptive_hockey_federation#495]
# Где был обнаружен баг ?
main app
*Описание места и возможных причин бага.*
migrations
# Скриншоты
![image](https://github.com/Studio-Yandex-Practicum/adaptive_hockey_federation/assets/166800734/bcd4628b-1150-4067-a5ef-06ef028cb030)

**Comment by KonstantinRaikhert** [comment]
@zaritskiiAA Пофиксил
