### ISSUE TITLE
Проблема редактирования диагнозов игроков

### ISSUE THREAD

**Issue by KonstantinRaikhert** [Studio-Yandex-Practicum/adaptive_hockey_federation#504]
# Где был обнаружен баг ?

При заполнении реальными данными `fill-db` возникает следующая ошибка в диагнозах:

дублирование созданного диагноза

# Скриншоты

![2024-07-25_14-51](https://github.com/user-attachments/assets/5f1b1804-7ecd-4d2d-b55d-5109460d6ff1)
![2024-07-25_14-51_1](https://github.com/user-attachments/assets/8c9bb82c-a868-4bdb-857b-07edb3dc1071)

# Предложения и предположения как исправить

Нам нужно, чтобы либо создавался новый диагноз, либо искался старый и выбирался. Так же необходимо учесть вопрос с нижним и верхним регистром

**Comment by KonstantinRaikhert** [comment]
@AlexanderKhasanov Возьми пожалуйста эту таску

**Comment by AlexanderKhasanov** [comment]
Ошибка заключалась не в функционале сохранения диагнозов. Проблема была только при заполнении БД реальными данными. В коде создавались экземпляры с id, которые не сдвигали внутренний pk таблиц. Был добавлен код, который после заполнения БД реальными данными устанавливает внутренний pk таблицы равным max_id(максимальный id, который использовался при заполнении) + 1
Pull Request - https://github.com/Studio-Yandex-Practicum/adaptive_hockey_federation/pull/538
