### ISSUE TITLE
Реализовать smkoe tests для Analytics, Games, Staffs.

### ISSUE THREAD

**Issue by KonstantinRaikhert** [Studio-Yandex-Practicum/adaptive_hockey_federation#516]
# Зачем?

Приводим в порядок тесты, согласно проведенной ревизии

# Как нужно делать?

Написать тесты согласно имеющимся (так же с ролями).
Если есть вопросы, касаемы пермишенов, прошу написать в пачке.

# Где?

adaptive_hockey_federation/tests/url_test.py

**Comment by KonstantinRaikhert** [comment]
@Milkyaway13 Готов взять в работу?)

**Comment by Milkyaway13** [comment]
> @Milkyaway13 Готов взять в работу?)

Да, конечно)
В пачку буду писать по мере поступления вопросов)
