### ISSUE TITLE
Переработать модель User.

### ISSUE THREAD

**Issue by KonstantinRaikhert** [Studio-Yandex-Practicum/adaptive_hockey_federation#52]
# Зачем?

Есть несколько недочётов в модели, которые необходимо устранить сейчас.

# Как нужно делать?

Модель User:
В ролях роль (ROLE_USER, 'Пользователь') лишняя, её необходимо упразднить.
Так же упразднить username (авторизироваться будет по email)
Обязательные поля:
- first_name
- last_name
- role
- email
Необязательные:
- phone (тут сразу продумать валидацию телефона, например [этот](https://django-phonenumber-field.readthedocs.io/en/latest/index.html) пакет. Не забыть указать Российский формат)

Так же проверить наличие полей registration_date, last_login_date.

ДЛЯ РОЛЕЙ:
Указать для каждой роли докстринг, что можеть эта роль.

'Представитель команды' - имеет возможность редактировать данные детей в своей команде,
 просматривать некоторые данные по игрокам в других командах (ФИО, возраст спортивный класс, тип заболевания)
Выгружать формы по своей команде. Загружать сканы справок

 'Модератор' - имеет возможности вносить данные по определенному ребенку, не может добавлять новых пользователей и удалять детей, команды. (Возможно дополнение)

'Администратор' - имеет неограниченные права

# Где?

adaptive_hockey_federation/users

**Comment by IvanFilippov74** [comment]
@KonstantinRaikhert 
В модели User роль 'Пользователь' стоит как дефолтная, после удаления какую необходимо указать по дефолту, я так полагаю что агент?
Про авторизацию по емейлу понял=) получается у всех юзеров логина не будет, обращение к пользователям будет по last_name и first_name?
По докстрингу, не совсем понял как это сделать, просто к переменной добавить докстринг?
Поле last_login_date, дата последнего входа?

**Comment by KonstantinRaikhert** [comment]
@IvanFilippov74 Да, давай агент поставим.
Авторизация по email. В форму естественно вводится email, мне кажется излижне добавлять username. Отображать будет да, по name, surname (ну или как там в абстрактной модели)
Сейчас роли оформлены как property, вот там и можно к функции написать докстринги
Да, их можно унаследовать от AbstractUser джанги, там есть эти поля

**Comment by KonstantinRaikhert** [comment]
@IvanFilippov74 Привет!) Сегодня будет ПР?

**Comment by IvanFilippov74** [comment]
@KonstantinRaikhert Привет!) Если только ночью, с утра точно будет
