### ISSUE TITLE
Возврат от редактирования профиля игрока к списку игроков

### ISSUE THREAD

**Issue by AleksandrPU** [Studio-Yandex-Practicum/adaptive_hockey_federation#524]
# Где был обнаружен баг ?

Долгий возврат от редактирования профиля игрока к списку игроков.

# Скриншоты

После сохранения в форме "Редактирование профиля игрока":
![screenshot21](https://github.com/user-attachments/assets/3e8ddfaa-fc8f-43e5-83db-a5b7bc149e5b)

Открывается форма "Профиль игрока". Если затем нажать кнопку "Назад":
![screenshot31](https://github.com/user-attachments/assets/529bb7ea-1f29-428d-b158-9ba4ea865f37)

То снова откроется форма "Редактирование профиля игрока". Ещё раз "Назад":
![screenshot41](https://github.com/user-attachments/assets/9ff6fde8-4739-46c3-bca9-7aa0ce17ade1)

Откроется форма "Профиль игрока". Ещё раз "Назад":
![screenshot31](https://github.com/user-attachments/assets/529bb7ea-1f29-428d-b158-9ba4ea865f37)

Выход в "Список игроков".

# Предложения и предположения как исправить

Изменить действие кнопки "Назад".

**Comment by KonstantinRaikhert** [comment]
@AleksandrPU Думаю тут уже в баг можно записать, спасибо!

**Comment by KonstantinRaikhert** [comment]
решено
