### ISSUE TITLE
Низкая заметность кнопок в нижнем колонтитуле

### ISSUE THREAD

**Issue by AleksandrPU** [Studio-Yandex-Practicum/adaptive_hockey_federation#525]
# Где был обнаружен баг ?

На страницах в нижнем колонтитуле.

# Скриншоты

![screenshot511](https://github.com/user-attachments/assets/b799e124-c22c-4ca1-97a6-db54693f7f26)

# Предложения и предположения как исправить

Изменить цвет кнопок.

**Comment by KonstantinRaikhert** [comment]
@AleksandrPU Ценное предложение, но т.к. у нас на проекте было 0,25 фронтендера, то сверстали, что смогли))
Если есть желание и время, буду очень благодарен, если поправишь.
