### ISSUE TITLE
Реализовать задание и смену пароля пользователя через email

### ISSUE THREAD

**Issue by KonstantinRaikhert** [Studio-Yandex-Practicum/adaptive_hockey_federation#53]
# Зачем?

Таску можно реализовать только после #52 .

Необходимо создать возможность изменять и задавать пароли через email backend (приходит письмо на почту со ссылкой задания или смены пароля), реализуется action в админке.

# Как нужно делать?

Здесь будет необходимо создать template, который отправляется на почту пользователю с необходимой ссылкой.
Пример реализации можно посмотреть [тут](https://github.com/Studio-Yandex-Practicum/RandomCoffeeBotTelegram/tree/develop/src/admin_user) Внимательно посмотреть на views, urls, utils.

# Где?

adaptive_hockey_federation/users

**Comment by Aleksey-Krd** [comment]
В фигме немного по другому восстановление показано, там нужно ввести код с почты или телефона и далее восстанавливать, я до этого сделал через ссылку на почту, всё работало(стандартные вьюхи джанго) , но удалил потому что не соответствует немного задаче, я так понял нужно реализовать именно через код на почту или телефон

**Comment by KonstantinRaikhert** [comment]
@KonstantinRaikhert Как сказал заказчик, в фигме некоторые моменты некорректны. Я ему предложил восстановление и двухфакторную аутенфикацию через код на почту (только на почту). Пример реализации на другом проекте тоже показал. Там просто приходит письмо с кодом на почту и его вводить в форме на сайте. С восстановлением пароля на почту приходит ссылка на форму по восстановлению. Кстати форму восстановления можно использовать стандартную джанго админ

**Comment by Aleksey-Krd** [comment]
@KonstantinRaikhert так это всё меняет), тогда есть пару вопросов, по поводу того, что мы должны видеть когда нажимаем "забыли пароль", должна открываться форма с единственным полем введите email и кнопочка восстановить пароль? Далее приходит ссылка на почту по ссылке мы попадаем на форму смены пароля, так?

**Comment by KonstantinRaikhert** [comment]
> @KonstantinRaikhert так это всё меняет), тогда есть пару вопросов, по поводу того, что мы должны видеть когда нажимаем "забыли пароль", должна открываться форма с единственным полем введите email и кнопочка восстановить пароль? Далее приходит ссылка на почту по ссылке мы попадаем на форму смены пароля, так?

Да, так)
