### ISSUE TITLE
Убрать celery и Redis с проекта

### ISSUE THREAD

**Issue by KonstantinRaikhert** [Studio-Yandex-Practicum/adaptive_hockey_federation#544]
# Зачем?

Это нам сейчас излишне. Поэтому выпиливаем. Текущую реализацию я сохраню в друго ветке.

# Как нужно делать?

В контейнере Redis, из команды запуска и тд. Проверить на работоспособность сервис. Наследуемся от dev и ПР сюда же.

**Comment by KonstantinRaikhert** [comment]
@OlegGsk Если есть доп вопросы, предлагаю обсудить в пачке

**Comment by OlegGsk** [comment]
ссылка на pull request
https://github.com/Studio-Yandex-Practicum/adaptive_hockey_federation/pull/545
