### ISSUE TITLE
Некорректная работа валидатора даты рождения игроков 

### ISSUE THREAD

**Issue by Toksi86** [Studio-Yandex-Practicum/adaptive_hockey_federation#560]
# Где был обнаружен баг ?
В базе данных существуют игроки, чей возраст меньше, чем нижнее ограничение валидатора. 

# Скриншоты
Например игрок Аверкиев имеет дату рождения 10.05.2006, а минимальная дата валидатора 02.10.2006
![1](https://github.com/user-attachments/assets/5fda8f36-ad62-41f2-a19e-794217781b20)

# Предложения и предположения как исправить

Изменить нижнее ограничение валидатора возраста игроков. Понизить лет на 10-15

**Comment by webn1nja** [comment]
Добрый вечер. Обнаружил странное.
class AgeLimits(IntEnum):
    """Возрастные лимиты."""

    MIN_AGE_PLAYER = 6
    MAX_AGE_PLAYER = 18

Вы пишете: "Изменить нижнее ограничение валидатора возраста игроков. Понизить лет на 10-15![Image](https://github.com/user-attachments/assets/3f3c9c85-7dc6-4d31-88c1-2e3baa5749ea)
![Image](https://github.com/user-attachments/assets/6e384858-d3f7-4de4-9fb0-a0d031a26d44)
"
До какого значения вы бы хотели понизить нижнюю границу?

**Comment by KonstantinRaikhert** [comment]
Так, у нас проблема, что БД имеет сейчас игроков, которым на данный момент уже больше 18 лет. Видимо нужно до 25. А это точно тот валидатор, который используется в данной форме?

**Comment by webn1nja** [comment]
в конечном итоге валидаторы формы хотят класс AgeLimits  из core/constants.py, в котором определены MIN_AGE_PLAYER и MAX_AGE_PLAYER
