### ISSUE TITLE
Заполнение БД реальными данными, ошибка создания представителя команды

### ISSUE THREAD

**Issue by KonstantinRaikhert** [Studio-Yandex-Practicum/adaptive_hockey_federation#572]
# Где был обнаружен баг ?

При помощи команды `export-db` был создан dump файл. Но почему то к каждой команде привязался куратор в лице суперпользователя. Поэтому теперь невозможно создать нового представителя команды, т.к. уже к ней привязан Админ Админ.
Такое же поведение и с командой `fill-db`

# Скриншоты

![2024-10-08_17-16](https://github.com/user-attachments/assets/f3e88a74-b13c-400b-950f-81d85906c152)
![2024-10-08_17-24](https://github.com/user-attachments/assets/ac9c8695-4634-4b0b-b252-fe370f2571af)
![2024-10-08_17-27](https://github.com/user-attachments/assets/2f83b20c-629b-40db-9fbc-15edc902495c)

# Предложения и предположения как исправить

Возможно, необходимо пересмотреть модели Curator  и User. Необходимо выяснить, почему так происходить.
Стоит еще посмотрь в сторону ролей, в форме понятно, почему не отображается Админ А. Но вопрос, почему он присваивается как куратор (представитель команды) по умолчанию.

**Comment by Toksi86** [comment]
При заполнении базы данных командой fill-db используется цикл, где явно указывается, что куратор для каждый команды это пользователь с ID - 1.
                for item in data:
                    if table_name == "main_team":
                        team_data = {
                            "id": item["id"],
                            "name": item["name"],
                            "city_id": item["city_id"],
                            "discipline_name_id": item["discipline_name_id"],
                            "curator_id": 1,
                        }
Поэтому он и представитель команды по умолчанию. Какое поведение должно быть в итоге? 

Почему он не высвечивается в форме еще не разобрался, смотрю.

**Comment by KonstantinRaikhert** [comment]
@Toksi86 Думаю да, нас устроит логика None в поле. Основная проблема была в том, что невозможно создать пользователя с ролью "Представитель команды". Попробуй пожалуйста у себя, т.е. у нас создаётся команда администратором, после мы должнать создать пользователя "представитель команды" И уже на этапе создания его привязывем к команде.

**Comment by Toksi86** [comment]
Да, у меня сейчас всё именно так и работает, чуть позже сделаю пуш и создам PR
