### ISSUE TITLE
Реализация по новой диаграмме моделей.

### ISSUE THREAD

**Issue by KonstantinRaikhert** [Studio-Yandex-Practicum/adaptive_hockey_federation#59]
# Зачем?

Нужно поправить и реализовать модели по ER диаграмме. 

# Как нужно делать?

Привести в порядок все модели, по возможности добавить всё в admin.py

# Где?

adaptive_hockey_federation/main/models.py
adaptive_hockey_federation/main/admin.py

**Comment by KonstantinRaikhert** [comment]
@wildcat3333 Кроме модели User, ага? Разделим чуть чуть.

**Comment by wildcat3333** [comment]
@KonstantinRaikhert  добрый день!
1.  Есть ли список 
 - обязательных полей,  
 - ограничений (например Диганоз-нозология, разные диагнозы нозология одинаковая)
 - по сортировке в админке (пока сделала по наименованию)
2. Вопрос по модели Player поле documents (Document),  объясни, плиз  только когда "пощупала" с данными не поняла,  что должно храниться в модели Document (Модель для загружаемых файлов)
title (str)
file (file)  

Я предполагала, что модель Document должна хранить информацию об игроке и подгруженных по нему документам )

**Comment by wildcat3333** [comment]
@KonstantinRaikhert добрый день!

1. Есть ли список
- обязательных полей,
- ограничений (например Диганоз-нозология, разные диагнозы нозология одинаковая)
- по сортировке в админке (пока сделала по наименованию)
2. Вопрос по модели Player поле documents (Document), объясни, плиз только когда "пощупала" с данными не поняла, что должно храниться в модели Document (Модель для загружаемых файлов)
title (str)
file (file)

Я предполагала, что модель Document должна хранить информацию об игроке и подгруженных по нему документам )

3. Модель Team связь Team --> Player,  а зачем она нам тут, если есть связь Player --> Team

Хех)

**Comment by KonstantinRaikhert** [comment]
> @KonstantinRaikhert добрый день!
> 
> 1. Есть ли список
> 
> * обязательных полей,
> * ограничений (например Диганоз-нозология, разные диагнозы нозология одинаковая)
> * по сортировке в админке (пока сделала по наименованию)
> 
> 2. Вопрос по модели Player поле documents (Document), объясни, плиз только когда "пощупала" с данными не поняла, что должно храниться в модели Document (Модель для загружаемых файлов)
>    title (str)
>    file (file)
> 
> Я предполагала, что модель Document должна хранить информацию об игроке и подгруженных по нему документам )
> 
> 3. Модель Team связь Team --> Player,  а зачем она нам тут, если есть связь Player --> Team
> 
> Хех)

Привет!
1. Попробую составить)
- список обязательный полей предлагаю сформировать. Следующим сообщением.
- ограничений думаю нет. Потому что выбор будет нозологии а диагноз записываться администратором или представтилем команды в поле строкой
- по сортировке пока пусть всё будет по алфавиту. Нам сейчас админка наша нужна для нашего удобства. далее мы там наверно оставим только юзеров...
2. Как сказал заказчик, нужно хранить какие либо сканы документов. Я представляю этот так. Есть например справка медицинская какая либо. И мы привязываем к игроку эту справку. title - название справки, file - непосредственно сам скан, формат пока не важен файла.
3. Это видимо я пропустил)) Давай Player --> Team оставим и все)

**Comment by wildcat3333** [comment]
@KonstantinRaikhert pull request +
