### ISSUE TITLE
Реализовать заполнение игроков по папке resourses

### ISSUE THREAD

**Issue by KonstantinRaikhert** [Studio-Yandex-Practicum/adaptive_hockey_federation#69]
# Зачем?

Сейчас важно сделать хотя бы минимальной работающий вариант. На целостность данных будем проверять потом.
Необходимо использовать legacy парсер. Сейчас он прикручен на команду fill-db. Но команда записывает в txt все данные.
Нам необходимо сразу писать с помощью этой команды в БД

# Как нужно делать?

- необходимо при помощи парсера сделать фикстуру (думаю в json)
- эту фикстуру использовать для заполнения команды fill-db

Очень важно! Не грузить в коммитах данные из таблиц.

# Где?

adaptive_hockey_federation/core/fixtures

**Comment by wildcat3333** [comment]
Привет, вопросы по распарсенным данным вносить исправления сразу?
1.  name парсится фамилия, surname - имя  
2. наименование/порядок полей не соответствует новым



![Image](https://github.com/Studio-Yandex-Practicum/adaptive_hockey_federation/assets/118195627/f3e9cf69-e248-4f9a-9b10-bc78b322d3c9)

**Comment by KonstantinRaikhert** [comment]
@wildcat3333 Привет, как успехи?)

**Comment by wildcat3333** [comment]
Привет!🌺 Импорт уже работает, заберу пг сегодня и перепишу на модели импорт, ветку закоммитила, но пока не пуллила.

**Comment by KonstantinRaikhert** [comment]
Как здорово!👍

**Comment by wildcat3333** [comment]
pull req +
