### ISSUE TITLE
Создание в БД готовых обьектов при помощи фикстур в формате JSON

### ISSUE THREAD

**Issue by KonstantinRaikhert** [Studio-Yandex-Practicum/adaptive_hockey_federation#85]
# Зачем?

Предлагаю разделение между тестовыми данными и готовыми. Поэтому здесь выполняем заполнение БД реальными данными в команде ```python manage.py fill-db```

Все фикстуры предлагаю хранить в JSON, каждую сущность можно отдельно. И при вызове команды заполнять исключительно с JSON. Парсеры, если они выполнини свою функцию можно упразднить (имеется ввиду не надо использовать сами парсеры при заполнении БД)

# Как нужно делать?

**City**
Тут уже видел файл, и если это все города, так и оставляем

**Nosology**
По заказчику такой список:
Нарушение слуха 
Нарушение зрения
Нарушением опорно-двигательного аппарата 
Задержкой психического развития 
Тяжелыми нарушениями речи (ТНР), 
Расстройства аттического спектра (РАС), 
Интеллектуальные нарушения
Ни одна из выше перечисленны

**Discipline**
Тут видимо нужно связать для каждой из 3 дисциплин свой level
В следж хоккее у нас 6 числовых статусов от 1 до 6
в хоккее незрячих :В1, В2, В3, В4, В5, б\к
В специальном хоккее: А, В, С

**Team** **Player** **StaffTeamMember**
Тут конечно сложнее, хотя бы заполнить что получилось и сделать какую то заметку, где не получилось. Будем проходить вручную

**User**
Эта сущность нам неизвестна, оставляем пустой

# Где?

adaptive_hockey_federation/core/fixtures

**Comment by wildcat3333** [comment]
@KonstantinRaikhert, привет!  правильно понимаю, что парсером прогнали один раз, далее вообще его вызов убираем из fill-db, данные в data.json зафиксировали  и далее уже будут передаваться в архиве вместе с сущностями для загрузки в базу?

**Comment by KonstantinRaikhert** [comment]
Да, разделяем настоящие данные и фиктивные

**Comment by wildcat3333** [comment]
@KonstantinRaikhert  подскажи, какие есть диагнозы чтобы сделать фикстуру для нее diagnosis

**Comment by KonstantinRaikhert** [comment]
@wildcat3333 

Категории нозологий заболеваний:
Нарушение слуха 
Нарушение зрения
Нарушением опорно-двигательного аппарата 
Задержкой психического развития 
Тяжелыми нарушениями речи (ТНР), 
Расстройства аттического спектра (РАС), 
Интеллектуальные нарушения
Ни одна из выше перечисленных

Хотя это категории, а видимо сами диагнозы либо вручную по карточкам будем собирать, либо если их нет - оставим на заполнение заказчику
