### ISSUE TITLE
Создание фабрик на все оставшиеся сущности

### ISSUE THREAD

**Issue by KonstantinRaikhert** [Studio-Yandex-Practicum/adaptive_hockey_federation#86]
# Зачем?

Сначала хотелось использовать реальные данные и как то попробовать их получить скорее, но процесс кропотливый. И лучше разобраться с инструментами генерации тестовых данных. Поэтому разделим и будем идти параллельно.

В этой таске делаем исключительно всё при помощи фабрик.
Нужно сделать генерацию всех сущностей моделей отдельной командой. Например ```python manage.py fill-test-db```

# Как нужно делать?

Пройдёмся по диаграмме:

**Users** 
Нам нужно создать 3 администратора, 2 модератора, 15 представителей команд

**City**
Создаём 20 городов

**Nosology**
Тип нозологии, у заказчика их 8. Делаем так же 8. От 3 до 5 слов в названии.

**Diagnosis**
Сам диагноз. Здесь предлагаю сделать рандом. Для каждого типа нозологии от 3 до 5 диагнозов.

**DisciplineName**
Всего их 3 у заказчика. Делаем так же 3. Название из 2 слов.

**DisciplineLevel**
Здесь нужно сделать генерацию типа "А1" -  буква и цифра. Для каждой дисциплины 5-6 объектов.

**Disciline**
Тут необходимо связать 2 фабрики DisciplineName DisciplineLevel
Суть в том, чтобы для каждой дисциплины выбирались свои уровни (числовые статусы). У каждой свои 5-6 объектов.

**StaffMember**
Генерируем 25 сущностей

**StaffTeamMember**
Генерируем 15 тренеров и 10 остальных. Рандомно можно заполнить квалификацию (5 слов) и заметки (7 - 10 слов)

**Team**
Тут уже на подумать. Давайте создадим всего 20 команд. По команде из города. Разделение по дисциплинам на усмотрение, но наверно минимум 3 команды по каждой дисциплине. У каждой команды по 1 тренеру (тут специально заложено, что тренер может быть один у 2 или более команд). Другие члены команды опционально, можно добавить по одному.
У каждой команды есть куратор (представитель в БД). Привязываем к команде User. Игроков в команде минимум 10 и должен присутствовать капитан и ассистент.

**Player**
Количество создаваемых игроков на команду от 10 до 20, предлагаю рандом.

Задачка нетривиальна. Думаю нужно выполнять вдвоём.
Если много непонятного, давайте созвонимся и обсудим)
Сначала реализуем фабрики на каждую сущность, потом делаем команду с заполнением БД. 

# Где?

adaptive_hockey_federation/main/factories.py
adaptive_hockey_federation/core/management/commands/ (делаем отдельную команду)

**Comment by KonstantinRaikhert** [comment]
@IvanFilippov74 @Pnazarov86 Ребят, привет! И с прошедшими!)
Как у вас дела, идёт процесс по таске?

**Comment by IvanFilippov74** [comment]
Привет! И тебя с прошедшими=). Остались Команды и Игроки. В остальных пофиксили всё баги, работают и создают то что нужно. Если есть необходимость, могу ПР отправить, и заниматься оставшимися. По сроку постараюсь завтра к вечеру закончить,   но обещать не могу, там таблицы побольше могут трудности возникнуть. =)

**Comment by KonstantinRaikhert** [comment]
> Привет! И тебя с прошедшими=). Остались Команды и Игроки. В остальных пофиксили всё баги, работают и создают то что нужно. Если есть необходимость, могу ПР отправить, и заниматься оставшимися. По сроку постараюсь завтра к вечеру закончить, но обещать не могу, там таблицы побольше могут трудности возникнуть. =)

Хорошо) Можешь отправить, посмотрю, и дальше продолжать.

**Comment by Pnazarov86** [comment]
Привет, и тебя с прошедшим!))
Да, большая часть сделана. Меня, сразу после праздников, угораздило заболеть((. Но постараемся добить таску, в ближайшие дни.

**Comment by KonstantinRaikhert** [comment]
> Привет, и тебя с прошедшим!))
> 
> Да, большая часть сделана. Меня, сразу после праздников, угораздило заболеть((. Но постараемся добить таску, в ближайшие дни. 

Вот блин. Выздоравливай! Здоровье важнее🙂
