### ISSUE TITLE
Реализовать изменение и удаление пользователей

### ISSUE THREAD

**Issue by KonstantinRaikhert** [Studio-Yandex-Practicum/adaptive_hockey_federation#87]
# Зачем?

Необходимо добавить возможность изменять и удалять пользователей в интерфейсе.
ВАЖНО! Удалять может только администратор. Изменять администратор модератор. Просматривать все.

# Как нужно делать?

![2023-12-27_01-08](https://github.com/Studio-Yandex-Practicum/adaptive_hockey_federation/assets/69113745/792f63c9-b6c0-47e8-99a4-8ab63696b414)

Кнопки активны в зависимости от роли.

# Где?

adaptive_hockey_federation/users

**Comment by Aleksey-Krd** [comment]
@KonstantinRaikhert  какие данные можно менять?

**Comment by KonstantinRaikhert** [comment]
> @KonstantinRaikhert  какие данные можно менять?

Администратор может все данные менять и удалять пользователей
Модератор может менять данные, удалять нет
Остальные могут только менять свои данные.

Думаю так. Но хотя бы пока начать настройку ролей, не обязательно сейчас все исполнять

**Comment by Aleksey-Krd** [comment]
я имел ввиду, какие именно, имя фамилию, что должно быть на странице редактирования данных.

**Comment by Aleksey-Krd** [comment]
@KonstantinRaikhert  например админ нажимает на кнопку редактирования, и что он видит перед собой

**Comment by KonstantinRaikhert** [comment]
@Aleksey-Krd Новый ПР с этой карточкой будешь делать?

**Comment by Aleksey-Krd** [comment]
Буду, сегодня сделаю, всё же готово)
